// <auto-generated />
using Elsa.Workflows.Publishing.Persistence.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elsa.Workflows.Publishing.Persistence.EntityFrameworkCore.Migrations.PublishingSnapshotReview.MySql
{
    [DbContext(typeof(PublishingSnapshotReviewMySqlDbContext))]
    [Migration("20260915205155_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_bin")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.HasAnnotation("MySQL:Charset", "utf8mb4");

            modelBuilder.Entity("Elsa.Workflows.Publishing.Persistence.EntityFrameworkCore.Entities.PublicationPolicyEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<string>("DefaultAction")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<string>("DefaultSlotName")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("varchar(1200)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<string>("PolicyKey")
                        .IsRequired()
                        .HasMaxLength(1244)
                        .HasColumnType("varchar(1244)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<string>("PolicyKeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("TenantId")
                        .HasMaxLength(1200)
                        .HasColumnType("varchar(1200)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<string>("TenantIdHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<int>("UpdatedAtOffsetMinutes")
                        .HasColumnType("int");

                    b.Property<long>("UpdatedAtUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkflowDefinitionId")
                        .HasMaxLength(1200)
                        .HasColumnType("varchar(1200)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<string>("WorkflowDefinitionIdHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.HasKey("Id");

                    b.HasIndex("TenantIdHash", "PolicyKeyHash")
                        .IsUnique()
                        .HasDatabaseName("IX_elsa_publication_policies_scope_policyKey");

                    b.ToTable("elsa_publication_policies", (string)null);

                    b.HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");
                });

            modelBuilder.Entity("Elsa.Workflows.Publishing.Persistence.EntityFrameworkCore.Entities.PublicationProjectionIntentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("IntentId")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("varchar(1200)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<string>("IntentIdHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<byte[]>("IntentIdOrderKey")
                        .IsRequired()
                        .HasMaxLength(902)
                        .HasColumnType("varbinary(902)");

                    b.Property<string>("LastFailureCode")
                        .HasMaxLength(344)
                        .HasColumnType("varchar(344)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<string>("LastFailureMessage")
                        .HasMaxLength(1368)
                        .HasColumnType("varchar(1368)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<int?>("NextAttemptAtOffsetMinutes")
                        .HasColumnType("int");

                    b.Property<long?>("NextAttemptAtUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<string>("ProjectionKind")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("varchar(1200)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<string>("ProjectionKindHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<string>("PublicationId")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("varchar(1200)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<string>("PublicationIdHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<string>("TenantId")
                        .HasMaxLength(1200)
                        .HasColumnType("varchar(1200)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<string>("TenantIdHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.HasKey("Id");

                    b.HasIndex("TenantIdHash", "IntentIdHash")
                        .IsUnique()
                        .HasDatabaseName("IX_elsa_publication_projection_intents_scope_intentId");

                    b.HasIndex("TenantIdHash", "PublicationIdHash", "IntentIdOrderKey", "IntentIdHash")
                        .HasDatabaseName("IX_elsa_publication_projection_intents_scope_publication_order");

                    b.ToTable("elsa_publication_projection_intents", (string)null);

                    b.HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");
                });

            modelBuilder.Entity("Elsa.Workflows.Publishing.Persistence.EntityFrameworkCore.Entities.PublicationSnapshotReviewEntity", b =>
                {
                    b.Property<string>("PreflightToken")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<string>("ActivePublicationId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<string>("CandidateHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Incarnation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<long?>("PolicyRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("PolicySource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<string>("RequestedAction")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<string>("RequestedExpectedPublicationId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<string>("RequestedSlotName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<string>("SlotName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<long>("SlotRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("TenantId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.HasKey("PreflightToken");

                    b.HasIndex("ExpiresAt", "PreflightToken")
                        .HasDatabaseName("IX_elsa_publication_snapshot_reviews_expiresAt_preflightToken");

                    b.ToTable("elsa_publication_snapshot_reviews", (string)null);

                    b.HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");
                });
#pragma warning restore 612, 618
        }
    }
}
