// <auto-generated />
using Elsa.Cluster.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elsa.Cluster.EntityFrameworkCore.Migrations.ClusterMembership.PostgreSql
{
    [DbContext(typeof(ClusterMembershipPostgreSqlDbContext))]
    partial class ClusterMembershipPostgreSqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            // NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns omitted: the module stays provider-free.

            modelBuilder.Entity("Elsa.Cluster.EntityFrameworkCore.Entities.ClusterMemberEntity", b =>
                {
                    b.Property<string>("HostId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .UseCollation("C");

                    b.Property<string>("Incarnation")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .UseCollation("C");

                    b.Property<string>("CurrentHostId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .UseCollation("C");

                    b.Property<long>("ExpiryPeriodTicks")
                        .HasColumnType("bigint");

                    b.Property<long>("HeartbeatAtUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<long?>("LeftAtUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("ReportJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ReportRevision")
                        .HasColumnType("bigint");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("HostId", "Incarnation");

                    b.HasIndex("CurrentHostId")
                        .IsUnique();

                    b.HasIndex("SchemaVersion");

                    b.ToTable("elsa_cluster_members", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
