<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Events\Core\Elsa.Events.Core.csproj" />
    <ProjectReference Include="..\..\Core\Elsa.Workflows.Design.Core.csproj" />
    <ProjectReference Include="..\..\Validations\Core\Elsa.Workflows.Design.Validations.Core.csproj" />
  </ItemGroup>

</Project>
