<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>0.0.1-local</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CShells.Abstractions" />
    <PackageReference Include="DistributedLock.FileSystem" />
    <PackageReference Include="Elsa.Platform.PackageManifest.Generator" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Elsa.Locking.Core.csproj" />
  </ItemGroup>

</Project>
