// <auto-generated />
using System;
using Elsa.Activities.Design.Persistence.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elsa.Activities.Design.Persistence.EntityFrameworkCore.Migrations.ActivitiesDesign.Sqlite
{
    [DbContext(typeof(ActivitiesDesignSqliteDbContext))]
    [Migration("20260918220146_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Elsa.Activities.Design.Persistence.Core.Entities.ActivityDefinition", b =>
                {
                    b.Property<string>("TenantScopeKey")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(66)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdIdentityHash")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityTypeKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantKey")
                        .IsRequired()
                        .HasMaxLength(66)
                        .HasColumnType("TEXT");

                    b.HasKey("TenantScopeKey", "IdIdentityHash");

                    b.HasIndex("TenantKey", "ActivityTypeKey")
                        .IsUnique();

                    b.ToTable("elsa_activity_definitions", (string)null);
                });

            modelBuilder.Entity("Elsa.Activities.Design.Persistence.Core.Entities.ActivityDefinitionAuthoringState", b =>
                {
                    b.Property<string>("TenantScopeKey")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(66)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdIdentityHash")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<string>("ContentAuthority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionIdIdentityHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ForkedFrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadVersionId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadVersionIdIdentityHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendedVersionId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendedVersionIdIdentityHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantScopeKey", "IdIdentityHash");

                    b.HasIndex("TenantScopeKey", "DefinitionIdIdentityHash")
                        .IsUnique();

                    b.HasIndex("TenantScopeKey", "HeadVersionIdIdentityHash");

                    b.ToTable("elsa_activity_definition_authoring", (string)null);
                });

            modelBuilder.Entity("Elsa.Activities.Design.Persistence.Core.Entities.ActivityDefinitionDraft", b =>
                {
                    b.Property<string>("TenantScopeKey")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(66)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdIdentityHash")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionIdIdentityHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PresentationLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedVersionId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedVersionIdIdentityHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceVersionId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceVersionIdIdentityHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantScopeKey", "IdIdentityHash");

                    b.HasIndex("TenantScopeKey", "DefinitionIdIdentityHash", "IdIdentityHash");

                    b.ToTable("elsa_activity_definition_drafts", (string)null);
                });

            modelBuilder.Entity("Elsa.Activities.Design.Persistence.Core.Entities.ActivityDefinitionDraftLayout", b =>
                {
                    b.Property<string>("TenantScopeKey")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(66)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdIdentityHash")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftIdIdentityHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Records")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantScopeKey", "IdIdentityHash");

                    b.HasIndex("TenantScopeKey", "DraftIdIdentityHash")
                        .IsUnique();

                    b.ToTable("elsa_activity_definition_draft_layouts", (string)null);
                });

            modelBuilder.Entity("Elsa.Activities.Design.Persistence.Core.Entities.ActivityDefinitionDraftManagementProjectionRevision", b =>
                {
                    b.Property<string>("TenantScopeKey")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(66)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdIdentityHash")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionIdIdentityHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftIdIdentityHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PresentationLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderSchemaVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceIdIdentityHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SortKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceVersionId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceVersionIdIdentityHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidFromKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ValidFromSequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValidToKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ValidToSequenceExclusive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VisibilityKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TenantScopeKey", "IdIdentityHash");

                    b.HasIndex("TenantId", "ValidFromSequence", "ValidToSequenceExclusive");

                    b.HasIndex("TenantScopeKey", "ResourceIdIdentityHash", "ValidToSequenceExclusive");

                    b.ToTable("elsa_activity_management_drafts", (string)null);
                });

            modelBuilder.Entity("Elsa.Activities.Design.Persistence.Core.Entities.ActivityDefinitionManagementProjectionRevision", b =>
                {
                    b.Property<string>("TenantScopeKey")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(66)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdIdentityHash")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityTypeKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<string>("ContentAuthorityAuthorityKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentAuthorityAuthorityKeyJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentAuthorityCanonicalJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentAuthorityIntegrityHash")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ContentAuthorityIsValid")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER")
                        .HasComputedColumnSql("CASE WHEN json_valid(\"ContentAuthority\") = 1 THEN CASE WHEN \"ContentAuthorityKind\" IN (0, 1) AND json_type(\"ContentAuthority\") = 'object' AND json_type(\"ContentAuthority\", '$.kind') = 'integer' AND json_extract(\"ContentAuthority\", '$.kind') = \"ContentAuthorityKind\" AND json_type(\"ContentAuthority\", '$.authorityKey') = 'text' AND \"ContentAuthorityAuthorityKey\" = json_extract(\"ContentAuthority\", '$.authorityKey') AND json_valid(\"ContentAuthorityAuthorityKeyJson\") = 1 AND json_type(\"ContentAuthorityAuthorityKeyJson\") = 'text' AND json_extract(\"ContentAuthorityAuthorityKeyJson\", '$') = \"ContentAuthorityAuthorityKey\" AND length(trim(json_extract(\"ContentAuthority\", '$.authorityKey'), char(9,10,11,12,13,32,133,160,5760,8192,8193,8194,8195,8196,8197,8198,8199,8200,8201,8202,8232,8233,8239,8287,12288))) > 0 AND (((json_type(\"ContentAuthority\", '$.sourceId') IS NULL OR json_type(\"ContentAuthority\", '$.sourceId') = 'null') AND \"ContentAuthoritySourceId\" IS NULL AND \"ContentAuthoritySourceIdJson\" = 'null') OR (json_type(\"ContentAuthority\", '$.sourceId') = 'text' AND \"ContentAuthoritySourceId\" = json_extract(\"ContentAuthority\", '$.sourceId') AND json_valid(\"ContentAuthoritySourceIdJson\") = 1 AND json_type(\"ContentAuthoritySourceIdJson\") = 'text' AND json_extract(\"ContentAuthoritySourceIdJson\", '$') = \"ContentAuthoritySourceId\" AND length(trim(json_extract(\"ContentAuthority\", '$.sourceId'), char(9,10,11,12,13,32,133,160,5760,8192,8193,8194,8195,8196,8197,8198,8199,8200,8201,8202,8232,8233,8239,8287,12288))) > 0)) AND json_type(\"ContentAuthority\", '$.integrityHash') = 'text' AND \"ContentAuthorityIntegrityHash\" = json_extract(\"ContentAuthority\", '$.integrityHash') AND (\"ContentAuthorityKind\" = 1 OR json_type(\"ContentAuthority\", '$.sourceId') IS NULL OR json_type(\"ContentAuthority\", '$.sourceId') = 'null') THEN 1 ELSE 0 END ELSE 0 END", false);

                    b.Property<string>("ContentAuthorityJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("ContentAuthority");

                    b.Property<int>("ContentAuthorityKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentAuthoritySourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentAuthoritySourceIdJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionIdIdentityHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<long>("DraftCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Head")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadVersionId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadVersionIdIdentityHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Recommendation")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendationProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendedVersionId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendedVersionIdIdentityHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceIdIdentityHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SortKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidFromKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ValidFromSequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValidToKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ValidToSequenceExclusive")
                        .HasColumnType("INTEGER");

                    b.Property<long>("VersionCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VisibilityKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TenantScopeKey", "IdIdentityHash");

                    b.HasIndex("TenantId", "ValidFromSequence", "ValidToSequenceExclusive");

                    b.HasIndex("TenantScopeKey", "ResourceIdIdentityHash", "ValidToSequenceExclusive");

                    b.ToTable("elsa_activity_management_definitions", (string)null);
                });

            modelBuilder.Entity("Elsa.Activities.Design.Persistence.Core.Entities.ActivityDefinitionVersion", b =>
                {
                    b.Property<string>("TenantScopeKey")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(66)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdIdentityHash")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<string>("ConsumerKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsumerSchemaVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionIdIdentityHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptorPayloadSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptorType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DesignFacetsSource")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExecutionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("InputsSource")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputsSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderSchemaVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SemVerSortKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TenantScopeKey", "IdIdentityHash");

                    b.HasIndex("TenantScopeKey", "DefinitionIdIdentityHash", "SemVerSortKey")
                        .IsUnique();

                    b.ToTable("elsa_activity_definition_versions_v2", (string)null);
                });

            modelBuilder.Entity("Elsa.Activities.Design.Persistence.Core.Entities.ActivityDefinitionVersionLayout", b =>
                {
                    b.Property<string>("TenantScopeKey")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(66)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdIdentityHash")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionVersionId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionVersionIdIdentityHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Records")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantScopeKey", "IdIdentityHash");

                    b.HasIndex("TenantScopeKey", "DefinitionVersionIdIdentityHash")
                        .IsUnique();

                    b.ToTable("elsa_activity_version_layouts", (string)null);
                });

            modelBuilder.Entity("Elsa.Activities.Design.Persistence.Core.Entities.ActivityDefinitionVersionManagementProjectionRevision", b =>
                {
                    b.Property<string>("TenantScopeKey")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(66)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdIdentityHash")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionIdIdentityHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionVersionId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionVersionIdIdentityHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Lifecycle")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderSchemaVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceIdIdentityHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SortKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidFromKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ValidFromSequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValidToKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ValidToSequenceExclusive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VisibilityKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TenantScopeKey", "IdIdentityHash");

                    b.HasIndex("TenantId", "ValidFromSequence", "ValidToSequenceExclusive");

                    b.HasIndex("TenantScopeKey", "ResourceIdIdentityHash", "ValidToSequenceExclusive");

                    b.ToTable("elsa_activity_management_versions", (string)null);
                });

            modelBuilder.Entity("Elsa.Activities.Design.Persistence.Core.Entities.ActivityDefinitionVersionPublication", b =>
                {
                    b.Property<string>("TenantScopeKey")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(66)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdIdentityHash")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityTypeKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClosedTemplateCount")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<string>("Contract")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionIdIdentityHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionVersionId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionVersionIdIdentityHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("DirectDependencyCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Lifecycle")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResolutionKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourceMeasurements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResumeTargetCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuntimeRequirements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceDraftId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceReferenceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceVersionId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceVersionIdIdentityHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TenantScopeKey", "IdIdentityHash");

                    b.HasIndex("TenantScopeKey", "DefinitionVersionIdIdentityHash")
                        .IsUnique();

                    b.HasIndex("TenantScopeKey", "DefinitionIdIdentityHash", "IdIdentityHash");

                    b.ToTable("elsa_activity_version_publications", (string)null);
                });

            modelBuilder.Entity("Elsa.Activities.Design.Persistence.Core.Entities.ActivityDependencyEdge", b =>
                {
                    b.Property<string>("TenantScopeKey")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(66)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdIdentityHash")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("ChildIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChildSlotName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DependencyTemplateHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DependencyVersionId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("DependencyVersionIdIdentityHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberUsage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeOrigin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OccurrenceId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("OccurrenceIdIdentityHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerTemplateHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerVersionId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerVersionIdIdentityHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentOccurrenceId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentOccurrenceIdIdentityHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantScopeKey", "IdIdentityHash");

                    b.HasIndex("TenantScopeKey", "DependencyVersionIdIdentityHash");

                    b.HasIndex("TenantScopeKey", "OwnerVersionIdIdentityHash");

                    b.HasIndex("TenantScopeKey", "OwnerVersionIdIdentityHash", "OccurrenceIdIdentityHash", "DependencyVersionIdIdentityHash")
                        .IsUnique();

                    b.ToTable("elsa_activity_dependency_edges", (string)null);
                });

            modelBuilder.Entity("Elsa.Activities.Design.Persistence.Core.Entities.ActivityDependencyProjectionState", b =>
                {
                    b.Property<string>("TenantScopeKey")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(66)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdIdentityHash")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AsOf")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RebuildId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantScopeKey", "IdIdentityHash");

                    b.ToTable("elsa_activity_dependency_projection", (string)null);
                });

            modelBuilder.Entity("Elsa.Activities.Design.Persistence.Core.Entities.ActivityDraftValidationState", b =>
                {
                    b.Property<string>("TenantScopeKey")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(66)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdIdentityHash")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diagnostics")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftIdIdentityHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ValidatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantScopeKey", "IdIdentityHash");

                    b.HasIndex("TenantScopeKey", "DraftIdIdentityHash", "Revision")
                        .IsUnique();

                    b.ToTable("elsa_activity_draft_validations", (string)null);
                });

            modelBuilder.Entity("Elsa.Activities.Design.Persistence.Core.Entities.ActivityForkCandidate", b =>
                {
                    b.Property<string>("TenantScopeKey")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(66)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdIdentityHash")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessBindingFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorIdentityHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppliedIdempotencyKey")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppliedIdempotencyKeyIdentityHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorizationProfile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateIdIdentityHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MigrationDiagnostics")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewIdempotencyKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReservedAuthoringState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReservedDefinition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReservedDraft")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReservedLayout")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RetainUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("RetentionKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceContractFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceDefinitionId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceDefinitionIdIdentityHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceLifecycle")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceProviderFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceVersionId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceVersionIdIdentityHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetContractFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetProviderFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantScopeKey", "IdIdentityHash");

                    b.HasIndex("TenantScopeKey", "ActorIdentityHash", "CandidateIdIdentityHash")
                        .IsUnique();

                    b.HasIndex("TenantScopeKey", "RetentionKey", "IdIdentityHash");

                    b.ToTable("elsa_activity_fork_candidates", (string)null);
                });

            modelBuilder.Entity("Elsa.Activities.Design.Persistence.Core.Entities.ActivityForkReceipt", b =>
                {
                    b.Property<string>("TenantScopeKey")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(66)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdIdentityHash")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessBindingFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityTypeKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorIdentityHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthoringState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorizationProfile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateIdIdentityHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionIdIdentityHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionMaterialJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Draft")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftIdIdentityHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyIdentityHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MigrationDiagnostics")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicCandidateId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicCandidateIdIdentityHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantScopeKey", "IdIdentityHash");

                    b.HasIndex("TenantScopeKey", "ActorIdentityHash", "IdempotencyIdentityHash")
                        .IsUnique();

                    b.ToTable("elsa_activity_fork_receipts", (string)null);
                });

            modelBuilder.Entity("Elsa.Activities.Design.Persistence.Core.Entities.ActivityManagementProjectionSnapshot", b =>
                {
                    b.Property<string>("TenantScopeKey")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(66)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdIdentityHash")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AsOf")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantScopeKey", "IdIdentityHash");

                    b.HasIndex("Sequence")
                        .IsUnique();

                    b.ToTable("elsa_activity_management_snapshots", (string)null);
                });

            modelBuilder.Entity("Elsa.Activities.Design.Persistence.Core.Entities.ActivityManagementProjectionWatermark", b =>
                {
                    b.Property<string>("TenantScopeKey")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(66)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdIdentityHash")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AdvancedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("RetainedFromSequence")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantScopeKey", "IdIdentityHash");

                    b.ToTable("elsa_activity_management_watermarks", (string)null);
                });

            modelBuilder.Entity("Elsa.Activities.Design.Persistence.EntityFrameworkCore.ActivityDesignOperationRecord", b =>
                {
                    b.Property<string>("TenantScopeKey")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(66)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdIdentityHash")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthoritativeResultFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthoritativeResultJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalRequestFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MutatedUnitsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationKeyIdentityHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationKindIdentityHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantScopeKey", "IdIdentityHash");

                    b.HasIndex("TenantScopeKey", "OperationKindIdentityHash", "OperationKeyIdentityHash")
                        .IsUnique();

                    b.ToTable("elsa_activity_design_operations", (string)null);
                });

            modelBuilder.Entity("Elsa.Activities.Design.Persistence.EntityFrameworkCore.ActivityUpgradeApplyReceiptRecord", b =>
                {
                    b.Property<string>("TenantScopeKey")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(66)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdIdentityHash")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKeyHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanIdIdentityHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptIdIdentityHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantScopeKey", "IdIdentityHash");

                    b.HasIndex("TenantScopeKey", "PlanIdIdentityHash", "IdempotencyKeyHash")
                        .IsUnique();

                    b.ToTable("elsa_activity_upgrade_apply_receipts", (string)null);
                });

            modelBuilder.Entity("Elsa.Activities.Design.Persistence.EntityFrameworkCore.ActivityUpgradePlanRecord", b =>
                {
                    b.Property<string>("TenantScopeKey")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(66)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdIdentityHash")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanIdIdentityHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantScopeKey", "IdIdentityHash");

                    b.ToTable("elsa_activity_upgrade_plans", (string)null);
                });

            modelBuilder.Entity("Elsa.Activities.Design.Persistence.EntityFrameworkCore.Entities.ActivityAvailabilitySettingsRecord", b =>
                {
                    b.Property<string>("TenantScopeKey")
                        .HasMaxLength(66)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeIdentityHash")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.HasKey("TenantScopeKey", "ScopeIdentityHash");

                    b.ToTable("elsa_activity_availability_settings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
