<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="CShells.Abstractions" />
    <PackageReference Include="Elsa.Platform.PackageManifest.Generator" PrivateAssets="all" />
    <PackageReference Include="Groundwork.Kernel" />
    <PackageReference Include="Groundwork.Query.Model" />
    <PackageReference Include="Groundwork.Store" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Elsa.Workflows.Runtime.Distributed.csproj" />
    <ProjectReference Include="..\..\..\..\..\Persistence\Core\Elsa.Persistence.Core.csproj" />
    <ProjectReference Include="..\..\..\..\..\Persistence\Groundwork\V2\Elsa.Persistence.Groundwork.V2.csproj" />
  </ItemGroup>

</Project>
