<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <PackageReference Include="Groundwork.Sqlite" VersionOverride="0.4.0-preview.3" />
    <PackageReference Include="Groundwork.Testing" VersionOverride="0.4.0-preview.3" />
    <PackageReference Include="CShells.FastEndpoints" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\Api\Compatibility\Testing\Elsa.Api.Compatibility.Testing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\..\..\src\Elsa\Foundation\Identity\Api\Elsa.Foundation.Identity.Api.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\..\src\Elsa\Foundation\Identity\AspNetCoreIdentity\Groundwork\Elsa.Foundation.Identity.AspNetCoreIdentity.Groundwork.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\..\src\Elsa\Foundation\Identity\Persistence\Groundwork\Elsa.Foundation.Identity.Persistence.Groundwork.csproj" />
    <ProjectReference Include="..\ProcessProbe\Elsa.Foundation.Identity.AspNetCoreIdentity.Groundwork.ProcessProbe.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\..\..\..\Persistence\Groundwork\Testing\Elsa.Persistence.Groundwork.Testing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Testing\IdentityProcessProbeProtocol.cs" Link="Testing\IdentityProcessProbeProtocol.cs" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <Target Name="CopyIdentityProcessProbeArtifacts" AfterTargets="Build">
    <RemoveDir Directories="$(TargetDir)IdentityProcessProbe" />
    <ItemGroup>
      <_IdentityProcessProbeArtifact Include="$(MSBuildProjectDirectory)/../ProcessProbe/bin/$(Configuration)/$(TargetFramework)/**/*" />
    </ItemGroup>
    <Copy SourceFiles="@(_IdentityProcessProbeArtifact)" DestinationFiles="@(_IdentityProcessProbeArtifact->'$(TargetDir)IdentityProcessProbe/%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>

</Project>
