// <auto-generated />
using Elsa.Workflows.Runtime.Distributed.Persistence.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elsa.Workflows.Runtime.Distributed.Persistence.EntityFrameworkCore.Migrations.ExecutionPlacement.PostgreSql
{
    [DbContext(typeof(ExecutionPlacementPostgreSqlDbContext))]
    partial class ExecutionPlacementPostgreSqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            // NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns omitted: the module stays provider-free.

            modelBuilder.Entity("Elsa.Persistence.EntityFramework.SchemaFinalization.EfDatabaseIdentityRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("DatabaseIdentity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("SchemaVersion");

                    b.ToTable("__ElsaDatabaseIdentity_ElsaDistributedExecutionPlacement", (string)null);
                });

            modelBuilder.Entity("Elsa.Persistence.EntityFramework.SchemaFinalization.EfSchemaFinalizationRecordRow", b =>
                {
                    b.Property<string>("Family")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DatabaseIdentity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FinalizedVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("FinishHistoryJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FinishJson")
                        .HasColumnType("text");

                    b.Property<string>("HistoryJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HoldsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IntentJson")
                        .HasColumnType("text");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Family");

                    b.HasIndex("SchemaVersion");

                    b.ToTable("__ElsaSchemaFinalization_ElsaDistributedExecutionPlacement", (string)null);
                });

            modelBuilder.Entity("Elsa.Workflows.Runtime.Distributed.Persistence.EntityFrameworkCore.Entities.ExecutionPlacementLeaseEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AcquiredAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExpiresAtOffsetMinutes")
                        .HasColumnType("integer");

                    b.Property<long>("ExpiresAtUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("boolean");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OwnerIdHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("PlacementToken")
                        .HasColumnType("bigint");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScopeKeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("WorkflowExecutionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<byte[]>("WorkflowExecutionIdOrderKey")
                        .IsRequired()
                        .HasMaxLength(258)
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("SchemaVersion");

                    b.HasIndex("ScopeKeyHash", "OwnerIdHash", "IsReleased", "ExpiresAtUtcTicks", "WorkflowExecutionIdOrderKey");

                    b.ToTable("elsa_distributed_execution_placement", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
