// <auto-generated />
using Elsa.Foundation.Identity.Persistence.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elsa.Foundation.Identity.Persistence.EntityFrameworkCore.Migrations.IdentityProviderConfiguration.MySql
{
    [DbContext(typeof(IdentityProviderConfigurationMySqlDbContext))]
    [Migration("20260918232117_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.HasAnnotation("MySQL:Charset", "utf8mb4");

            modelBuilder.Entity("Elsa.Foundation.Identity.Persistence.EntityFrameworkCore.Entities.GlobalProviderConfigurationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .UseCollation("utf8mb4_0900_bin")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PermissionPropagation")
                        .HasColumnType("int");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("varchar(1600)")
                        .UseCollation("utf8mb4_0900_bin")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<string>("ProviderLookupKey")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("varchar(1600)")
                        .UseCollation("utf8mb4_0900_bin")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("SupportsApplicationManagement")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsGroupSync")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsLocalRoleManagement")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsLocalUserManagement")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsRefresh")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsRevocation")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsTokenIssuance")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TenantId")
                        .HasMaxLength(1600)
                        .HasColumnType("varchar(1600)")
                        .UseCollation("utf8mb4_0900_bin")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<string>("TenantLookupKey")
                        .HasMaxLength(1600)
                        .HasColumnType("varchar(1600)")
                        .UseCollation("utf8mb4_0900_bin")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.HasKey("Id");

                    b.ToTable("identity_global_provider_configurations", (string)null);
                });

            modelBuilder.Entity("Elsa.Foundation.Identity.Persistence.EntityFrameworkCore.Entities.TenantProviderConfigurationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .UseCollation("utf8mb4_0900_bin")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PermissionPropagation")
                        .HasColumnType("int");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("varchar(1600)")
                        .UseCollation("utf8mb4_0900_bin")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<string>("ProviderLookupKey")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("varchar(1600)")
                        .UseCollation("utf8mb4_0900_bin")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("SupportsApplicationManagement")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsGroupSync")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsLocalRoleManagement")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsLocalUserManagement")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsRefresh")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsRevocation")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsTokenIssuance")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("varchar(1600)")
                        .UseCollation("utf8mb4_0900_bin")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.Property<string>("TenantLookupKey")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("varchar(1600)")
                        .UseCollation("utf8mb4_0900_bin")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_0900_bin");

                    b.HasKey("Id");

                    b.ToTable("identity_provider_configurations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
