<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="CShells.Abstractions" />
    <PackageReference Include="CShells.AspNetCore.Abstractions" />
    <PackageReference Include="Elsa.Platform.PackageManifest.Generator" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Elsa.Expressions.Core.csproj" />
    <ProjectReference Include="..\..\Api\AspNetCore\Elsa.Api.AspNetCore.csproj" />
    <ProjectReference Include="..\..\Api\Endpoints\Elsa.Api.Endpoints.csproj" />
    <ProjectReference Include="..\..\Api\Capabilities\Elsa.Api.Capabilities.csproj" />
    <ProjectReference Include="..\..\Mediator\Core\Elsa.Mediator.Core.csproj" />
  </ItemGroup>

</Project>
