<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.0.1-local</Version>
  </PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Elsa.Locking.Core\Elsa.Locking.Core.csproj" />
	  <ProjectReference Include="..\Elsa.Events.Core\Elsa.Events.Core.csproj" />
	  <ProjectReference Include="..\Elsa.Events\Elsa.Events.csproj" />
	  <ProjectReference Include="..\Elsa.Serialization.Core\Elsa.Serialization.Core.csproj" />
	  <ProjectReference Include="..\Elsa.Workflows.Design.Persistence.Core\Elsa.Workflows.Design.Persistence.Core.csproj" />
	  <ProjectReference Include="..\Elsa.Workflows.Design.Validations.Core\Elsa.Workflows.Design.Validations.Core.csproj" />
	  <ProjectReference Include="..\Elsa.Persistence.EFCore\Elsa.Persistence.EFCore.csproj" />
	</ItemGroup>

</Project>
