<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="CShells.Abstractions" />
    <PackageReference Include="Elsa.Platform.PackageManifest.Generator" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Runtime\Core\Elsa.Activities.Runtime.Core.csproj" />
    <ProjectReference Include="..\..\Primitives\Primitives\Elsa.Primitives.csproj" />
    <ProjectReference Include="..\..\Expressions\JavaScript\Core\Elsa.Expressions.JavaScript.Core.csproj" />
  </ItemGroup>

</Project>
