<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Groundwork.Testing" VersionOverride="0.2.0-preview.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Activities\ControlFlow\Elsa.Activities.ControlFlow.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Activities\Design\Core\Elsa.Activities.Design.Core.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Activities\Design\Reconciliation\Core\Elsa.Activities.Design.Reconciliation.Core.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Activities\Design\Reconciliation\Elsa.Activities.Design.Reconciliation.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Activities\Runtime\Core\Elsa.Activities.Runtime.Core.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Expressions\JavaScript\Core\Elsa.Expressions.JavaScript.Core.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Expressions\JavaScript\Elsa.Expressions.JavaScript.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Expressions\JavaScript\Rendering\Core\Elsa.Expressions.JavaScript.Rendering.Core.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Expressions\JavaScript\Rendering\Elsa.Expressions.JavaScript.Rendering.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Events\Core\Elsa.Events.Core.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Events\Elsa.Events.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Mediator\Elsa.Mediator.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Serialization\SystemText\Elsa.Serialization.SystemText.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Primitives\Primitives\Elsa.Primitives.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Primitives\Hosting\Elsa.Primitives.Hosting.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Locking\Core\Elsa.Locking.Core.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Workflows\Design\Core\Elsa.Workflows.Design.Core.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Workflows\Dashboard\Elsa.Workflows.Dashboard.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Workflows\Design\Api\Elsa.Workflows.Design.Api.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Workflows\Design\Api\Core\Elsa.Workflows.Design.Api.Core.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Workflows\Design\Persistence\Core\Elsa.Workflows.Design.Persistence.Core.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Workflows\Design\Persistence\Groundwork\Elsa.Workflows.Design.Persistence.Groundwork.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Workflows\Design\Reconciliation\Elsa.Workflows.Design.Reconciliation.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Workflows\Design\Reconciliation\Core\Elsa.Workflows.Design.Reconciliation.Core.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Workflows\Design\Reconciliation\Git\Elsa.Workflows.Design.Reconciliation.Git.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Workflows\Design\Reconciliation\Json\Elsa.Workflows.Design.Reconciliation.Json.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Workflows\Design\Validations\Elsa.Workflows.Design.Validations.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Workflows\Design\Validations\Core\Elsa.Workflows.Design.Validations.Core.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Workflows\Design\JavaScript\Elsa.Workflows.Design.JavaScript.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Persistence\Groundwork\Sqlite\Elsa.Persistence.Groundwork.Sqlite.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Persistence\Groundwork\Sqlite\Unified\Elsa.Persistence.Groundwork.Sqlite.Unified.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Elsa\Persistence\Groundwork\ReferenceComposition\Elsa.Persistence.Groundwork.ReferenceComposition.csproj" />
    <ProjectReference Include="..\..\..\Persistence\Groundwork\Testing\Elsa.Persistence.Groundwork.Testing.csproj" />
  </ItemGroup>

</Project>
