// <auto-generated />
using System;
using Elsa.Secrets.Persistence.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elsa.Secrets.Persistence.EntityFrameworkCore.Migrations.SqlServer
{
    [DbContext(typeof(SecretsSqlServerDbContext))]
    partial class SecretsSqlServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            // SqlServerModelBuilderExtensions.UseIdentityColumns omitted: the module stays provider-free.

            modelBuilder.Entity("Elsa.Secrets.Persistence.EntityFrameworkCore.Entities.SecretRecord", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("Latin1_General_BIN2");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("Latin1_General_BIN2");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("DisplayNameSearchKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasNonExpiringActiveVersion")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("MaxActiveVersionExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NameSearchKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScopeLookupKey")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Latin1_General_BIN2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("StoreNameLookupKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Latin1_General_BIN2");

                    b.Property<string>("TypeNameLookupKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Latin1_General_BIN2");

                    b.HasKey("TenantId", "NormalizedName");

                    b.HasIndex("TenantId", "Status", "NormalizedName")
                        .HasDatabaseName("IX_elsa_secrets_tenantId_status_normalizedName");

                    b.ToTable("elsa_secrets", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
