using System.Text.Json;

namespace Elsa.Server.ExtensionBuilder;

internal interface IExtensionBuilderTemplateCatalog
{
    IReadOnlyList<ExtensionTemplate> List();
    ExtensionTemplate? Find(string templateId);
}

internal sealed class ExtensionBuilderTemplateCatalog : IExtensionBuilderTemplateCatalog
{
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web);
    private readonly ExtensionTemplate[] _templates;

    public ExtensionBuilderTemplateCatalog()
    {
        _templates =
        [
            CreateElsaActivityTemplate(),
            CreateGenericDotNetTemplate()
        ];
    }

    public IReadOnlyList<ExtensionTemplate> List() => _templates;

    public ExtensionTemplate? Find(string templateId) =>
        _templates.FirstOrDefault(x => string.Equals(x.Id, templateId, StringComparison.OrdinalIgnoreCase));

    private static ExtensionTemplate CreateElsaActivityTemplate()
    {
        const string packageId = "Elsa.ExtensionBuilder.Activity";
        var manifest = Manifest(
            "Extension Builder Activity",
            "Starter Elsa activity module generated by Extension Builder.",
            ["Activities", "Extension Builder"],
            $$"""
            {
              "package": {
                "id": "{{packageId}}",
                "version": "0.1.0"
              },
              "features": [
                {
                  "id": "ExtensionBuilderActivity",
                  "displayName": "Extension Builder Activity",
                  "description": "Starter activity contributed by an Extension Builder package.",
                  "category": "Activities",
                  "extensions": {
                    "cshellsFeatureName": "ExtensionBuilderActivity"
                  }
                }
              ]
            }
            """);

        return new(
            "elsa-activity-module",
            ExtensionTemplateKind.ElsaActivityModule,
            "Elsa activity/module",
            "A buildable NuGet package with an Elsa package manifest and starter activity source.",
            packageId,
            "0.1.0",
            "net10.0",
            manifest,
            [
                new("ExtensionBuilderActivity.csproj", ProjectFile(packageId, "0.1.0", "net10.0"), ProjectFileKind.Project),
                new("elsa-package.json", manifest.Content.GetRawText(), ProjectFileKind.Manifest),
                new("Activities/ExtensionBuilderActivity.cs", """
                    namespace Elsa.ExtensionBuilder.Activity;

                    public sealed class ExtensionBuilderActivity
                    {
                        public string Execute() => "Hello from Extension Builder";
                    }
                    """, ProjectFileKind.Source)
            ]);
    }

    private static ExtensionTemplate CreateGenericDotNetTemplate()
    {
        const string packageId = "Elsa.ExtensionBuilder.Generic";
        var manifest = Manifest(
            "Generic Extension Builder Package",
            "Generic .NET package generated by Extension Builder.",
            ["Extension Builder"],
            $$"""
            {
              "package": {
                "id": "{{packageId}}",
                "version": "0.1.0"
              },
              "features": []
            }
            """);

        return new(
            "generic-dotnet",
            ExtensionTemplateKind.GenericDotNet,
            "Generic .NET class library",
            "A buildable generic .NET class library package with no Elsa-specific feature contribution.",
            packageId,
            "0.1.0",
            "net10.0",
            manifest,
            [
                new("GenericExtension.csproj", ProjectFile(packageId, "0.1.0", "net10.0"), ProjectFileKind.Project),
                new("elsa-package.json", manifest.Content.GetRawText(), ProjectFileKind.Manifest),
                new("Class1.cs", """
                    namespace Elsa.ExtensionBuilder.Generic;

                    public sealed class Class1
                    {
                        public string GetMessage() => "Hello from a generic Extension Builder package";
                    }
                    """, ProjectFileKind.Source)
            ]);
    }

    internal static string ProjectFile(string packageId, string version, string targetFramework) =>
        $$"""
        <Project Sdk="Microsoft.NET.Sdk">
          <PropertyGroup>
            <TargetFramework>{{targetFramework}}</TargetFramework>
            <Nullable>enable</Nullable>
            <ImplicitUsings>enable</ImplicitUsings>
            <PackageId>{{packageId}}</PackageId>
            <Version>{{version}}</Version>
            <Authors>Elsa Extension Builder</Authors>
            <Description>Generated by Elsa Extension Builder.</Description>
            <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
          </PropertyGroup>
          <ItemGroup>
            <None Include="elsa-package.json" Pack="true" PackagePath="" />
          </ItemGroup>
        </Project>
        """;

    private static ExtensionProjectManifest Manifest(string displayName, string? description, IReadOnlyList<string> categories, string json) =>
        new(displayName, description, categories, JsonDocument.Parse(json).RootElement.Clone());

    public static JsonElement RewriteManifest(JsonElement manifest, string packageId, string version)
    {
        using var document = JsonDocument.Parse(manifest.GetRawText());
        using var stream = new MemoryStream();
        using (var writer = new Utf8JsonWriter(stream, new() { Indented = true }))
        {
            writer.WriteStartObject();
            foreach (var property in document.RootElement.EnumerateObject())
            {
                if (property.NameEquals("package"))
                {
                    writer.WritePropertyName("package");
                    writer.WriteStartObject();
                    writer.WriteString("id", packageId);
                    writer.WriteString("version", version);
                    writer.WriteEndObject();
                    continue;
                }

                property.WriteTo(writer);
            }
            writer.WriteEndObject();
        }

        return JsonDocument.Parse(stream.ToArray()).RootElement.Clone();
    }
}
