<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Elsa.Activities.Design.Core.csproj" />
    <ProjectReference Include="..\..\..\..\Workflows\Design\Persistence\Core\Elsa.Workflows.Design.Persistence.Core.csproj" />
    <ProjectReference Include="..\..\..\..\Primitives\Primitives\Elsa.Primitives.csproj" />
  </ItemGroup>

</Project>
