using Elsa.Activities.Design.Core.Contracts;
using Elsa.Activities.Design.Persistence.Core.Contracts;
using Elsa.Activities.Design.Persistence.Core.Entities;
using Elsa.Activities.Design.Reconciliation.Core;
using Elsa.Activities.Design.Reconciliation.Options;
using Elsa.Events.Core.Contracts;
using Elsa.Persistence.Core;
using Elsa.Primitives.Contracts;
using Elsa.Primitives.Enums;
using Elsa.Primitives.Versioning;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace Elsa.Activities.Design.Reconciliation.Services;

/// <summary>
/// Model X reconciliation policy (Unit C 2026-05-28; pending 2026-06-01 architecture
/// review). For each candidate version contributed by source modules:
///
/// 1. Find the parent definition by its surrogate Id or by the natural key
///    <c>(SourceKind, SourceId, ActivityTypeKey)</c>.
/// 2. If no parent exists, persist a fresh Definition + Version with immutable provenance.
///    The version carries an immutable <see cref="ActivityDefinitionVersion.ReconcilliationHash"/>
///    computed from its content.
/// 3. If the parent exists but the specific Version number does not, append the Version
///    with immutable provenance (including ProvisioningHash).
/// 4. If <c>(DefinitionId, Version)</c> is already persisted, compute the incoming hash
///    and compare to the persisted ProvisioningHash:
///    - Hashes differ → <see cref="ActivityVersionHashMismatchException"/> (the source is
///      broken — same logical identity, different content).
///    - Hashes match → skip or throw per the <see cref="DuplicateHandling"/> option.
///
/// No per-pass mutating state is carried by any entity in this domain. Source disappearance
/// is intentionally not tracked. Versions are never deleted.
/// </summary>
public sealed class ActivityVersionReconciler(
    ILogger<ActivityVersionReconciler> logger,
    IEventPublisher sender,
    IOptions<ActivityVersionReconcilerOptions> options,
    IQueries<ActivityDefinition> definitionQueries,
    IQueries<ActivityDefinitionVersion> versionQueries,
    IAddActivityDefinitionCommand addNewDefinitionCommand,
    IAddCommand<ActivityDefinitionVersion> addVersionCommand
)
    : IActivityVersionReconciler
{
    public async Task Reconcile(CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        // Handlers contribute by adding to the event's directly-accessible Versions collection;
        // the reconciler reads the accumulated set after dispatch.
        var @event = new OnActivityVersionsReconciling();
        await sender.Publish(@event, cancellationToken: cancellationToken);

        foreach (var version in @event.Versions)
        {
            await ReconcileVersion(version, cancellationToken);
        }
    }

    private async Task ReconcileVersion(IActivityDefinitionVersion incomingVersion, CancellationToken cancellationToken)
    {
        // The content hash is generated by the version factory; the reconciler only compares it.
        var incomingHash = incomingVersion.Hash;

        var definition = await FindDefinition(
            incomingVersion.Definition.Id,
            incomingVersion.Definition.ActivityTypeKey,
            cancellationToken
        );

        if (definition is null)
        {
            // Fresh definition + first version (the candidate's own DefinitionId is kept).
            await addNewDefinitionCommand.Execute(
                ActivityDefinition.From(incomingVersion.Definition),
                ActivityDefinitionVersion.From(incomingVersion),
                cancellationToken);
            return;
        }

        // Definition exists. Lookup the specific version by (DefinitionId, Version) — build-metadata-
        // insensitive (FR-013) by matching on the normalised sort key, so 1.0.0 and 1.0.0+build are
        // the same logical version.
        var incomingSortKey = SemVer.ToSortKey(incomingVersion.Version);
        var existingVersion = await versionQueries.Find(
            v => v.DefinitionId == definition.Id && v.SemVerSortKey == incomingSortKey,
            cancellationToken
        );

        if (existingVersion is null)
        {
            // Definition exists but this Version number doesn't. Append, rebinding the version to the
            // existing definition's id while keeping the candidate's content hash unchanged.
            await addVersionCommand.Add(ActivityDefinitionVersion.From(incomingVersion, definition.Id), cancellationToken);
            return;
        }

        // (DefinitionId, Version) is already persisted — Model X duplicate path.
        if (!string.Equals(existingVersion.Hash, incomingHash, StringComparison.Ordinal))
        {
            // Same identity, different content — the source is broken. Throw loudly.
            throw new ActivityVersionHashMismatchException(
                definitionId: definition.Id,
                activityTypeKey: definition.ActivityTypeKey,
                version: incomingVersion.Version,
                persistedHash: existingVersion.Hash,
                incomingHash: incomingHash
            );
        }

        // Hash matches → genuine duplicate.
        HandleHashMatchedDuplicate(definition, incomingVersion.Version);
    }

    private void HandleHashMatchedDuplicate(ActivityDefinition definition, string version)
    {
        switch (options.Value.DuplicateHandling)
        {
            case DuplicateHandling.Throw:
                throw new InvalidOperationException(
                    $"Activity definition '{definition.ActivityTypeKey}' (id = '{definition.Id}') already has version {version} persisted with matching content hash.");

            case DuplicateHandling.Skip:
                LogSkipDuplicate(definition.Id, definition.ActivityTypeKey, version);
                break;

            default:
                break;
        }
    }

    private void LogSkipDuplicate(string definitionId, string activityTypeKey, string version)
    {
        if (logger.IsEnabled(LogLevel.Information))
            logger.LogInformation(
                "Reconciliation: skipping hash-matched duplicate. Definition '{key}' (id = '{id}'), version {v}.",
                activityTypeKey, definitionId, version);
    }

    private async Task<ActivityDefinition?> FindDefinition(
        string definitionId,
        string activityTypeKey,
        CancellationToken cancellationToken)
    {
        var definition = await definitionQueries.Find(
            x => x.Id == definitionId || x.ActivityTypeKey == activityTypeKey,
            cancellationToken
        );

        if (definition is null)
            return null;

        // Sanity check: if the surrogate Id matched but the natural key disagrees (or vice
        // versa), that's a real identity collision. Throw — the source has produced a row
        // whose logical identity contradicts an existing row's.
        var idMatches = definition.Id == definitionId;
        var naturalKeyMatches = definition.ActivityTypeKey == activityTypeKey;

        if (!idMatches && !naturalKeyMatches)
        {
            throw new InvalidOperationException(
                $"Activity definition identity mismatch. Trying to reconcile definition (id = '{definitionId}', ActivityTypeKey = '{activityTypeKey}'); found existing definition (id = '{definition.Id}', ActivityTypeKey = '{definition.ActivityTypeKey}').");
        }

        return definition;
    }
}
