// <auto-generated />
using Elsa.Foundation.Identity.Persistence.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elsa.Foundation.Identity.Persistence.EntityFrameworkCore.Migrations.IdentityProviderConfiguration.Sqlite
{
    [DbContext(typeof(IdentityProviderConfigurationSqliteDbContext))]
    partial class IdentityProviderConfigurationSqliteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Elsa.Foundation.Identity.Persistence.EntityFrameworkCore.Entities.GlobalProviderConfigurationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PermissionPropagation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderLookupKey")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SupportsApplicationManagement")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsGroupSync")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsLocalRoleManagement")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsLocalUserManagement")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsRefresh")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsRevocation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsTokenIssuance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .HasMaxLength(1600)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantLookupKey")
                        .HasMaxLength(1600)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("identity_global_provider_configurations", (string)null);
                });

            modelBuilder.Entity("Elsa.Foundation.Identity.Persistence.EntityFrameworkCore.Entities.TenantProviderConfigurationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PermissionPropagation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderLookupKey")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SupportsApplicationManagement")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsGroupSync")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsLocalRoleManagement")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsLocalUserManagement")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsRefresh")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsRevocation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsTokenIssuance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantLookupKey")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("identity_provider_configurations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
