using Groundwork.Core.Indexing;
using Groundwork.Core.Manifests;
using Groundwork.Core.Queries;
using Groundwork.Core.Workloads;

namespace Elsa.Persistence.Groundwork.RuntimeEntities;

public static class RuntimeEntityManifestFactory
{
    public const string DefinitionDocumentKind = "runtimeEntityDefinition";

    public static string InstanceDocumentKind(RuntimeEntityDefinition definition) => $"runtimeEntityInstance.{definition.EntityType}";

    public static StorageManifest Create(RuntimeEntityDefinition definition) =>
        new(
            new StorageManifestIdentity($"elsa.runtime-entities.{definition.EntityType}"),
            new StorageManifestOwner("elsa.persistence.groundwork"),
            new StorageManifestVersion("1.0.0"),
            [CreateDefinitionUnit(), CreateInstanceUnit(definition)],
            new HashSet<string> { "schema-history", "optimistic-concurrency" },
            ["Runtime-defined entity manifest generated by the Elsa Groundwork bridge."]);

    private static StorageUnit CreateDefinitionUnit() =>
        new(
            new StorageUnitIdentity(DefinitionDocumentKind),
            "Runtime entity definition",
            new WorkloadClassification(WorkloadFamily.RuntimeDefinedBusinessData, WorkloadCandidateCategory.GroundworkDefault),
            LifecyclePolicy.Mutable,
            IdentityPolicy.StringId(),
            TenancyPolicy.None,
            ConcurrencyPolicy.Optimistic(),
            SerializationPolicy.Json(),
            [
                new IndexDeclaration(
                    "by-entity-type",
                    [new IndexField("entityType")],
                    IndexValueKind.Keyword,
                    true,
                    true,
                    MissingValueBehavior.Excluded,
                    new HashSet<PortableQueryOperation> { PortableQueryOperation.Equal })
            ],
            [
                new PortableQueryDeclaration(
                    "find-by-entity-type",
                    "by-entity-type",
                    new HashSet<PortableQueryOperation> { PortableQueryOperation.Equal },
                    QuerySortSupport.None,
                    QueryPagingSupport.None)
            ],
            PhysicalizationPolicy.Portable);

    private static StorageUnit CreateInstanceUnit(RuntimeEntityDefinition definition)
    {
        var indexes = definition.Indexes
            .Select(index => new IndexDeclaration(
                index.Name,
                [new IndexField(index.Path)],
                index.ValueKind,
                index.IsUnique,
                index.IsSortable,
                MissingValueBehavior.Excluded,
                new HashSet<PortableQueryOperation> { PortableQueryOperation.Equal }))
            .ToList();
        var queries = definition.Indexes
            .Select(index => new PortableQueryDeclaration(
                $"query-{index.Name}",
                index.Name,
                new HashSet<PortableQueryOperation> { PortableQueryOperation.Equal },
                index.IsSortable ? QuerySortSupport.Both : QuerySortSupport.None,
                QueryPagingSupport.Offset))
            .ToList();

        return new StorageUnit(
            new StorageUnitIdentity(InstanceDocumentKind(definition)),
            definition.DisplayName,
            new WorkloadClassification(WorkloadFamily.RuntimeDefinedBusinessData, WorkloadCandidateCategory.GroundworkDefault),
            LifecyclePolicy.Mutable,
            IdentityPolicy.StringId(),
            TenancyPolicy.None,
            ConcurrencyPolicy.Optimistic(),
            SerializationPolicy.Json(),
            indexes,
            queries,
            PhysicalizationPolicy.Portable);
    }
}
