<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Elsa.Workflows.Runtime.Core.csproj" />
    <ProjectReference Include="..\..\..\..\Serialization\Core\Elsa.Serialization.Core.csproj" />
    <ProjectReference Include="..\..\..\..\Primitives\Primitives\Elsa.Primitives.csproj" />
  </ItemGroup>

</Project>
