<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Activities\Runtime\Core\Elsa.Activities.Runtime.Core.csproj" />
    <ProjectReference Include="..\..\..\Expressions\Core\Elsa.Expressions.Core.csproj" />
    <ProjectReference Include="..\..\..\Serialization\Core\Elsa.Serialization.Core.csproj" />
  </ItemGroup>

</Project>
