<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="CShells.Abstractions" />
    <PackageReference Include="Elsa.Platform.PackageManifest.Generator" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../Api/FastEndpoints/Elsa.Api.FastEndpoints.csproj" />
    <ProjectReference Include="../../../Foundation/Identity/Abstractions/Elsa.Foundation.Identity.Abstractions.csproj" />
    <ProjectReference Include="../Core/Elsa.Studio.Preferences.Core.csproj" />
  </ItemGroup>
</Project>
