<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Persistence\Core\Elsa.Activities.Design.Persistence.Core.csproj" />
    <ProjectReference Include="..\..\..\Events\Core\Elsa.Events.Core.csproj" />
    <ProjectReference Include="..\..\..\Features\Abstractions\Elsa.Features.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\Api\FastEndpoints\Elsa.Api.FastEndpoints.csproj" />
    <ProjectReference Include="..\..\..\Mediator\Core\Elsa.Mediator.Core.csproj" />
  </ItemGroup>

</Project>
