<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Elsa.Platform.PackageManifest.Generator" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Core\**\*.cs" />
    <Compile Remove="Models\**\*.cs" />
    <Compile Remove="Requests\**\*.cs" />
    <Compile Remove="Commands\**\*.cs" />
    <Compile Include="Models\ActivityProblemDetails.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Persistence\Core\Elsa.Activities.Design.Persistence.Core.csproj" />
    <ProjectReference Include="..\..\..\Events\Core\Elsa.Events.Core.csproj" />
    <ProjectReference Include="Core\Elsa.Activities.Design.Api.Core.csproj" />
    <ProjectReference Include="..\..\..\Foundation\Identity\Abstractions\Elsa.Foundation.Identity.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\Api\Capabilities\Elsa.Api.Capabilities.csproj" />
    <ProjectReference Include="..\..\..\Expressions\Core\Elsa.Expressions.Core.csproj" />
    <ProjectReference Include="..\..\..\Mediator\Core\Elsa.Mediator.Core.csproj" />
    <ProjectReference Include="..\..\..\Serialization\Core\Elsa.Serialization.Core.csproj" />
  </ItemGroup>

</Project>
