// <auto-generated />
using Elsa3.Activities.Design.Import.Persistence.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elsa3.Activities.Design.Import.Persistence.EntityFrameworkCore.Migrations.Elsa3Import.SqlServer
{
    [DbContext(typeof(Elsa3ImportSqlServerDbContext))]
    [Migration("20260915232855_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            // SqlServerModelBuilderExtensions.UseIdentityColumns omitted: the module stays provider-free.

            modelBuilder.Entity("Elsa3.Activities.Design.Import.Persistence.EntityFrameworkCore.Entities.Elsa3ImportCollectionRecord", b =>
                {
                    b.Property<string>("TenantKey")
                        .HasMaxLength(66)
                        .HasColumnType("nvarchar(66)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("UserIdHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("HandleHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<long>("ContentLength")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedAtUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<long>("ExpiresAtUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("TenantId")
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("TenantKey", "UserIdHash", "HandleHash");

                    b.ToTable("elsa3_reusable_import_collections", (string)null);
                });

            modelBuilder.Entity("Elsa3.Activities.Design.Import.Persistence.EntityFrameworkCore.Entities.Elsa3ImportDefinitionBindingRecord", b =>
                {
                    b.Property<string>("TenantKey")
                        .HasMaxLength(66)
                        .HasColumnType("nvarchar(66)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("BindingIdHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("BindingId")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<int>("CreatedAtOffsetMinutes")
                        .HasColumnType("int");

                    b.Property<long>("CreatedAtUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("SourceDefinitionId")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("TargetDefinitionId")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("TargetDefinitionIdHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("TargetDocumentKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("TenantId")
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("TenantKey", "BindingIdHash");

                    b.ToTable("elsa3_reusable_import_definition_bindings", (string)null);
                });

            modelBuilder.Entity("Elsa3.Activities.Design.Import.Persistence.EntityFrameworkCore.Entities.Elsa3ImportReceiptRecord", b =>
                {
                    b.Property<string>("TenantKey")
                        .HasMaxLength(66)
                        .HasColumnType("nvarchar(66)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("UserIdHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ReceiptIdHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("CommitAttemptId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<long>("CompletedAtUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ReceiptId")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("TenantId")
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("TenantKey", "UserIdHash", "ReceiptIdHash");

                    b.ToTable("elsa3_reusable_import_receipts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
