<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\elsa\Admin\Api\Elsa.Admin.Api.csproj" />
    <ProjectReference Include="..\..\elsa\Admin\Core\Elsa.Admin.Core.csproj" />
    <ProjectReference Include="..\..\elsa\Admin\Web\Elsa.Admin.Web.csproj" />
    <ProjectReference Include="..\..\elsa\Admin\Samples\Dashboard\Elsa.Admin.Samples.Dashboard.csproj" />
    <ProjectReference Include="..\..\elsa\Admin\Samples\WeatherForecast\Elsa.Admin.Samples.WeatherForecast.csproj" />
    <ProjectReference Include="..\..\elsa\Events\Elsa.Events.csproj" />
  </ItemGroup>

</Project>
