// <auto-generated />
using Elsa3.Activities.Design.Import.Persistence.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elsa3.Activities.Design.Import.Persistence.EntityFrameworkCore.Migrations.Elsa3Import.Sqlite
{
    [DbContext(typeof(Elsa3ImportSqliteDbContext))]
    partial class Elsa3ImportSqliteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Elsa.Persistence.EntityFramework.SchemaFinalization.EfDatabaseIdentityRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DatabaseIdentity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SchemaVersion");

                    b.ToTable("__ElsaDatabaseIdentity_Elsa3ReusableActivityImport", (string)null);
                });

            modelBuilder.Entity("Elsa.Persistence.EntityFramework.SchemaFinalization.EfSchemaFinalizationRecordRow", b =>
                {
                    b.Property<string>("Family")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabaseIdentity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalizedVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("FinishHistoryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FinishJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("HistoryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HoldsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IntentJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Family");

                    b.HasIndex("SchemaVersion");

                    b.ToTable("__ElsaSchemaFinalization_Elsa3ReusableActivityImport", (string)null);
                });

            modelBuilder.Entity("Elsa3.Activities.Design.Import.Persistence.EntityFrameworkCore.Entities.Elsa3ImportCollectionRecord", b =>
                {
                    b.Property<string>("TenantKey")
                        .HasMaxLength(66)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserIdHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("HandleHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ContentLength")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.HasKey("TenantKey", "UserIdHash", "HandleHash");

                    b.HasIndex("SchemaVersion");

                    b.ToTable("elsa3_reusable_import_collections", (string)null);
                });

            modelBuilder.Entity("Elsa3.Activities.Design.Import.Persistence.EntityFrameworkCore.Entities.Elsa3ImportDefinitionBindingRecord", b =>
                {
                    b.Property<string>("TenantKey")
                        .HasMaxLength(66)
                        .HasColumnType("TEXT");

                    b.Property<string>("BindingIdHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BindingId")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedAtOffsetMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceDefinitionId")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetDefinitionId")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetDefinitionIdHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetDocumentKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.HasKey("TenantKey", "BindingIdHash");

                    b.HasIndex("SchemaVersion");

                    b.ToTable("elsa3_reusable_import_definition_bindings", (string)null);
                });

            modelBuilder.Entity("Elsa3.Activities.Design.Import.Persistence.EntityFrameworkCore.Entities.Elsa3ImportReceiptRecord", b =>
                {
                    b.Property<string>("TenantKey")
                        .HasMaxLength(66)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserIdHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptIdHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitAttemptId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("CompletedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptId")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.HasKey("TenantKey", "UserIdHash", "ReceiptIdHash");

                    b.HasIndex("SchemaVersion");

                    b.ToTable("elsa3_reusable_import_receipts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
