using System.Text;
using System.Text.RegularExpressions;
using System.Xml;
using System.Xml.Linq;

namespace Elsa.Versioning.Calculator;

/// <summary>
/// The MSBuild file that carries a computation into <c>dotnet build</c> and <c>dotnet pack</c> (#2080):
/// <c>PackageVersioning.props</c> at the repository root reads what it sets, and each run passes it in with
/// <c>-p:CustomBeforeDirectoryBuildProps=&lt;its full path&gt;</c>.
/// </summary>
/// <remarks>
/// <para>
/// It sets <c>ElsaVersionComputationCommit</c> to the commit computed, and for each packable project, selected by
/// project name, <c>ElsaComputedPackageVersion</c> and <c>ElsaInputFingerprint</c>. A package being published carries
/// its computed <c>major.minor.patch</c> with the branch's prerelease label (<see cref="PrereleaseLabel"/>); a package
/// that is not keeps the exact version its record names, label and all, because that is the version on the feed that
/// the ranges of packages referencing it must start at (SC-002).
/// </para>
/// <para>
/// It is a pure function of the computation and the branch, so the same commit, record revision and branch give the
/// same bytes. It lives outside the repository: nothing commits it, so the calculator never reads it as an input.
/// </para>
/// </remarks>
public static partial class PackProperties
{
    public const string CommitProperty = "ElsaVersionComputationCommit";
    public const string VersionProperty = "ElsaComputedPackageVersion";
    public const string FingerprintProperty = "ElsaInputFingerprint";

    private static readonly XmlWriterSettings WriterSettings = new()
    {
        OmitXmlDeclaration = true,
        Indent = true,
        IndentChars = "  ",
        NewLineChars = "\n"
    };

    /// <summary>Renders the file for a computation packed from <paramref name="branch"/>.</summary>
    /// <exception cref="InvalidOperationException">
    /// The commit's <c>VersionLines.props</c> does not assign <c>ElsaPrereleaseLabel</c>, the branch makes no label, or
    /// two packable projects share a name.
    /// </exception>
    public static string Render(VersionComputation computation, string branch)
    {
        var label = LabelFor(computation, branch);

        var projects = computation.Packages.Select(package => (Name: Path.GetFileNameWithoutExtension(package.Path), Package: package)).ToArray();
        var invalid = projects.Where(project => !ProjectName().IsMatch(project.Name)).Select(project => project.Package.Path).ToArray();
        if (invalid.Length > 0)
            throw new InvalidOperationException($"These projects' names cannot be matched in an MSBuild condition: {string.Join(", ", invalid)}.");

        var shared = projects.GroupBy(project => project.Name, StringComparer.OrdinalIgnoreCase).Where(group => group.Count() > 1).Select(group => group.Key).ToArray();
        if (shared.Length > 0)
            throw new InvalidOperationException(
                $"More than one packable project is named {string.Join(", ", shared)}; MSBuild selects each package's version by project name.");

        var document = new XElement("Project",
            new XComment(
                $"\n    Generated by tools/versioning/Elsa.Versioning.Calculator for commit {computation.Commit}, branch {branch}. Pass it to\n" +
                "    both dotnet build and dotnet pack as -p:CustomBeforeDirectoryBuildProps=<this file's full path>, and never commit it.\n  "),
            new XElement("PropertyGroup", new XElement(CommitProperty, computation.Commit)),
            projects.OrderBy(project => project.Name, StringComparer.Ordinal).Select(project => new XElement("PropertyGroup",
                new XAttribute("Condition", $"'$(MSBuildProjectName)' == '{project.Name}'"),
                new XElement(VersionProperty, VersionOf(project.Package, label)),
                new XElement(FingerprintProperty, project.Package.Fingerprint))));

        var text = new StringBuilder();
        using (var writer = XmlWriter.Create(text, WriterSettings))
            document.WriteTo(writer);

        return text.Append('\n').ToString();
    }

    /// <summary>The prerelease label packages of the computation packed from <paramref name="branch"/> carry, or null for none.</summary>
    /// <exception cref="InvalidOperationException">The commit's <c>VersionLines.props</c> does not assign <c>ElsaPrereleaseLabel</c>, or the branch makes no label.</exception>
    public static string? LabelFor(VersionComputation computation, string branch) =>
        PrereleaseLabel.For(branch, computation.Lines.PrereleaseLabel ?? throw new InvalidOperationException(
            $"{VersionLineSettings.RelativePath} at {computation.Commit} does not assign <{PrereleaseLabel.PropertyName}>, so nothing says which " +
            "label its packages carry (spec 150 FR-008). Assign it: preview while the lines are unreleased, empty once they are."));

    /// <summary>The version a package is packed at: its computed one with the label when it is published, its recorded one when not.</summary>
    public static string VersionOf(ComputedPackage package, string? label) =>
        package.Affected
            ? (package.Version with { Label = label }).ToString()
            : package.LastPublished?.Version.ToString() ?? throw new InvalidOperationException(
                $"{package.PackageId} is not affected but has no last-published record; the calculator marks every package without one affected.");

    [GeneratedRegex("^[A-Za-z0-9._-]+$", RegexOptions.CultureInvariant)]
    private static partial Regex ProjectName();
}
