<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Groundwork.Core" />
    <PackageReference Include="Groundwork.DiagnosticRecords" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Events\Core\Elsa.Events.Core.csproj" />
  </ItemGroup>

</Project>
