// <auto-generated />
using System;
using Elsa.Secrets.Persistence.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elsa.Secrets.Persistence.EntityFrameworkCore.Migrations.PostgreSql
{
    [DbContext(typeof(SecretsPostgreSqlDbContext))]
    partial class SecretsPostgreSqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            // NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns omitted: the module stays provider-free.

            modelBuilder.Entity("Elsa.Secrets.Persistence.EntityFrameworkCore.Entities.SecretRecord", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("DisplayNameSearchKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasNonExpiringActiveVersion")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("MaxActiveVersionExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameSearchKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ScopeLookupKey")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StoreNameLookupKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeNameLookupKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TenantId", "NormalizedName");

                    b.HasIndex("TenantId", "Status", "NormalizedName")
                        .HasDatabaseName("IX_elsa_secrets_tenantId_status_normalizedName");

                    b.ToTable("elsa_secrets", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
