<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CShells.Abstractions" />
    <PackageReference Include="Elsa.Platform.PackageManifest.Generator" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Elsa.Modularity.Core.csproj" />
    <ProjectReference Include="..\Nuplane\Elsa.Modularity.Nuplane.csproj" />
    <ProjectReference Include="..\..\Api\FastEndpoints\Elsa.Api.FastEndpoints.csproj" />
  </ItemGroup>

</Project>
