<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../../src/Elsa/Studio/Preferences/Core/Elsa.Studio.Preferences.Core.csproj" />
    <ProjectReference Include="../../../../../src/Elsa/Studio/Preferences/Api/Elsa.Studio.Preferences.Api.csproj" />
  </ItemGroup>
</Project>
