<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="CShells.Abstractions" />
    <PackageReference Include="Elsa.Platform.PackageManifest.Generator" PrivateAssets="all" />
  </ItemGroup>

  <Target Name="BuildAdminClient" BeforeTargets="ComputeFilesToPublish" Condition="'$(Configuration)' == 'Release' And Exists('Client/package.json')">
    <Exec WorkingDirectory="Client" Command="npm ci" />
    <Exec WorkingDirectory="Client" Command="npm run build" />
  </Target>

</Project>
