<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="CShells.Abstractions" />
    <PackageReference Include="CShells.AspNetCore.Abstractions" />
    <PackageReference Include="Elsa.Platform.PackageManifest.Generator" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../Api/AspNetCore/Elsa.Api.AspNetCore.csproj" />
    <ProjectReference Include="../../Foundation/Identity/Abstractions/Elsa.Foundation.Identity.Abstractions.csproj" />
    <ProjectReference Include="../../Events/Core/Elsa.Events.Core.csproj" />
    <ProjectReference Include="../Design/Persistence/Core/Elsa.Workflows.Design.Persistence.Core.csproj" />
    <ProjectReference Include="../Design/Validations/Core/Elsa.Workflows.Design.Validations.Core.csproj" />
    <ProjectReference Include="../Runtime/Core/Elsa.Workflows.Runtime.Core.csproj" />
    <ProjectReference Include="../Runtime/Elsa.Workflows.Runtime.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Persistence/**/*" />
    <EmbeddedResource Remove="Persistence/**/*" />
    <None Remove="Persistence/**/*" />
    <Compile Remove="Providers/**/*" />
    <EmbeddedResource Remove="Providers/**/*" />
    <None Remove="Providers/**/*" />
  </ItemGroup>
</Project>
