<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>0.0.1-local</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CShells.Abstractions" />
    <PackageReference Include="Groundwork.Kernel" />
    <PackageReference Include="Groundwork.Query.Model" />
    <PackageReference Include="Groundwork.Store" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Elsa.Diagnostics.OpenTelemetry.Core.csproj" />
    <ProjectReference Include="..\..\..\Persistence\Elsa.Diagnostics.Persistence.csproj" />
  </ItemGroup>

</Project>
