<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <ImportDirectoryBuildProps>false</ImportDirectoryBuildProps>
    <ImportDirectoryBuildTargets>false</ImportDirectoryBuildTargets>
    <GroundworkVersion>0.4.0-preview.8</GroundworkVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Groundwork.Kernel" Version="$(GroundworkVersion)" />
    <PackageReference Include="Groundwork.MongoDb" Version="$(GroundworkVersion)" />
    <PackageReference Include="Groundwork.PostgreSql" Version="$(GroundworkVersion)" />
    <PackageReference Include="Groundwork.Sqlite" Version="$(GroundworkVersion)" />
    <PackageReference Include="Groundwork.SqlServer" Version="$(GroundworkVersion)" />
    <PackageReference Include="Groundwork.Store" Version="$(GroundworkVersion)" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" PrivateAssets="all" />
    <PackageReference Include="Xunit.SkippableFact" Version="1.5.23" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../../../src/Elsa/Persistence/Groundwork/V2/Elsa.Persistence.Groundwork.V2.csproj" />
    <ProjectReference Include="..\..\Testing\Elsa.Persistence.Groundwork.Testing.csproj" />
  </ItemGroup>
</Project>
