<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Elsa.Platform.PackageManifest.Generator" PrivateAssets="all" />
    <ProjectReference Include="..\Elsa.Diagnostics.OpenTelemetry.Persistence.EFCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\Persistence\EFCore\Sqlite\Elsa.Persistence.EFCore.Sqlite.csproj" />
  </ItemGroup>

</Project>
