<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <Version>0.0.4-jint4</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jint" Version="4.9.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.8" />
	  <PackageReference Include="CShells.Abstractions" Version="0.0.24" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Elsa.Expressions.JavaScript.Core.csproj" />
    <ProjectReference Include="..\..\..\Events\Core\Elsa.Events.Core.csproj" />
    <ProjectReference Include="..\..\..\Serialization\Core\Elsa.Serialization.Core.csproj" />
    <ProjectReference Include="..\..\..\Workflows\Runtime\Core\Elsa.Workflows.Runtime.Core.csproj" />
  </ItemGroup>

</Project>
