// <auto-generated />
using Elsa.Activities.Design.Persistence.EFCore.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elsa.Activities.Design.Persistence.EFCore.Sqlite.Migrations
{
    [DbContext(typeof(ActivitiesDesignDbContext))]
    [Migration("20260528142756_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Elsa")
                .HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Elsa.Activities.Design.Persistence.Core.Entities.ActivityDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityTypeKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvisionedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvisionedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_ActivityDefinition_Category");

                    b.HasIndex("TenantId");

                    b.HasIndex("SourceKind", "SourceId")
                        .HasDatabaseName("IX_ActivityDefinition_SourceKind_SourceId");

                    b.HasIndex("SourceKind", "SourceId", "ActivityTypeKey")
                        .IsUnique()
                        .HasDatabaseName("UX_ActivityDefinition_SourceKind_SourceId_ActivityTypeKey");

                    b.ToTable("ActivityDefinitions", "Elsa");
                });

            modelBuilder.Entity("Elsa.Activities.Design.Persistence.Core.Entities.ActivityDefinitionVersion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityTypeKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExecutionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImplementationDescriptorPayload")
                        .HasMaxLength(-1)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImplementationKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InputsSource")
                        .HasMaxLength(-1)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputsSource")
                        .HasMaxLength(-1)
                        .HasColumnType("TEXT");

                    b.Property<string>("PortsSource")
                        .HasMaxLength(-1)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvisioningHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("DefinitionId", "Version")
                        .IsUnique()
                        .HasDatabaseName("UX_ActivityDefinitionVersion_DefinitionId_Version");

                    b.ToTable("ActivityDefinitionVersions", "Elsa");
                });

            modelBuilder.Entity("Elsa.Activities.Design.Persistence.Core.Entities.ActivityDefinitionVersion", b =>
                {
                    b.HasOne("Elsa.Activities.Design.Persistence.Core.Entities.ActivityDefinition", "Definition")
                        .WithMany()
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Definition");
                });
#pragma warning restore 612, 618
        }
    }
}
