<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="CShells.Abstractions" />
		<PackageReference Include="Elsa.Platform.PackageManifest.Generator" PrivateAssets="all" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
		<PackageReference Include="Microsoft.Extensions.Options" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Abstractions\Elsa.Foundation.Identity.Abstractions.csproj" />
	</ItemGroup>

</Project>
