<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Elsa.Expressions.JavaScript.Rendering.Core\Elsa.Expressions.JavaScript.Rendering.Core.csproj" />
    <ProjectReference Include="..\Elsa.Primitives\Elsa.Primitives.csproj" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="CShells.Abstractions" Version="0.0.24" />
	</ItemGroup>

</Project>
