<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Version>0.0.1-local</Version>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CShells.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="Elsa.Platform.PackageManifest.Generator" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Core\Elsa.Caching.Core.csproj" />
	</ItemGroup>

</Project>
