<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CShells.Abstractions" Version="0.0.24" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Elsa.Workflows.Design.Validations.Core\Elsa.Workflows.Design.Validations.Core.csproj" />
    <ProjectReference Include="..\Elsa.Expressions.Core\Elsa.Expressions.Core.csproj" />
    <ProjectReference Include="..\Elsa.Mediator.Core\Elsa.Mediator.Core.csproj" />
  </ItemGroup>

</Project>
