<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Version>0.0.2-local</Version>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CShells.FastEndpoints.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Mediator\Core\Elsa.Mediator.Core.csproj" />
		<ProjectReference Include="..\..\Primitives\Primitives\Elsa.Primitives.csproj" />
	</ItemGroup>

</Project>
