using Elsa.Workflows.Design.CodeGeneration;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace Elsa.Workflows.Design.CodeGeneration.Tests;

public sealed class ActivityCallGeneratorTests
{
    [Fact]
    public void Generator_emits_deterministic_named_facade_and_typed_call_handle()
    {
        const string source = $$"""
            using Elsa.Activities.Runtime.Core.Attributes;
            using Elsa.Activities.Runtime.Core.Contracts;

            {{RuntimeStubs}}
            {{AuthoringStubs}}

            namespace GeneratorConsumer
            {
                public sealed record ChargeCardResult(
                    [property: Output(Key = "approved")] bool Approved,
                    [property: Output(Key = "receipt-id")] string ReceiptId);

                [Version("2.0.0")]
                [ActivityOutcome("completed")]
                [ActivityOutcome("declined")]
                public sealed class ChargeCard : IActivity, IActivityResult<ChargeCardResult>
                {
                    [ActivityInput(Key = "customer-id", Order = 0)]
                    [Required]
                    public string CustomerId { get; set; } = "";

                    [ActivityInput(Key = "amount", Order = 1)]
                    [Required]
                    public decimal Amount { get; set; }
                }
            }
            """;

        var first = RunGenerator(source);
        var second = RunGenerator(source);
        var firstSource = GetFacadeSource(first);
        var secondSource = GetFacadeSource(second);

        Assert.Equal(firstSource, secondSource);
        Assert.Equal(
            """
            // <auto-generated/>
            #nullable enable

            namespace Elsa.Workflows.Design.CodeGeneration.Generated;

            public static partial class ActivityCallExtensions
            {
                public static ChargeCardCall ChargeCard(
                    this global::Elsa.Workflows.Design.Core.Authoring.ISequenceBuilder sequence,
                    global::Elsa.Workflows.Design.Core.Authoring.ActivityArgument<string> customerId,
                    global::Elsa.Workflows.Design.Core.Authoring.ActivityArgument<decimal> amount,
                    string? nodeId = null)
                {
                    if (sequence is null)
                        throw new global::System.ArgumentNullException(nameof(sequence));

                    var call = sequence.Add<global::GeneratorConsumer.ChargeCard, global::GeneratorConsumer.ChargeCardResult>(
                        "actver_sYzJcF1AJpo1k9MGPw5pohSuNQsg6bLoZ2c_QnzmthU",
                        inputs =>
                        {
                            inputs.Set("customer-id", customerId);
                            inputs.Set("amount", amount);
                        },
                        nodeId);
                    return new ChargeCardCall(call);
                }
            }

            public sealed class ChargeCardCall
            {
                private readonly global::Elsa.Workflows.Design.Core.Authoring.ActivityCall<global::GeneratorConsumer.ChargeCardResult> _call;

                internal ChargeCardCall(global::Elsa.Workflows.Design.Core.Authoring.ActivityCall<global::GeneratorConsumer.ChargeCardResult> call)
                {
                    _call = call;
                    Outputs = new ChargeCardOutputSources(call);
                    Outcomes = new ChargeCardOutcomeSources(call);
                }

                public global::Elsa.Workflows.Design.Core.Authoring.ActivityNodeHandle Node => _call.Node;
                public global::Elsa.Workflows.Design.Core.Authoring.ActivityResultSource<global::GeneratorConsumer.ChargeCardResult> Result => _call.Result;
                public ChargeCardOutputSources Outputs { get; }
                public ChargeCardOutcomeSources Outcomes { get; }
            }

            public sealed class ChargeCardOutputSources
            {
                private readonly global::Elsa.Workflows.Design.Core.Authoring.ActivityCall<global::GeneratorConsumer.ChargeCardResult> _call;

                internal ChargeCardOutputSources(global::Elsa.Workflows.Design.Core.Authoring.ActivityCall<global::GeneratorConsumer.ChargeCardResult> call) => _call = call;

                public global::Elsa.Workflows.Design.Core.Authoring.ActivityResultSource<bool> Approved => _call.Output<bool>("approved");

                public global::Elsa.Workflows.Design.Core.Authoring.ActivityResultSource<string> ReceiptId => _call.Output<string>("receipt-id");
            }

            public sealed class ChargeCardOutcomeSources
            {
                private readonly global::Elsa.Workflows.Design.Core.Authoring.ActivityCall<global::GeneratorConsumer.ChargeCardResult> _call;

                internal ChargeCardOutcomeSources(global::Elsa.Workflows.Design.Core.Authoring.ActivityCall<global::GeneratorConsumer.ChargeCardResult> call) => _call = call;

                public global::Elsa.Workflows.Design.Core.Authoring.ActivityOutcomeSource Completed => _call.Outcome("completed");

                public global::Elsa.Workflows.Design.Core.Authoring.ActivityOutcomeSource Declined => _call.Outcome("declined");
            }
            """.ReplaceLineEndings("\n") + "\n",
            firstSource);
        Assert.DoesNotContain(first.OutputCompilation.GetDiagnostics(), diagnostic => diagnostic.Severity == DiagnosticSeverity.Error);
    }

    [Fact]
    public void Generator_reports_duplicate_method_names_with_stable_diagnostic()
    {
        const string source = $$"""
            using Elsa.Activities.Runtime.Core.Attributes;
            using Elsa.Activities.Runtime.Core.Contracts;

            {{RuntimeStubs}}
            namespace GeneratorConsumer
            {
                [Version("1.0.0")]
                public sealed class Send : IActivity, IActivityResult<string>;

                namespace Other
                {
                    [Version("1.0.0")]
                    public sealed class Send : IActivity, IActivityResult<string>;
                }
            }
            """;

        var result = RunGenerator(source);
        var diagnostic = GetSingleGeneratorDiagnostic(result);

        Assert.Equal(ActivityCallGenerator.DuplicateFacadeDiagnosticId, diagnostic.Id);
        Assert.Equal(
            "Activity-call method 'Send' is declared by both 'GeneratorConsumer.Other.Send' and 'GeneratorConsumer.Send'. Method names must be unique.",
            diagnostic.GetMessage());
        Assert.DoesNotContain(result.RunResult.Results.SelectMany(x => x.GeneratedSources), source => source.HintName == ActivityCallGenerator.GeneratedHintName);
    }

    [Fact]
    public void Generator_reports_unsupported_generic_activity_shape_with_stable_diagnostic()
    {
        const string source = $$"""
            using Elsa.Activities.Runtime.Core.Attributes;
            using Elsa.Activities.Runtime.Core.Contracts;

            {{RuntimeStubs}}
            namespace GeneratorConsumer;

            [Version("1.0.0")]
            public sealed class Map<T> : IActivity, IActivityResult<string>;
            """;

        var result = RunGenerator(source);
        var diagnostic = GetSingleGeneratorDiagnostic(result);

        Assert.Equal(ActivityCallGenerator.UnsupportedShapeDiagnosticId, diagnostic.Id);
        Assert.Equal(
            "Activity 'GeneratorConsumer.Map<T>' has unsupported activity-call metadata: activity types must be top-level and non-generic",
            diagnostic.GetMessage());
    }

    [Fact]
    public void Generator_discovers_activity_metadata_from_referenced_assemblies()
    {
        const string activityPackage = """
            namespace Elsa.Activities.Runtime.Core.Contracts
            {
                public interface IActivity;
                public interface IActivityResult<TResult>;
            }

            namespace Elsa.Activities.Runtime.Core.Attributes
            {
                [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
                public sealed class ActivityInputAttribute : System.Attribute
                {
                    public string? Key { get; init; }
                    public float Order { get; init; }
                }

                [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
                public sealed class OutputAttribute : System.Attribute
                {
                    public string? Key { get; init; }
                }

                [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
                public sealed class RequiredAttribute : System.Attribute;
                [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = true, Inherited = true)]
                public sealed class ActivityOutcomeAttribute(string key) : System.Attribute;
                [System.AttributeUsage(System.AttributeTargets.Class)]
                public sealed class VersionAttribute(string version) : System.Attribute;
            }

            namespace ReferencedActivities
            {
                using Elsa.Activities.Runtime.Core.Attributes;
                using Elsa.Activities.Runtime.Core.Contracts;

                public sealed record SendEmailResult([property: Output(Key = "message-id")] string MessageId);

                [Version("1.0.0")]
                [ActivityOutcome("sent")]
                public sealed class SendEmail : IActivity, IActivityResult<SendEmailResult>
                {
                    [ActivityInput(Key = "to")]
                    [Required]
                    public string To { get; set; } = "";
                }
            }
            """;
        var activityReference = CompileReference("ReferencedActivityPackage", activityPackage);
        var result = RunGenerator(AuthoringStubs, [activityReference]);
        var generated = GetFacadeSource(result);

        Assert.Contains("public static SendEmailCall SendEmail(", generated, StringComparison.Ordinal);
        Assert.Contains("sequence.Add<global::ReferencedActivities.SendEmail, global::ReferencedActivities.SendEmailResult>", generated, StringComparison.Ordinal);
        Assert.DoesNotContain(result.OutputCompilation.GetDiagnostics(), diagnostic => diagnostic.Severity == DiagnosticSeverity.Error);
    }

    private static GeneratorResult RunGenerator(string source, IReadOnlyCollection<MetadataReference>? additionalReferences = null)
    {
        var compilation = CSharpCompilation.Create(
            assemblyName: "GeneratorConsumer",
            syntaxTrees: [CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Preview))],
            references: GetPlatformReferences().Concat(additionalReferences ?? []),
            options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary, nullableContextOptions: NullableContextOptions.Enable));

        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            generators: [new ActivityCallGenerator().AsSourceGenerator()],
            parseOptions: new CSharpParseOptions(LanguageVersion.Preview));
        driver = driver.RunGeneratorsAndUpdateCompilation(compilation, out var updatedCompilation, out var diagnostics);

        Assert.DoesNotContain(diagnostics, diagnostic => diagnostic.Id == "CS8785");
        return new GeneratorResult(driver.GetRunResult(), updatedCompilation);
    }

    private static MetadataReference CompileReference(string assemblyName, string source)
    {
        var compilation = CSharpCompilation.Create(
            assemblyName,
            [CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Preview))],
            GetPlatformReferences(),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary, nullableContextOptions: NullableContextOptions.Enable));
        using var stream = new MemoryStream();
        var emit = compilation.Emit(stream);
        Assert.True(emit.Success, string.Join(Environment.NewLine, emit.Diagnostics));
        return MetadataReference.CreateFromImage(stream.ToArray());
    }

    private static string GetFacadeSource(GeneratorResult result) => result.RunResult.Results
        .SelectMany(x => x.GeneratedSources)
        .Single(x => x.HintName == ActivityCallGenerator.GeneratedHintName)
        .SourceText
        .ToString()
        .ReplaceLineEndings("\n");

    private static Diagnostic GetSingleGeneratorDiagnostic(GeneratorResult result)
    {
        var exception = result.RunResult.Diagnostics.FirstOrDefault(diagnostic => diagnostic.Id == "CS8785");
        Assert.True(exception is null, exception?.ToString());
        return Assert.Single(result.RunResult.Diagnostics);
    }

    private static IReadOnlyCollection<MetadataReference> GetPlatformReferences()
    {
        var trustedPlatformAssemblies = (string?)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES") ?? string.Empty;
        return trustedPlatformAssemblies
            .Split(Path.PathSeparator, StringSplitOptions.RemoveEmptyEntries)
            .Select(path => MetadataReference.CreateFromFile(path))
            .ToArray();
    }

    private sealed record GeneratorResult(GeneratorDriverRunResult RunResult, Compilation OutputCompilation);

    private const string RuntimeStubs = """
        namespace Elsa.Activities.Runtime.Core.Contracts
        {
            public interface IActivity;
            public interface IActivityResult<TResult>;
        }

        namespace Elsa.Activities.Runtime.Core.Attributes
        {
            [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
            public sealed class ActivityInputAttribute : System.Attribute
            {
                public string? Key { get; init; }
                public float Order { get; init; }
            }

            [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
            public sealed class OutputAttribute : System.Attribute
            {
                public string? Key { get; init; }
            }

            [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
            public sealed class RequiredAttribute : System.Attribute;

            [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = true, Inherited = true)]
            public sealed class ActivityOutcomeAttribute(string key) : System.Attribute;

            [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
            public sealed class VersionAttribute(string version) : System.Attribute;
        }
        """;

    private const string AuthoringStubs = """
        namespace Elsa.Workflows.Design.Core.Authoring
        {
            public interface ISequenceBuilder
            {
                ActivityCall<TResult> Add<TActivity, TResult>(string activityVersionId, System.Action<IActivityInputBuilder<TActivity>>? inputs = null, string? nodeId = null);
            }

            public interface IActivityInputBuilder<TActivity>
            {
                IActivityInputBuilder<TActivity> Set<T>(string inputKey, ActivityArgument<T> argument);
            }

            public readonly struct ActivityArgument<T>;
            public sealed record ActivityNodeHandle(string NodeId);
            public sealed record ActivityOutcomeSource(ActivityNodeHandle Node, string OutcomeKey);
            public sealed class ActivityResultSource<T>;

            public sealed class ActivityCall<TResult>
            {
                public ActivityNodeHandle Node { get; } = new("node");
                public ActivityResultSource<TResult> Result { get; } = new();
                public ActivityResultSource<T> Output<T>(string projectionKey) => new();
                public ActivityOutcomeSource Outcome(string outcomeKey) => new(Node, outcomeKey);
            }
        }
        """;
}
