namespace Elsa.Maps.Generator;

/// <summary>
/// Writes <c>docs/maps/architecture-reference-map.md</c> and <c>docs/reports/maps-v2-findings.md</c>:
/// direct project references that cross the design/runtime seam, and projects that reach both sides.
/// </summary>
/// <remarks>
/// A signal here is a review prompt, not an automatic constitution violation. The authoritative seam
/// enforcement lives in <c>ArchitectureGuardTests</c>.
/// </remarks>
public static class ArchitectureReferenceMapGenerator
{
    private sealed record Signal(string Kind, string From, string FromPath, string To, string ToPath, string Note);

    private const string RuntimeToDesignNote = "review signal";
    private const string DesignToRuntimeNote = "expected in some design/read/publish paths; review context";

    /// <summary>Generates both files and returns the repo-relative paths written.</summary>
    public static IReadOnlyList<string> Generate(RepoContext repo, IReadOnlyList<ProjectFacts> projects)
    {
        var byName = projects.ToDictionary(project => project.Name, StringComparer.Ordinal);

        var edges = projects
            .Where(project => project.Kind == "source")
            .SelectMany(project => project.References
                .Where(byName.ContainsKey)
                .Select(reference => (From: project, To: byName[reference])))
            .ToArray();

        var signals = edges
            .Select(edge => (edge, fromPhase: Phase(edge.From.Name), toPhase: Phase(edge.To.Name)))
            .Where(candidate => candidate is { fromPhase: "runtime", toPhase: "design" } or { fromPhase: "design", toPhase: "runtime" })
            .Select(candidate => new Signal(
                candidate.fromPhase == "runtime" ? "runtime-to-design" : "design-to-runtime",
                candidate.edge.From.Name,
                candidate.edge.From.RelativePath,
                candidate.edge.To.Name,
                candidate.edge.To.RelativePath,
                candidate.fromPhase == "runtime" ? RuntimeToDesignNote : DesignToRuntimeNote))
            .OrderBy(signal => $"{signal.Kind}\t{signal.From}\t{signal.FromPath}\t{signal.To}\t{signal.ToPath}\t{signal.Note}", StringComparer.Ordinal)
            .ToArray();

        var bridges = edges
            .GroupBy(edge => edge.From, ProjectComparer.Instance)
            .Select(group => (
                Project: group.Key,
                Design: group.Where(edge => Phase(edge.To.Name) == "design").Select(edge => edge.To.Name).ToArray(),
                Runtime: group.Where(edge => Phase(edge.To.Name) == "runtime").Select(edge => edge.To.Name).ToArray()))
            .Where(bridge => bridge.Design.Length > 0 && bridge.Runtime.Length > 0)
            .OrderBy(bridge => bridge.Project.Name, StringComparer.Ordinal)
            .ToArray();

        var runtimeToDesign = signals.Count(signal => signal.Kind == "runtime-to-design");
        var designToRuntime = signals.Count(signal => signal.Kind == "design-to-runtime");

        WriteMap(repo, signals, bridges, runtimeToDesign, designToRuntime);
        WriteFindings(repo, signals, bridges.Length, runtimeToDesign, designToRuntime);

        return ["docs/maps/architecture-reference-map.md", "docs/reports/maps-v2-findings.md"];
    }

    private static void WriteMap(
        RepoContext repo,
        IReadOnlyList<Signal> signals,
        IReadOnlyList<(ProjectFacts Project, string[] Design, string[] Runtime)> bridges,
        int runtimeToDesign,
        int designToRuntime)
    {
        var map = new MapBuilder()
            .Line("# Architecture Reference Map")
            .Line()
            .Line("Generated by `tools/maps/generate-architecture-reference-map`.")
            .Line()
            .Line("Records direct project-reference signals only. A signal is a review prompt, not an automatic constitution violation.")
            .Line()
            .Line("## Summary")
            .Line()
            .Line($"- Runtime-to-design direct reference signals: {runtimeToDesign}")
            .Line($"- Design-to-runtime direct reference signals: {designToRuntime}")
            .Line($"- Projects directly referencing both design and runtime projects: {bridges.Count}")
            .Line()
            .Line("## Direct Design/Runtime Signals")
            .Line()
            .Row("Signal", "From", "To", "Review note")
            .Line("|---|---|---|---|");

        if (signals.Count > 0)
            foreach (var signal in signals)
                map.Row(signal.Kind, $"[{signal.From}](../../{signal.FromPath})", $"[{signal.To}](../../{signal.ToPath})", signal.Note);
        else
            map.Row("ok", "-", "-", "No direct design/runtime reference signals found.");

        map.Line()
            .Line("## Bridge-Like Direct Reference Shape")
            .Line()
            .Row("Project", "Design references", "Runtime references")
            .Line("|---|---|---|");

        if (bridges.Count > 0)
            foreach (var bridge in bridges)
                map.Row(
                    $"[{bridge.Project.Name}](../../{bridge.Project.RelativePath})",
                    MarkdownTable.Cell(MarkdownTable.Lines(bridge.Design)),
                    MarkdownTable.Cell(MarkdownTable.Lines(bridge.Runtime)));
        else
            map.Row("-", "-", "-");

        MarkdownTable.Write(Path.Combine(repo.Root, "docs", "maps", "architecture-reference-map.md"), map.Content);
    }

    private static void WriteFindings(
        RepoContext repo,
        IReadOnlyList<Signal> signals,
        int bridgeCount,
        int runtimeToDesign,
        int designToRuntime)
    {
        var mapsDirectory = Path.Combine(repo.Root, "docs", "maps");

        var findings = new MapBuilder()
            .Line("# Maps v2 Findings")
            .Line()
            .Line("Generated by `tools/maps/generate-architecture-reference-map`.")
            .Line()
            .Line("This is a point-in-time report from generated map facts. It is not a constitution compliance verdict.")
            .Line()
            .Line("## Summary")
            .Line()
            .Line($"- Domains in domain map: {ReadSummary(Path.Combine(mapsDirectory, "domain-map.md"), "- Domains: ")}")
            .Line($"- Source extension catalogs discovered: {ReadSummary(Path.Combine(mapsDirectory, "extension-point-map.md"), "- Source catalogs discovered: ")}")
            .Line($"- Source extension catalogs indexed from root: {ReadSummary(Path.Combine(mapsDirectory, "extension-point-map.md"), "- Source catalogs indexed from root: ")}")
            .Line($"- Discovered source catalogs not linked from root index: {ReadSummary(Path.Combine(mapsDirectory, "extension-point-map.md"), "- Discovered source catalogs not linked from root index: ")}")
            .Line($"- Root-indexed catalogs missing on disk: {ReadSummary(Path.Combine(mapsDirectory, "extension-point-map.md"), "- Root-indexed catalogs missing on disk: ")}")
            .Line($"- Runtime-to-design direct reference signals: {runtimeToDesign}")
            .Line($"- Design-to-runtime direct reference signals: {designToRuntime}")
            .Line($"- Bridge-like direct reference shapes: {bridgeCount}")
            .Line()
            .Line("## Reference Signals")
            .Line();

        if (signals.Count > 0)
            foreach (var signal in signals)
                findings.Line($"- {signal.From} -> {signal.To} ({signal.Kind}): {signal.Note}.");
        else
            findings.Line("No direct design/runtime reference signals were found.");

        findings.Line()
            .Line("## Next Map Work")
            .Line()
            .Line("- Use these maps as inputs for constitution verification reports.")
            .Line("- Keep runtime/design reference signals as review prompts, not automatic violations.")
            .Line("- Build CShells appsettings generation as a separate work unit after feature identifiers and dependency expectations are pinned.");

        MarkdownTable.Write(Path.Combine(repo.Root, "docs", "reports", "maps-v2-findings.md"), findings.Content);
    }

    /// <summary>
    /// Reads a summary bullet out of a previously generated map, mirroring the shell version's
    /// cross-layer read. Reports "not generated" when the map has not been produced yet.
    /// </summary>
    private static string ReadSummary(string path, string prefix)
    {
        if (!File.Exists(path)) return "not generated";

        var line = File.ReadLines(path).FirstOrDefault(candidate => candidate.StartsWith(prefix, StringComparison.Ordinal));
        var value = line?[prefix.Length..];
        return string.IsNullOrEmpty(value) ? "unknown" : value;
    }

    /// <summary>design/runtime/bridge-like classification, from the project name alone.</summary>
    private static string Phase(string project)
    {
        if (Matches(project, "Design")) return "design";
        if (Matches(project, "Runtime")) return "runtime";
        if (Matches(project, "Publishing")) return "bridge-like";
        return "neutral";
    }

    private static bool Matches(string project, string segment) =>
        project.EndsWith($".{segment}", StringComparison.Ordinal) ||
        project.Contains($".{segment}.", StringComparison.Ordinal);

    private sealed class ProjectComparer : IEqualityComparer<ProjectFacts>
    {
        public static ProjectComparer Instance { get; } = new();

        public bool Equals(ProjectFacts? left, ProjectFacts? right) =>
            string.Equals(left?.Name, right?.Name, StringComparison.Ordinal);

        public int GetHashCode(ProjectFacts value) => StringComparer.Ordinal.GetHashCode(value.Name);
    }
}
