namespace Elsa.Maps.Generator;

/// <summary>
/// Writes <c>docs/maps/domain-map.md</c>: how projects group into domains, and which direct references
/// cross a domain boundary.
/// </summary>
public static class DomainMapGenerator
{
    /// <summary>Generates the map and returns the repo-relative paths written.</summary>
    public static IReadOnlyList<string> Generate(RepoContext repo, IReadOnlyList<ProjectFacts> projects)
    {
        var domains = projects.Select(project => project.Domain).Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal).ToArray();
        var domainByProject = projects.ToDictionary(project => project.Name, project => project.Domain, StringComparer.Ordinal);
        var pathByProject = projects.ToDictionary(project => project.Name, project => project.RelativePath, StringComparer.Ordinal);

        var crossDomain = projects
            .SelectMany(project => project.References.Select(reference => (From: project.Name, To: reference)))
            .Where(edge => domainByProject.TryGetValue(edge.To, out var toDomain) && domainByProject[edge.From] != toDomain)
            .ToArray();

        var map = new MapBuilder()
            .Line("# Domain Map")
            .Line()
            .Line("Generated by `tools/maps/generate-domain-map`.")
            .Line()
            .Line("Records project grouping and direct reference facts only. Roles are heuristic navigation labels, not constitution verdicts.")
            .Line()
            .Line("## Summary")
            .Line()
            .Line($"- Source projects: {projects.Count(project => project.Kind == "source")}")
            .Line($"- Test projects: {projects.Count(project => project.Kind == "test")}")
            .Line($"- Domains: {domains.Length}")
            .Line($"- Direct cross-domain references: {crossDomain.Length}")
            .Line()
            .Line("## Domains")
            .Line()
            .Row("Domain", "Source projects", "Test projects", "Roles")
            .Line("|---|---:|---:|---|");

        foreach (var domain in domains)
        {
            var inDomain = projects.Where(project => project.Domain == domain).ToArray();
            var roles = inDomain.Select(project => project.Role).Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal);
            map.Row(
                domain,
                inDomain.Count(project => project.Kind == "source").ToString(),
                inDomain.Count(project => project.Kind == "test").ToString(),
                MarkdownTable.Cell(MarkdownTable.Lines(roles)));
        }

        map.Line()
            .Line("## Projects")
            .Line()
            .Row("Project", "Kind", "Domain", "Sub-domain", "Role", "Direct references")
            .Line("|---|---|---|---|---|---|");

        foreach (var project in projects)
            map.Row(
                $"[{project.Name}](../../{project.RelativePath})",
                project.Kind,
                project.Domain,
                MarkdownTable.Cell(project.SubDomain),
                project.Role,
                MarkdownTable.Cell(MarkdownTable.Lines(project.References)));

        map.Line()
            .Line("## Direct Cross-Domain References")
            .Line()
            .Row("From", "From domain", "To", "To domain")
            .Line("|---|---|---|---|");

        // Sorted on the same composite the shell pipeline sorted: from, from-path, from-domain, to, ...
        var orderedEdges = crossDomain
            .Select(edge => (
                Key: $"{edge.From}\t{pathByProject[edge.From]}\t{domainByProject[edge.From]}\t{edge.To}\t{pathByProject[edge.To]}\t{domainByProject[edge.To]}",
                edge.From,
                edge.To))
            .Order(Comparer<(string Key, string From, string To)>.Create(
                (left, right) => string.CompareOrdinal(left.Key, right.Key)));

        foreach (var edge in orderedEdges)
            map.Row(
                $"[{edge.From}](../../{pathByProject[edge.From]})",
                domainByProject[edge.From],
                $"[{edge.To}](../../{pathByProject[edge.To]})",
                domainByProject[edge.To]);

        MarkdownTable.Write(Path.Combine(repo.Root, "docs", "maps", "domain-map.md"), map.Content);
        return ["docs/maps/domain-map.md"];
    }
}
