using System.Text.RegularExpressions;

namespace Elsa.Maps.Generator;

/// <summary>
/// Writes <c>docs/maps/extension-point-map.md</c>: every <c>EXTENSION_POINTS.md</c> catalog, what it
/// declares, and whether the root index links it.
/// </summary>
/// <remarks>
/// Records catalog facts only; it does not validate catalog completeness, which stays a human judgement
/// per the review's D1 recommendation.
/// </remarks>
public static partial class ExtensionPointMapGenerator
{
    [GeneratedRegex(@"\]\((src/[^)]+/EXTENSION_POINTS\.md)\)", RegexOptions.Compiled)]
    private static partial Regex RootIndexLinkPattern { get; }

    private sealed record Catalog(
        string RelativePath,
        string Project,
        string Domain,
        string Sections,
        string Points,
        string Kinds,
        int KnownImplementationBlocks,
        string RootIndexed);

    /// <summary>Generates the map and returns the repo-relative paths written.</summary>
    public static IReadOnlyList<string> Generate(RepoContext repo, IReadOnlyList<ProjectFacts> projects)
    {
        var rootIndexPath = Path.Combine(repo.Root, "EXTENSION_POINTS.md");
        var hasRootIndex = File.Exists(rootIndexPath);

        var indexed = hasRootIndex
            ? RootIndexLinkPattern.Matches(File.ReadAllText(rootIndexPath))
                .Select(match => match.Groups[1].Value)
                .Distinct(StringComparer.Ordinal)
                .Order(StringComparer.Ordinal)
                .ToArray()
            : [];

        var catalogPaths = new List<string>();
        if (hasRootIndex) catalogPaths.Add("EXTENSION_POINTS.md");
        catalogPaths.AddRange(repo.ListFiles("src/EXTENSION_POINTS.md", "src/*/EXTENSION_POINTS.md"));

        var catalogs = catalogPaths
            .Distinct(StringComparer.Ordinal)
            .Order(StringComparer.Ordinal)
            .Select(relativePath => ReadCatalog(repo, projects, relativePath, indexed))
            .ToArray();

        var discoveredSource = catalogs
            .Where(catalog => catalog.RelativePath.StartsWith("src/", StringComparison.Ordinal))
            .Select(catalog => catalog.RelativePath)
            .Distinct(StringComparer.Ordinal)
            .Order(StringComparer.Ordinal)
            .ToArray();

        var notIndexed = discoveredSource.Except(indexed, StringComparer.Ordinal).Order(StringComparer.Ordinal).ToArray();
        var missing = indexed.Except(discoveredSource, StringComparer.Ordinal).Order(StringComparer.Ordinal).ToArray();

        var map = new MapBuilder()
            .Line("# Extension-Point Map")
            .Line()
            .Line("Generated by `tools/maps/generate-extension-point-map`.")
            .Line()
            .Line("Records Markdown catalog facts from `EXTENSION_POINTS.md` files. It does not validate catalog completeness.")
            .Line()
            .Line("## Summary")
            .Line()
            .Line($"- Catalog files discovered: {catalogs.Length}")
            .Line($"- Source catalogs discovered: {discoveredSource.Length}")
            .Line($"- Source catalogs indexed from root: {indexed.Length}")
            .Line($"- Discovered source catalogs not linked from root index: {notIndexed.Length}")
            .Line($"- Root-indexed catalogs missing on disk: {missing.Length}")
            .Line()
            .Line("## Catalogs")
            .Line()
            .Row("Catalog", "Owner project", "Domain", "Sections", "Extension-point headings", "Kind lines", "Known implementation blocks", "Root indexed")
            .Line("|---|---|---|---|---|---|---:|---|");

        foreach (var catalog in catalogs)
            map.Row(
                $"[{catalog.RelativePath}](../../{catalog.RelativePath})",
                catalog.Project,
                catalog.Domain,
                MarkdownTable.Cell(catalog.Sections),
                MarkdownTable.Cell(catalog.Points),
                MarkdownTable.Cell(catalog.Kinds),
                catalog.KnownImplementationBlocks.ToString(),
                catalog.RootIndexed);

        map.Line()
            .Line("## Root Index Coverage")
            .Line()
            .Row("Status", "Catalog")
            .Line("|---|---|");

        if (notIndexed.Length == 0 && missing.Length == 0)
        {
            map.Row("ok", "Root index and discovered source catalogs match.");
        }
        else
        {
            foreach (var relativePath in notIndexed)
                map.Row("discovered but not root-indexed", $"[{relativePath}](../../{relativePath})");
            foreach (var relativePath in missing)
                map.Row("root-indexed but missing on disk", relativePath);
        }

        MarkdownTable.Write(Path.Combine(repo.Root, "docs", "maps", "extension-point-map.md"), map.Content);
        return ["docs/maps/extension-point-map.md"];
    }

    private static Catalog ReadCatalog(
        RepoContext repo,
        IReadOnlyList<ProjectFacts> projects,
        string relativePath,
        IReadOnlyList<string> indexed)
    {
        var lines = File.ReadAllLines(repo.Absolute(relativePath));
        var project = OwnerProject(projects, relativePath);

        var rootIndexed = relativePath == "EXTENSION_POINTS.md"
            ? "root"
            : indexed.Contains(relativePath, StringComparer.Ordinal) ? "yes" : "no";

        return new Catalog(
            relativePath,
            project,
            project == "-" ? "repo root" : ProjectGraph.DomainGroup(project),
            MarkdownTable.Lines(Prefixed(lines, "## ").Where(section => section is not ("Cross-references" or "Constitutional basis"))),
            MarkdownTable.Lines(Prefixed(lines, "### ")),
            MarkdownTable.Lines(Prefixed(lines, "- **Kind:** ")),
            lines.Count(line => line.StartsWith("**Known implementations", StringComparison.Ordinal)),
            rootIndexed);
    }

    private static IEnumerable<string> Prefixed(IEnumerable<string> lines, string prefix) =>
        lines.Where(line => line.StartsWith(prefix, StringComparison.Ordinal)).Select(line => line[prefix.Length..]);

    /// <summary>
    /// The nearest project that owns a catalog, found by walking up from the catalog's directory and
    /// taking the ordinally-first <c>.csproj</c> in the first directory that has one.
    /// </summary>
    /// <remarks>
    /// Deliberately not <see cref="ProjectGraph.OwningProject{T}"/>. That picks the longest matching
    /// directory prefix; this picks the first match walking upward, which differs when a directory holds
    /// several projects. The shell generator used <c>find -maxdepth 1 … | sort | head -1</c> per level,
    /// and the map's byte-for-byte output depends on reproducing that rule rather than the other one.
    /// </remarks>
    private static string OwnerProject(IReadOnlyList<ProjectFacts> projects, string relativePath)
    {
        var directory = Path.GetDirectoryName(relativePath)?.Replace('\\', '/') ?? string.Empty;

        while (true)
        {
            var prefix = directory.Length == 0 ? string.Empty : directory + "/";
            var owner = projects
                .Where(project => project.RelativePath.StartsWith(prefix, StringComparison.Ordinal))
                .Where(project => !project.RelativePath[prefix.Length..].Contains('/', StringComparison.Ordinal))
                .Order(Comparer<ProjectFacts>.Create((left, right) => string.CompareOrdinal(left.RelativePath, right.RelativePath)))
                .FirstOrDefault();

            if (owner is not null) return owner.Name;
            if (directory.Length == 0) return "-";

            var separator = directory.LastIndexOf('/');
            directory = separator < 0 ? string.Empty : directory[..separator];
        }
    }
}
