using System.Text.Json;

namespace Elsa.Maps.Generator;

/// <summary>
/// Writes <c>docs/maps/feature-dependency-map.md</c>: CShells feature identity, the public properties a
/// feature exposes to configuration, and dependency evidence from direct project/package references.
/// </summary>
/// <remarks>
/// Dependency rows are evidence, not policy: a direct project reference does not prove the referenced
/// feature must be activated in the same shell.
/// </remarks>
public static class FeatureDependencyMapGenerator
{
    /// <summary>Generates the map and returns the repo-relative paths written.</summary>
    public static IReadOnlyList<string> Generate(RepoContext repo, IReadOnlyList<ProjectFacts> projects)
    {
        var sourceProjects = projects.Where(project => project.Kind == "source").ToArray();
        var packages = PackageVersions.Load(repo);
        var features = FeatureScanner.Scan(repo, projects);

        var featureProjects = features.Select(feature => feature.Project).ToHashSet(StringComparer.Ordinal);

        // For a referenced feature project, report its feature IDs (falling back to class names).
        var idsByProject = features
            .GroupBy(feature => feature.Project, StringComparer.Ordinal)
            .ToDictionary(
                group => group.Key,
                group => group
                    .Select(feature => feature.FeatureId != "-" ? feature.FeatureId : feature.ClassName)
                    .Distinct(StringComparer.Ordinal)
                    .Order(StringComparer.Ordinal)
                    .ToArray(),
                StringComparer.Ordinal);

        var duplicates = features
            .Where(feature => feature.FeatureId != "-")
            .GroupBy(feature => feature.FeatureId, StringComparer.Ordinal)
            .Where(group => group.Count() > 1)
            .Select(group => (
                Id: group.Key,
                Classes: MarkdownTable.Lines(group.Select(feature => feature.ClassName)),
                Projects: MarkdownTable.Lines(group.Select(feature => feature.Project))))
            .OrderBy(duplicate => duplicate.Id, StringComparer.Ordinal)
            .ToArray();

        var missingConcreteId = features.Count(feature => !feature.IsAbstract && feature.FeatureId == "-");

        var map = new MapBuilder()
            .Line("# Feature Dependency Map")
            .Line()
            .Line("Generated by `tools/maps/generate-feature-dependency-map`.")
            .Line()
            .Line("Records CShells feature identity, public feature properties, and dependency evidence from direct project/package references. It does not generate appsettings JSON and does not treat `src/Apps/Elsa.Server` composition choices as canonical.")
            .Line()
            .Line("## Summary")
            .Line()
            .Line($"- Feature classes: {features.Count}")
            .Line($"- Concrete features missing explicit ShellFeature ID: {missingConcreteId}")
            .Line($"- Duplicate explicit feature IDs: {duplicates.Length}")
            .Line($"- Feature-bearing source projects: {featureProjects.Count}")
            .Line("- IConfiguration feature-registration shape observed from: `src/Apps/Elsa.Server/appsettings.json`")
            .Line()
            .Line("## IConfiguration Shape Evidence")
            .Line()
            .Line("The test shell is not a composition source of truth. The only evidence taken from `src/Apps/Elsa.Server/appsettings.json` is the JSON shape: `CShells:Shells:{shellName}:Features:{featureId}` with optional nested feature settings such as `Options`, plus shell-level `Configuration`.")
            .Line()
            .Line("Observed default-shell feature keys:")
            .Line();

        var defaultKeys = ReadDefaultShellFeatureKeys(repo);
        if (defaultKeys.Count > 0)
            foreach (var key in defaultKeys)
                map.Line($"- `{key}`");
        else
            map.Line("- none");

        map.Line()
            .Line("## Duplicate Feature IDs")
            .Line();

        if (duplicates.Length == 0)
        {
            map.Line("No duplicate explicit feature IDs were discovered.");
        }
        else
        {
            map.Row("Feature ID", "Feature classes", "Projects")
                .Line("|---|---|---|");
            foreach (var duplicate in duplicates)
                map.Row(duplicate.Id, MarkdownTable.Cell(duplicate.Classes), MarkdownTable.Cell(duplicate.Projects));
        }

        map.Line()
            .Line("## Feature Identity And Configuration Inputs")
            .Line()
            .Row("Feature ID", "Feature class", "Abstract", "Project", "Public feature properties", "Option/config signals", "File")
            .Line("|---|---|---|---|---|---|---|");

        foreach (var feature in features)
            map.Row(
                feature.FeatureId,
                feature.ClassName,
                feature.IsAbstract ? "True" : "False",
                feature.Project,
                MarkdownTable.Cell(MarkdownTable.Lines(feature.Properties)),
                MarkdownTable.Cell(MarkdownTable.Lines(feature.OptionSignals)),
                $"[{Path.GetFileName(feature.RelativePath)}](../../{feature.RelativePath})");

        map.Line()
            .Line("## Feature Dependency Evidence")
            .Line()
            .Line("Rows below are dependency evidence, not final policy. Feature-project references means the feature's owning project directly references another project that also declares one or more feature classes. Core/helper references are still important runtime prerequisites, but they are not feature activation IDs by themselves.")
            .Line()
            .Row("Feature ID", "Project", "Feature-project references", "Core/helper project references", "Direct external packages")
            .Line("|---|---|---|---|---|");

        var projectByName = sourceProjects.ToDictionary(project => project.Name, StringComparer.Ordinal);

        foreach (var feature in features.Where(feature => !feature.IsAbstract))
        {
            if (!projectByName.TryGetValue(feature.Project, out var project)) continue;

            var featureRefs = project.References
                .Where(featureProjects.Contains)
                .Select(reference => $"{reference} ({string.Join(", ", idsByProject[reference])})")
                .Distinct(StringComparer.Ordinal)
                .Order(StringComparer.Ordinal)
                .ToArray();

            var coreRefs = project.References
                .Where(reference => !featureProjects.Contains(reference))
                .Distinct(StringComparer.Ordinal)
                .Order(StringComparer.Ordinal)
                .ToArray();

            map.Row(
                feature.FeatureId,
                feature.Project,
                MarkdownTable.Cell(MarkdownTable.Lines(featureRefs)),
                MarkdownTable.Cell(MarkdownTable.Lines(coreRefs)),
                MarkdownTable.Cell(MarkdownTable.Lines(packages.ReferencesFor(repo.Absolute(project.RelativePath)))));
        }

        map.Line()
            .Line("## Gaps For Generator Work")
            .Line()
            .Line("- Direct project references do not prove that a referenced feature must be activated in the same shell.")
            .Line("- Public feature properties expose possible IConfiguration keys, but required/default/secret/path/type-name classification still needs an architecture decision.")
            .Line("- Feature IDs must stay explicit on concrete features; abstract feature bases may remain unannotated unless base metadata becomes useful.")
            .Line("- Nuplane assembly-loading settings are host/loading evidence, not feature-selection evidence.")
            .Line("- A CShells appsettings generator should consume this map plus an approved configuration/settings classification before emitting JSON.");

        MarkdownTable.Write(Path.Combine(repo.Root, "docs", "maps", "feature-dependency-map.md"), map.Content);
        return ["docs/maps/feature-dependency-map.md"];
    }

    /// <summary>
    /// The feature keys enabled on the default shell, read only as evidence of the JSON shape.
    /// </summary>
    private static IReadOnlyList<string> ReadDefaultShellFeatureKeys(RepoContext repo)
    {
        var path = Path.Combine(repo.Root, "src", "Apps", "Elsa.Server", "appsettings.json");
        if (!File.Exists(path)) return [];

        using var document = JsonDocument.Parse(File.ReadAllText(path), new JsonDocumentOptions
        {
            CommentHandling = JsonCommentHandling.Skip,
            AllowTrailingCommas = true
        });

        if (!document.RootElement.TryGetProperty("CShells", out var cshells) ||
            !cshells.TryGetProperty("Shells", out var shells) ||
            !shells.TryGetProperty("default", out var defaultShell) ||
            !defaultShell.TryGetProperty("Features", out var featuresElement) ||
            featuresElement.ValueKind != JsonValueKind.Object)
            return [];

        return featuresElement.EnumerateObject()
            .Select(property => property.Name)
            .Order(StringComparer.Ordinal)
            .ToArray();
    }
}
