// <auto-generated />
using Elsa.Foundation.Identity.Persistence.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elsa.Foundation.Identity.Persistence.EntityFrameworkCore.Migrations.IdentityProviderConfiguration.SqlServer
{
    [DbContext(typeof(IdentityProviderConfigurationSqlServerDbContext))]
    partial class IdentityProviderConfigurationSqlServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            // SqlServerModelBuilderExtensions.UseIdentityColumns omitted: the module stays provider-free.

            modelBuilder.Entity("Elsa.Foundation.Identity.Persistence.EntityFrameworkCore.Entities.GlobalProviderConfigurationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PermissionPropagation")
                        .HasColumnType("int");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("nvarchar(1600)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ProviderLookupKey")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("nvarchar(1600)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SupportsApplicationManagement")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportsGroupSync")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportsLocalRoleManagement")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportsLocalUserManagement")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportsRefresh")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportsRevocation")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportsTokenIssuance")
                        .HasColumnType("bit");

                    b.Property<string>("TenantId")
                        .HasMaxLength(1600)
                        .HasColumnType("nvarchar(1600)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("TenantLookupKey")
                        .HasMaxLength(1600)
                        .HasColumnType("nvarchar(1600)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("Id");

                    b.HasIndex("SchemaVersion");

                    b.ToTable("identity_global_provider_configurations", (string)null);
                });

            modelBuilder.Entity("Elsa.Foundation.Identity.Persistence.EntityFrameworkCore.Entities.TenantProviderConfigurationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PermissionPropagation")
                        .HasColumnType("int");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("nvarchar(1600)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ProviderLookupKey")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("nvarchar(1600)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SupportsApplicationManagement")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportsGroupSync")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportsLocalRoleManagement")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportsLocalUserManagement")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportsRefresh")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportsRevocation")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportsTokenIssuance")
                        .HasColumnType("bit");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("nvarchar(1600)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("TenantLookupKey")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("nvarchar(1600)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("Id");

                    b.HasIndex("SchemaVersion");

                    b.ToTable("identity_provider_configurations", (string)null);
                });

            modelBuilder.Entity("Elsa.Persistence.EntityFramework.SchemaFinalization.EfDatabaseIdentityRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("DatabaseIdentity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("SchemaVersion");

                    b.ToTable("__ElsaDatabaseIdentity_ElsaIdentityProviderConfiguration", (string)null);
                });

            modelBuilder.Entity("Elsa.Persistence.EntityFramework.SchemaFinalization.EfSchemaFinalizationRecordRow", b =>
                {
                    b.Property<string>("Family")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("DatabaseIdentity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FinalizedVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("FinishHistoryJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinishJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistoryJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoldsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntentJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Family");

                    b.HasIndex("SchemaVersion");

                    b.ToTable("__ElsaSchemaFinalization_ElsaIdentityProviderConfiguration", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
