<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="CShells.Abstractions" />
		<PackageReference Include="Elsa.Specifications.PackageManifest.Generator" PrivateAssets="all" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
		<PackageReference Include="Microsoft.Extensions.Options" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Core\Elsa.Foundation.Identity.Core.csproj" />
		<ProjectReference Include="..\Elsa.Foundation.Identity.csproj" />
	</ItemGroup>

</Project>
