<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>0.0.1-local</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CShells.Abstractions" />
    <PackageReference Include="Elsa.Platform.PackageManifest.Generator" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Elsa.Diagnostics.Persistence.csproj" />
    <ProjectReference Include="..\..\OpenTelemetry\Persistence\Groundwork\Elsa.Diagnostics.OpenTelemetry.Persistence.Groundwork.csproj" />
    <ProjectReference Include="..\..\StructuredLogs\Persistence\Groundwork\Elsa.Diagnostics.StructuredLogs.Persistence.Groundwork.csproj" />
  </ItemGroup>

</Project>
