<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Activities\Design\Core\Elsa.Activities.Design.Core.csproj" />
    <ProjectReference Include="..\..\..\Events\Core\Elsa.Events.Core.csproj" />
    <ProjectReference Include="..\..\..\Primitives\Primitives\Elsa.Primitives.csproj" />
    <ProjectReference Include="..\..\..\Expressions\Core\Elsa.Expressions.Core.csproj" />
  </ItemGroup>

</Project>
