<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="CShells.Abstractions" />
    <PackageReference Include="Elsa.Platform.PackageManifest.Generator" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../Attention/Core/Elsa.Attention.Core.csproj" />
    <ProjectReference Include="../Core/Elsa.Modularity.Core.csproj" />
    <ProjectReference Include="../Api/Elsa.Modularity.Api.csproj" />
  </ItemGroup>
</Project>
