<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="CShells.FastEndpoints" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <ProjectReference Include="../../../src/Elsa/Api/FastEndpoints/Elsa.Api.FastEndpoints.csproj" />
    <ProjectReference Include="../../../src/Elsa/Foundation/Identity/Abstractions/Elsa.Foundation.Identity.Abstractions.csproj" />
    <ProjectReference Include="../../../src/Elsa/Mediator/Core/Elsa.Mediator.Core.csproj" />
    <ProjectReference Include="../../../src/Elsa/Primitives/Primitives/Elsa.Primitives.csproj" />
    <ProjectReference Include="../../../src/Elsa/Workflows/Runtime/Api/Elsa.Workflows.Runtime.Api.csproj" />
    <ProjectReference Include="../../../tests/Elsa/Api/Compatibility/Testing/Elsa.Api.Compatibility.Testing.csproj" />
  </ItemGroup>
</Project>
