<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CShells.Abstractions" />
    <PackageReference Include="Elsa.Platform.PackageManifest.Generator" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="Core\Elsa.Secrets.Core.csproj" />
    <ProjectReference Include="..\Expressions\Core\Elsa.Expressions.Core.csproj" />
    <ProjectReference Include="..\Serialization\Core\Elsa.Serialization.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Api/**/*;Attention/**/*;Core/**/*;Persistence/**/*" />
    <EmbeddedResource Remove="Api/**/*;Attention/**/*;Core/**/*;Persistence/**/*" />
    <None Remove="Api/**/*;Attention/**/*;Core/**/*;Persistence/**/*" />
  </ItemGroup>

</Project>
