<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Elsa.Events.Core.csproj" />
    <ProjectReference Include="..\..\Primitives\Primitives\Elsa.Primitives.csproj" />
  </ItemGroup>

</Project>
