<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authorization" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.10" />
	  <PackageReference Include="CShells.Abstractions" Version="0.0.26" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Http\Core\Elsa.Http.Core.csproj" />
    <ProjectReference Include="..\..\..\Primitives\Primitives\Elsa.Primitives.csproj" />
  </ItemGroup>

</Project>
