<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Abstractions" />
    <PackageReference Include="Microsoft.AspNetCore.Authorization" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
	  <PackageReference Include="CShells.Abstractions" />
    <PackageReference Include="Elsa.Platform.PackageManifest.Generator" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Http\Core\Elsa.Http.Core.csproj" />
    <ProjectReference Include="..\..\..\Primitives\Primitives\Elsa.Primitives.csproj" />
    <ProjectReference Include="..\..\..\Tasks\Core\Elsa.Tasks.Core.csproj" />
    <ProjectReference Include="..\Core\Elsa.Workflows.Runtime.Core.csproj" />
  </ItemGroup>

</Project>
