<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Elsa.Activities.Design.Api</RootNamespace>
    <AssemblyName>Elsa.Activities.Design.Api.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Models\*.cs"
             Exclude="..\Models\ActivityProblemDetails.cs"
             Link="Models\%(Filename)%(Extension)" />
    <Compile Include="..\Requests\*.cs" Link="Requests\%(Filename)%(Extension)" />
    <Compile Include="..\Commands\*.cs" Link="Commands\%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Elsa.Activities.Design.Core.csproj" />
    <ProjectReference Include="..\..\..\..\Mediator\Core\Elsa.Mediator.Core.csproj" />
  </ItemGroup>

</Project>
