<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="CShells.Abstractions" />
		<PackageReference Include="CShells.AspNetCore.Abstractions" />
		<PackageReference Include="Elsa.Platform.PackageManifest.Generator" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Activities\Design\Persistence\Core\Elsa.Activities.Design.Persistence.Core.csproj" />
		<ProjectReference Include="..\..\..\Api\AspNetCore\Elsa.Api.AspNetCore.csproj" />
		<ProjectReference Include="..\..\..\Api\Capabilities\Elsa.Api.Capabilities.csproj" />
		<ProjectReference Include="..\..\..\Events\Core\Elsa.Events.Core.csproj" />
		<ProjectReference Include="..\..\..\Foundation\Identity\Abstractions\Elsa.Foundation.Identity.Abstractions.csproj" />
		<ProjectReference Include="..\..\..\Locking\Core\Elsa.Locking.Core.csproj" />
		<ProjectReference Include="..\..\..\Mediator\Core\Elsa.Mediator.Core.csproj" />
		<ProjectReference Include="..\..\..\Serialization\Core\Elsa.Serialization.Core.csproj" />
		<ProjectReference Include="..\Persistence\Core\Elsa.Workflows.Design.Persistence.Core.csproj" />
		<ProjectReference Include="..\Validations\Core\Elsa.Workflows.Design.Validations.Core.csproj" />
		<ProjectReference Include="..\..\..\Tasks\Core\Elsa.Tasks.Core.csproj" />
	</ItemGroup>

</Project>
