<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Groundwork.PostgreSql" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="CShells.Abstractions" />
    <PackageReference Include="Elsa.Platform.PackageManifest.Generator" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Elsa.Persistence.Groundwork.PostgreSql.csproj" />
    <ProjectReference Include="..\..\Unified\Elsa.Persistence.Groundwork.Unified.csproj" />
    <ProjectReference Include="..\..\..\..\Secrets\Persistence\Groundwork\Elsa.Secrets.Persistence.Groundwork.csproj" />
    <ProjectReference Include="..\..\..\..\Workflows\Dashboard\Persistence\Groundwork\Elsa.Workflows.Dashboard.Persistence.Groundwork.csproj" />
  </ItemGroup>

</Project>
