<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="CShells.Abstractions" />
    <PackageReference Include="Elsa.Platform.PackageManifest.Generator" PrivateAssets="all" />
    <PackageReference Include="Groundwork.Kernel" />
    <PackageReference Include="Groundwork.Query.Model" />
    <PackageReference Include="Groundwork.Store" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Activities\Design\Core\Elsa.Activities.Design.Core.csproj" />
    <ProjectReference Include="..\..\..\..\Activities\Design\Persistence\Core\Elsa.Activities.Design.Persistence.Core.csproj" />
    <ProjectReference Include="..\..\..\..\Activities\Design\Persistence\Groundwork\Elsa.Activities.Design.Persistence.Groundwork.csproj" />
    <ProjectReference Include="..\..\..\..\Persistence\Groundwork\V2\Elsa.Persistence.Groundwork.V2.csproj" />
    <ProjectReference Include="..\..\..\..\Serialization\Core\Elsa.Serialization.Core.csproj" />
    <ProjectReference Include="..\..\..\Design\Core\Elsa.Workflows.Design.Core.csproj" />
    <ProjectReference Include="..\..\..\Design\Persistence\Core\Elsa.Workflows.Design.Persistence.Core.csproj" />
    <ProjectReference Include="..\..\..\Design\Persistence\Groundwork\Elsa.Workflows.Design.Persistence.Groundwork.csproj" />
    <ProjectReference Include="..\..\Core\Elsa.Workflows.Publishing.Core.csproj" />
    <ProjectReference Include="..\..\..\Runtime\Core\Elsa.Workflows.Runtime.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Sqlite\**\*.cs" />
    <EmbeddedResource Remove="Sqlite\**\*" />
    <None Remove="Sqlite\**\*" />
  </ItemGroup>
</Project>
