<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Groundwork.Core" />
    <PackageReference Include="Groundwork.Documents" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Core\Elsa.Workflows.Publishing.Core.csproj" />
    <ProjectReference Include="..\..\..\..\Persistence\Groundwork\Composition\Elsa.Persistence.Groundwork.Composition.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Sqlite\**\*.cs" />
    <EmbeddedResource Remove="Sqlite\**\*" />
    <None Remove="Sqlite\**\*" />
  </ItemGroup>
</Project>
