<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="CShells.Abstractions" />
    <PackageReference Include="Elsa.Platform.PackageManifest.Generator" PrivateAssets="all" />
    <PackageReference Include="Groundwork.Kernel" />
    <PackageReference Include="Groundwork.Query.Model" />
    <PackageReference Include="Groundwork.Store" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Elsa.Secrets.csproj" />
    <ProjectReference Include="..\..\Core\Elsa.Secrets.Core.csproj" />
    <ProjectReference Include="..\..\..\Persistence\Groundwork\Composition\Elsa.Persistence.Groundwork.Composition.csproj" />
  </ItemGroup>

</Project>
