<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Groundwork.Kernel" />
    <PackageReference Include="Groundwork.MongoDb" VersionOverride="0.4.0-preview.2" />
    <PackageReference Include="Groundwork.PostgreSql" VersionOverride="0.4.0-preview.2" />
    <PackageReference Include="Groundwork.Query.Model" />
    <PackageReference Include="Groundwork.Store" />
    <PackageReference Include="Groundwork.Sqlite" VersionOverride="0.4.0-preview.2" />
    <PackageReference Include="Groundwork.SqlServer" VersionOverride="0.4.0-preview.2" />
    <PackageReference Include="Groundwork.Testing" VersionOverride="0.4.0-preview.2" />
    <PackageReference Include="Microsoft.Data.SqlClient" VersionOverride="7.0.2" />
    <PackageReference Include="MongoDB.Driver" VersionOverride="3.10.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Xunit.SkippableFact" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\..\..\src\Elsa\Workflows\Publishing\Persistence\Groundwork\Elsa.Workflows.Publishing.Persistence.Groundwork.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\..\src\Elsa\Workflows\Publishing\Elsa.Workflows.Publishing.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\..\src\Elsa\Workflows\Publishing\Api\Elsa.Workflows.Publishing.Api.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\..\src\Elsa\Persistence\Groundwork\V2\Elsa.Persistence.Groundwork.V2.csproj" />
    <ProjectReference Include="..\..\..\..\..\Persistence\Groundwork\Testing\Elsa.Persistence.Groundwork.Testing.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Fixtures\**\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
