Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$docsMaps = Join-Path $repoRoot "docs\maps"
$docsReports = Join-Path $repoRoot "docs\reports"

function To-RepoPath {
    param([string]$Path)
    $full = (Resolve-Path $Path).Path
    return ($full.Substring($repoRoot.Length + 1) -replace '\\', '/')
}

function Escape-Cell {
    param([string]$Value)
    if ([string]::IsNullOrWhiteSpace($Value)) { return "-" }
    return (($Value -replace '\|', '\|') -replace "`r?`n", "<br>")
}

function Get-Phase {
    param([string]$ProjectName)
    if ($ProjectName -match "\.Design(\.|$)") { return "design" }
    if ($ProjectName -match "\.Runtime(\.|$)") { return "runtime" }
    if ($ProjectName -match "\.Publishing(\.|$)") { return "bridge-like" }
    return "neutral"
}

function Read-Projects {
    $projectFiles = @()
    foreach ($root in @("src", "tests")) {
        $dir = Join-Path $repoRoot $root
        if (Test-Path -LiteralPath $dir) {
            $projectFiles += Get-ChildItem -LiteralPath $dir -Recurse -Filter "*.csproj" | Sort-Object FullName
        }
    }
    $projects = @()
    foreach ($file in $projectFiles) {
        [xml]$xml = Get-Content -LiteralPath $file.FullName -Raw
        $name = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
        $refs = @()
        foreach ($reference in @($xml.Project.SelectNodes("ItemGroup/ProjectReference"))) {
            if ($null -ne $reference -and -not [string]::IsNullOrWhiteSpace($reference.Include)) {
                $refs += [System.IO.Path]::GetFileNameWithoutExtension($reference.Include)
            }
        }
        $projects += [pscustomobject]@{ Name = $name; Path = To-RepoPath $file.FullName; Kind = if ($file.FullName -like "*\tests\*") { "test" } else { "source" }; Phase = Get-Phase $name; References = @($refs | Sort-Object -Unique) }
    }
    return @($projects | Sort-Object Kind, Name)
}

function Write-Lines {
    param([string]$Path, [string[]]$Lines)
    [System.IO.File]::WriteAllText($Path, (($Lines -join "`n") + "`n"), [System.Text.UTF8Encoding]::new($false))
}

New-Item -ItemType Directory -Force -Path $docsMaps | Out-Null
New-Item -ItemType Directory -Force -Path $docsReports | Out-Null
$projects = Read-Projects
$byName = @{}
foreach ($project in $projects) { $byName[$project.Name] = $project }

$signals = @()
$bridgeRows = @()
foreach ($project in $projects | Where-Object Kind -eq "source") {
    $resolvedRefs = @($project.References | Where-Object { $byName.ContainsKey($_) } | ForEach-Object { $byName[$_] })
    foreach ($target in $resolvedRefs) {
        if ($project.Phase -eq "runtime" -and $target.Phase -eq "design") {
            $signals += [pscustomobject]@{ Signal = "runtime-to-design"; From = $project; To = $target; Review = "review signal" }
        } elseif ($project.Phase -eq "design" -and $target.Phase -eq "runtime") {
            $signals += [pscustomobject]@{ Signal = "design-to-runtime"; From = $project; To = $target; Review = "expected in some design/read/publish paths; review context" }
        }
    }
    $hasDesign = @($resolvedRefs | Where-Object Phase -eq "design").Count -gt 0
    $hasRuntime = @($resolvedRefs | Where-Object Phase -eq "runtime").Count -gt 0
    if ($hasDesign -and $hasRuntime) {
        $bridgeRows += [pscustomobject]@{ Project = $project; DesignRefs = @($resolvedRefs | Where-Object Phase -eq "design" | Select-Object -ExpandProperty Name); RuntimeRefs = @($resolvedRefs | Where-Object Phase -eq "runtime" | Select-Object -ExpandProperty Name) }
    }
}

$lines = @(
    "# Architecture Reference Map",
    "",
    'Generated by `tools/maps/generate-architecture-reference-map`.',
    "",
    "Records direct project-reference signals only. A signal is a review prompt, not an automatic constitution violation.",
    "",
    "## Summary",
    "",
    "- Runtime-to-design direct reference signals: $(@($signals | Where-Object Signal -eq 'runtime-to-design').Count)",
    "- Design-to-runtime direct reference signals: $(@($signals | Where-Object Signal -eq 'design-to-runtime').Count)",
    "- Projects directly referencing both design and runtime projects: $($bridgeRows.Count)",
    "",
    "## Direct Design/Runtime Signals",
    "",
    "| Signal | From | To | Review note |",
    "|---|---|---|---|"
)
foreach ($signal in $signals | Sort-Object Signal, { $_.From.Name }, { $_.To.Name }) {
    $lines += "| $($signal.Signal) | [$($signal.From.Name)](../../$($signal.From.Path)) | [$($signal.To.Name)](../../$($signal.To.Path)) | $($signal.Review) |"
}
if ($signals.Count -eq 0) { $lines += "| ok | - | - | No direct design/runtime reference signals found. |" }

$lines += @("", "## Bridge-Like Direct Reference Shape", "", "| Project | Design references | Runtime references |", "|---|---|---|")
foreach ($row in $bridgeRows | Sort-Object { $_.Project.Name }) {
    $lines += "| [$($row.Project.Name)](../../$($row.Project.Path)) | $(Escape-Cell ($row.DesignRefs -join '<br>')) | $(Escape-Cell ($row.RuntimeRefs -join '<br>')) |"
}
if ($bridgeRows.Count -eq 0) { $lines += "| - | - | - |" }

Write-Lines -Path (Join-Path $docsMaps "architecture-reference-map.md") -Lines $lines

$extensionMap = Join-Path $docsMaps "extension-point-map.md"
$domainMap = Join-Path $docsMaps "domain-map.md"
$extensionText = if (Test-Path -LiteralPath $extensionMap) {
    Get-Content -LiteralPath $extensionMap -Raw
} else { "" }
$extensionSummary = if (-not [string]::IsNullOrWhiteSpace($extensionText)) {
    $match = [regex]::Match($extensionText, '(?m)^- Source catalogs discovered: (.+)$')
    if ($match.Success) { $match.Groups[1].Value } else { "unknown" }
} else { "not generated" }
$extensionIndexedSummary = if (-not [string]::IsNullOrWhiteSpace($extensionText)) {
    $match = [regex]::Match($extensionText, '(?m)^- Source catalogs indexed from root: (.+)$')
    if ($match.Success) { $match.Groups[1].Value } else { "unknown" }
} else { "not generated" }
$extensionNotIndexedSummary = if (-not [string]::IsNullOrWhiteSpace($extensionText)) {
    $match = [regex]::Match($extensionText, '(?m)^- Discovered source catalogs not linked from root index: (.+)$')
    if ($match.Success) { $match.Groups[1].Value } else { "unknown" }
} else { "not generated" }
$extensionMissingSummary = if (-not [string]::IsNullOrWhiteSpace($extensionText)) {
    $match = [regex]::Match($extensionText, '(?m)^- Root-indexed catalogs missing on disk: (.+)$')
    if ($match.Success) { $match.Groups[1].Value } else { "unknown" }
} else { "not generated" }
$domainSummary = if (Test-Path -LiteralPath $domainMap) {
    $text = Get-Content -LiteralPath $domainMap -Raw
    $match = [regex]::Match($text, '(?m)^- Domains: (.+)$')
    if ($match.Success) { $match.Groups[1].Value } else { "unknown" }
} else { "not generated" }

$findings = @(
    "# Maps v2 Findings",
    "",
    'Generated by `tools/maps/generate-architecture-reference-map`.',
    "",
    "This is a point-in-time report from generated map facts. It is not a constitution compliance verdict.",
    "",
    "## Summary",
    "",
    "- Domains in domain map: $domainSummary",
    "- Source extension catalogs discovered: $extensionSummary",
    "- Source extension catalogs indexed from root: $extensionIndexedSummary",
    "- Discovered source catalogs not linked from root index: $extensionNotIndexedSummary",
    "- Root-indexed catalogs missing on disk: $extensionMissingSummary",
    "- Runtime-to-design direct reference signals: $(@($signals | Where-Object Signal -eq 'runtime-to-design').Count)",
    "- Design-to-runtime direct reference signals: $(@($signals | Where-Object Signal -eq 'design-to-runtime').Count)",
    "- Bridge-like direct reference shapes: $($bridgeRows.Count)",
    "",
    "## Reference Signals",
    ""
)
if ($signals.Count -eq 0) {
    $findings += "No direct design/runtime reference signals were found."
} else {
    foreach ($signal in $signals | Sort-Object Signal, { $_.From.Name }, { $_.To.Name }) {
        $findings += "- $($signal.From.Name) -> $($signal.To.Name) ($($signal.Signal)): $($signal.Review)."
    }
}
$findings += @("", "## Next Map Work", "", "- Use these maps as inputs for constitution verification reports.", "- Keep runtime/design reference signals as review prompts, not automatic violations.", "- Build CShells appsettings generation as a separate work unit after feature identifiers and dependency expectations are pinned.")
Write-Lines -Path (Join-Path $docsReports "maps-v2-findings.md") -Lines $findings

Write-Host "Generated maps:"
Write-Host " - docs/maps/architecture-reference-map.md"
Write-Host " - docs/reports/maps-v2-findings.md"
