#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/../.." && pwd)"
docs_maps="$repo_root/docs/maps"
docs_reports="$repo_root/docs/reports"
mkdir -p "$docs_maps" "$docs_reports"

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

repo_path() {
  local path="$1"
  path="$(cd "$(dirname "$path")" && pwd)/$(basename "$path")"
  printf '%s\n' "${path#$repo_root/}" | sed 's#\\#/#g'
}

escape_cell() {
  local value="${1:-}"
  if [ -z "${value// }" ]; then
    printf '%s' "-"
  else
    printf '%s' "$value" | sed 's/|/\\|/g'
  fi
}

sha256_file() {
  local file="$1"
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$file" | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$file" | awk '{print $1}'
  else
    echo "sha256sum or shasum is required to write docs/maps/manifest.json" >&2
    exit 1
  fi
}

sha256_text() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 | awk '{print $1}'
  else
    echo "sha256sum or shasum is required to write docs/maps/manifest.json" >&2
    exit 1
  fi
}

json_bool_or_null() {
  local value="${1:-}"
  case "$value" in
    true|false|null) printf '%s' "$value" ;;
    *) printf 'null' ;;
  esac
}

json_string_or_null() {
  local value="${1:-}"
  if [ -z "$value" ]; then
    printf 'null'
  else
    printf '"%s"' "$(printf '%s' "$value" | sed 's/\\/\\\\/g; s/"/\\"/g')"
  fi
}

run_git() {
  if command -v git >/dev/null 2>&1; then
    git "$@"
  elif command -v git.exe >/dev/null 2>&1; then
    git.exe "$@"
  else
    return 127
  fi
}

git_head_value() {
  local value head ref ref_file head_file
  if value="$(run_git -C "$repo_root" rev-parse --verify HEAD 2>/dev/null)"; then
    printf '%s' "$value"
    return 0
  fi

  head_file="$repo_root/.git/HEAD"
  if [ ! -f "$head_file" ]; then return 1; fi
  IFS= read -r head < "$head_file" || return 1
  case "$head" in
    "ref: "*)
      ref="${head#ref: }"
      ref_file="$repo_root/.git/$ref"
      if [ -f "$ref_file" ]; then
        IFS= read -r value < "$ref_file" || return 1
        printf '%s' "$value"
        return 0
      fi
      ;;
    *)
      printf '%s' "$head"
      return 0
      ;;
  esac
  return 1
}

domain_group() {
  local project="$1"
  case "$project" in
    Server) printf '%s\n' "Server" ;;
    Test.*) printf '%s\n' "Test" ;;
    Elsa3.*) printf '%s\n' "Elsa3" ;;
    Elsa.*) printf '%s\n' "$project" | awk -F. '{print $1 "." $2}' ;;
    *) printf '%s\n' "Other" ;;
  esac
}

target_framework() {
  local file="$1"
  local value
  value="$(sed -n 's/.*<TargetFramework>\([^<]*\)<\/TargetFramework>.*/\1/p' "$file" | head -n 1)"
  [ -n "$value" ] && printf '%s\n' "$value" || printf '%s\n' "-"
}

is_packable() {
  local file="$1"
  local value
  value="$(sed -n 's/.*<IsPackable>\([^<]*\)<\/IsPackable>.*/\1/p' "$file" | head -n 1)"
  [ -n "$value" ] && printf '%s\n' "$value" || printf '%s\n' "default"
}

project_name_from_include() {
  local include="$1"
  include="${include##*\\}"
  include="${include##*/}"
  printf '%s\n' "${include%.csproj}"
}

project_refs() {
  local file="$1"
  { grep -oE '<ProjectReference[^>]+Include="[^"]+"' "$file" 2>/dev/null || true; } \
    | sed -E 's/.*Include="([^"]+)".*/\1/' \
    | while IFS= read -r include; do project_name_from_include "$include"; done \
    | sort
}

package_refs() {
  local file="$1"
  { grep -oE '<PackageReference[^>]+' "$file" 2>/dev/null || true; } \
    | while IFS= read -r line; do
      local id version
      id="$(printf '%s\n' "$line" | sed -nE 's/.*Include="([^"]+)".*/\1/p')"
      version="$(printf '%s\n' "$line" | sed -nE 's/.*Version="([^"]+)".*/\1/p')"
      [ -z "$version" ] && version="(unspecified)"
      [ -n "$id" ] && printf '%s|%s\n' "$id" "$version"
    done
}

owner_project() {
  local file="$1"
  local dir
  dir="$(dirname "$file")"
  while [ "$dir" != "/" ]; do
    local match
    match="$(find "$dir" -maxdepth 1 -name '*.csproj' -type f | sort | head -n 1)"
    if [ -n "$match" ]; then
      basename "$match" .csproj
      return 0
    fi
    dir="$(dirname "$dir")"
  done
  return 1
}

join_br() {
  awk 'BEGIN{first=1} { if (!first) printf "<br>"; printf "%s", $0; first=0 }'
}

find "$repo_root/src" "$repo_root/tests" -name '*.csproj' -type f 2>/dev/null | sort > "$tmp_dir/projects.txt"

{
  echo "# Project Reference Map"
  echo
  echo 'Generated by `tools/maps/generate-maps`.'
  echo
  echo "Records direct project references only."
  echo
  echo "## Summary"
  echo
  source_count="$(grep -c '/src/' "$tmp_dir/projects.txt" || true)"
  test_count="$(grep -c '/tests/' "$tmp_dir/projects.txt" || true)"
  direct_refs=0
  while IFS= read -r project_file; do
    count="$(project_refs "$project_file" | grep -c . || true)"
    direct_refs=$((direct_refs + count))
  done < "$tmp_dir/projects.txt"
  echo "- Source projects: $source_count"
  echo "- Test projects: $test_count"
  echo "- Direct project references: $direct_refs"
  echo
  echo "## Projects"
  echo
  echo "| Project | Kind | Domain | Target | Packable | Direct project references |"
  echo "|---|---|---|---|---|---|"
  : > "$tmp_dir/domains.tsv"
  while IFS= read -r project_file; do
    name="$(basename "$project_file" .csproj)"
    rel="$(repo_path "$project_file")"
    kind="source"
    case "$rel" in tests/*) kind="test" ;; esac
    domain="$(domain_group "$name")"
    printf '%s\t%s\n' "$domain" "$kind" >> "$tmp_dir/domains.tsv"
    refs="$(project_refs "$project_file" | join_br)"
    [ -z "$refs" ] && refs="-"
    echo "| [$name](../../$rel) | $kind | $domain | $(target_framework "$project_file") | $(is_packable "$project_file") | $(escape_cell "$refs") |"
  done < "$tmp_dir/projects.txt"
  echo
  echo "## Domain Groups"
  echo
  echo "| Domain | Source projects | Test projects |"
  echo "|---|---:|---:|"
  awk -F'\t' '{ domains[$1]=1; counts[$1 "|" $2]++ } END { for (d in domains) print d "|" counts[d "|source"]+0 "|" counts[d "|test"]+0 }' "$tmp_dir/domains.tsv" | sort \
    | while IFS='|' read -r domain source test; do echo "| $domain | $source | $test |"; done
} > "$docs_maps/project-reference-map.md"

: > "$tmp_dir/packages.tsv"
while IFS= read -r project_file; do
  name="$(basename "$project_file" .csproj)"
  rel="$(repo_path "$project_file")"
  kind="source"
  case "$rel" in tests/*) kind="test" ;; esac
  package_refs "$project_file" | while IFS='|' read -r id version; do
    printf '%s\t%s\t%s\t%s\t%s\n' "$id" "$version" "$name" "$rel" "$kind" >> "$tmp_dir/packages.tsv"
  done
done < "$tmp_dir/projects.txt"

{
  echo "# Package Map"
  echo
  echo 'Generated by `tools/maps/generate-maps`.'
  echo
  echo 'Records direct `PackageReference` entries only; it does not compute transitive closure.'
  echo
  echo "## Package Version Clusters"
  echo
  echo "| Package | Versions | Projects |"
  echo "|---|---|---|"
  cut -f1 "$tmp_dir/packages.tsv" | sort -u | while IFS= read -r id; do
    versions="$(awk -F'\t' -v id="$id" '$1==id {print $2}' "$tmp_dir/packages.tsv" | sort -u | join_br)"
    projects="$(awk -F'\t' -v id="$id" '$1==id {print $3 " (" $2 ")"}' "$tmp_dir/packages.tsv" | sort | join_br)"
    echo "| $id | $(escape_cell "$versions") | $(escape_cell "$projects") |"
  done
  echo
  echo "## Direct Package References"
  echo
  echo "| Project | Kind | Package | Version |"
  echo "|---|---|---|---|"
  sort -k3,3 -k1,1 "$tmp_dir/packages.tsv" | while IFS=$'\t' read -r id version project rel kind; do
    echo "| [$project](../../$rel) | $kind | $id | $version |"
  done
} > "$docs_maps/package-map.md"

: > "$tmp_dir/features.tsv"
find "$repo_root/src" -name '*.cs' -type f 2>/dev/null | sort | while IFS= read -r cs_file; do
  { grep -E '^[[:space:]]*public[[:space:]].*class[[:space:]][A-Za-z0-9_]+[[:space:]]*:[^{]*(IShellFeature|FastEndpointsFeatureBase|EFCore.*FeatureBase|FeatureBase)' "$cs_file" 2>/dev/null || true; } \
    | while IFS= read -r line; do
      class="$(printf '%s\n' "$line" | sed -nE 's/.*class[[:space:]]+([A-Za-z0-9_]+).*/\1/p')"
      base="$(printf '%s\n' "$line" | sed -nE 's/.*:[[:space:]]*([^<{]+).*/\1/p' | sed 's/[[:space:]]\+/ /g; s/[[:space:]]*$//')"
      project="$(owner_project "$cs_file" || true)"
      [ -z "$project" ] && continue
      kind="feature-base-derived"
      printf '%s\n' "$base" | grep -Eq '\bIShellFeature\b' && kind="direct IShellFeature"
      printf '%s\n' "$base" | grep -Eq '\bFastEndpointsFeatureBase\b' && kind="FastEndpoints feature"
      printf '%s\n' "$base" | grep -Eq '\bEFCore.*FeatureBase' && kind="EF Core feature base"
      printf '%s\t%s\t%s\t%s\t%s\n' "$class" "$kind" "$project" "$base" "$(repo_path "$cs_file")" >> "$tmp_dir/features.tsv"
    done
done

{
  echo "# Feature Map"
  echo
  echo 'Generated by `tools/maps/generate-maps`.'
  echo
  echo "Discovers public CShells feature classes and feature-base-derived classes by scanning source text."
  echo
  echo "## Summary"
  echo
  echo "- Discovered feature classes: $(grep -c . "$tmp_dir/features.tsv" || true)"
  echo
  echo "## Features"
  echo
  echo "| Feature class | Kind | Project | Base/interface | File |"
  echo "|---|---|---|---|---|"
  sort -k3,3 -k1,1 "$tmp_dir/features.tsv" | while IFS=$'\t' read -r class kind project base rel; do
    echo "| $class | $kind | $project | $(escape_cell "$base") | [$(basename "$rel")](../../$rel) |"
  done
} > "$docs_maps/feature-map.md"

: > "$tmp_dir/testrefs.txt"
grep '/tests/' "$tmp_dir/projects.txt" | while IFS= read -r project_file; do
  project_refs "$project_file" >> "$tmp_dir/testrefs.txt"
done
sort -u "$tmp_dir/testrefs.txt" -o "$tmp_dir/testrefs.txt"

{
  echo "# Test Map"
  echo
  echo 'Generated by `tools/maps/generate-maps`.'
  echo
  echo "Records direct test-project references only; it does not claim behavioral coverage."
  echo
  echo "## Summary"
  echo
  echo "- Test projects: $(grep -c '/tests/' "$tmp_dir/projects.txt" || true)"
  echo "- Source projects directly referenced by at least one test project: $(grep -c . "$tmp_dir/testrefs.txt" || true)"
  no_test_count=0
  while IFS= read -r project_file; do
    name="$(basename "$project_file" .csproj)"
    if ! grep -Fxq "$name" "$tmp_dir/testrefs.txt"; then no_test_count=$((no_test_count + 1)); fi
  done < <(grep '/src/' "$tmp_dir/projects.txt")
  echo "- Source projects not directly referenced by test projects: $no_test_count"
  echo
  echo "## Test Projects"
  echo
  echo "| Test project | Direct production references |"
  echo "|---|---|"
  grep '/tests/' "$tmp_dir/projects.txt" | while IFS= read -r project_file; do
    name="$(basename "$project_file" .csproj)"
    rel="$(repo_path "$project_file")"
    refs="$(project_refs "$project_file" | join_br)"
    [ -z "$refs" ] && refs="-"
    echo "| [$name](../../$rel) | $(escape_cell "$refs") |"
  done
  echo
  echo "## Source Projects Without Direct Test Reference"
  echo
  echo "| Project | Domain |"
  echo "|---|---|"
  grep '/src/' "$tmp_dir/projects.txt" | while IFS= read -r project_file; do
    name="$(basename "$project_file" .csproj)"
    if ! grep -Fxq "$name" "$tmp_dir/testrefs.txt"; then
      echo "| [$name](../../$(repo_path "$project_file")) | $(domain_group "$name") |"
    fi
  done
} > "$docs_maps/test-map.md"

: > "$tmp_dir/specs.tsv"
find "$repo_root/specs" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | sort | while IFS= read -r spec_dir; do
  id="$(basename "$spec_dir")"
  title="$id"
  status="unknown"
  notes=""
  spec_file="$spec_dir/spec.md"
  plan_file="$spec_dir/plan.md"
  tasks_file="$spec_dir/tasks.md"
  if [ -f "$spec_file" ]; then
    title_line="$(grep -m1 '^# Feature Specification:' "$spec_file" || true)"
    [ -n "$title_line" ] && title="${title_line#*: }"
    status_line="$(grep -m1 '^\*\*Status\*\*:' "$spec_file" || true)"
    [ -n "$status_line" ] && status="${status_line#**Status**: }"
    lower="$(tr '[:upper:]' '[:lower:]' < "$spec_file")"
    for keyword in "superseded" "retained" "deferred" "out of scope" "construct-only"; do
      if printf '%s\n' "$lower" | grep -q "$keyword"; then
        [ -n "$notes" ] && notes="$notes, "
        notes="$notes$keyword"
      fi
    done
  fi
  [ -z "$notes" ] && notes="-"
  verdict="-"
  if [ -f "$plan_file" ]; then
    verdict_line="$(grep -m1 -E '(Initial )?Constitution Check verdict:' "$plan_file" || true)"
    [ -n "$verdict_line" ] && verdict="$(printf '%s\n' "$verdict_line" | sed -E 's/.*Constitution Check verdict:[[:space:]]*//')"
  fi
  done_count=0
  open_count=0
  if [ -f "$tasks_file" ]; then
    done_count="$(grep -cE '^[[:space:]]*-[[:space:]]+\[[xX]\][[:space:]]+T[0-9]+' "$tasks_file" || true)"
    open_count="$(grep -cE '^[[:space:]]*-[[:space:]]+\[[[:space:]]\][[:space:]]+T[0-9]+' "$tasks_file" || true)"
  fi
  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$id" "$title" "$status" "$verdict" "$done_count" "$open_count" "$notes" >> "$tmp_dir/specs.tsv"
done

{
  echo "# Spec Status Map"
  echo
  echo 'Generated by `tools/maps/generate-maps`.'
  echo
  echo 'Reads current `specs/*` folders and task checkboxes. Status clues are textual, not authoritative workflow state.'
  echo
  echo "## Specs"
  echo
  echo "| Spec | Title | Status | Plan verdict | Tasks done | Tasks open | Notes |"
  echo "|---|---|---|---|---:|---:|---|"
  while IFS=$'\t' read -r id title status verdict done_count open_count notes; do
    echo "| [$id](../../specs/$id/spec.md) | $(escape_cell "$title") | $(escape_cell "$status") | $(escape_cell "$verdict") | $done_count | $open_count | $(escape_cell "$notes") |"
  done < "$tmp_dir/specs.tsv"
} > "$docs_maps/spec-status-map.md"

{
  source_count="$(grep -c '/src/' "$tmp_dir/projects.txt" || true)"
  test_count="$(grep -c '/tests/' "$tmp_dir/projects.txt" || true)"
  feature_count="$(grep -c . "$tmp_dir/features.tsv" || true)"
  spec_count="$(grep -c . "$tmp_dir/specs.tsv" || true)"
  multi_version_count="$(awk -F'\t' '{ versions[$1][$2]=1 } END { count=0; for (id in versions) { n=0; for (v in versions[id]) n++; if (n>1) count++ } print count+0 }' "$tmp_dir/packages.tsv" 2>/dev/null || echo 0)"
  echo "# Maps v1 Findings"
  echo
  echo 'Generated by `tools/maps/generate-maps`.'
  echo
  echo "This is a point-in-time report from direct repo facts. It is not a constitution compliance verdict."
  echo
  echo "## Summary"
  echo
  echo "- Source projects: $source_count"
  echo "- Test projects: $test_count"
  echo "- Discovered CShells feature classes: $feature_count"
  echo "- Specs: $spec_count"
  echo "- Direct package IDs with multiple versions: $multi_version_count"
  echo
  echo "## Package Version Clusters"
  echo
  if [ "$multi_version_count" = "0" ]; then
    echo "No direct package ID has multiple direct versions."
  else
    echo "| Package | Versions | Projects |"
    echo "|---|---|---|"
    cut -f1 "$tmp_dir/packages.tsv" | sort -u | while IFS= read -r id; do
      version_count="$(awk -F'\t' -v id="$id" '$1==id {print $2}' "$tmp_dir/packages.tsv" | sort -u | grep -c . || true)"
      if [ "$version_count" -gt 1 ]; then
        versions="$(awk -F'\t' -v id="$id" '$1==id {print $2}' "$tmp_dir/packages.tsv" | sort -u | join_br)"
        projects="$(awk -F'\t' -v id="$id" '$1==id {print $3 " (" $2 ")"}' "$tmp_dir/packages.tsv" | sort | join_br)"
        echo "| $id | $(escape_cell "$versions") | $(escape_cell "$projects") |"
      fi
    done
  fi
  echo
  echo "## Test Visibility"
  echo
  echo "- Source projects without a direct test-project reference: $no_test_count"
  echo "- This is only a visibility signal; tests may cover behavior indirectly through higher-level projects."
  echo
  echo "## Spec 006 State"
  echo
  spec006="$(grep '^006-activity-construction-seam	' "$tmp_dir/specs.tsv" || true)"
  if [ -n "$spec006" ]; then
    IFS=$'\t' read -r _id _title _status _verdict done_count open_count notes <<< "$spec006"
    echo "- \`006-activity-construction-seam\`: $done_count tasks done, $open_count tasks open; notes: $notes."
  else
    echo "- Spec 006 was not found."
  fi
  echo
  echo "## Runtime/Design Reference Signal"
  echo
  runtime_refs=""
  while IFS= read -r project_file; do
    name="$(basename "$project_file" .csproj)"
    case "$name" in
      *Runtime*|Elsa.Activities.Primitives|Elsa.Activities.Composition.Runtime)
        refs="$(project_refs "$project_file" | grep 'Design' || true)"
        if [ -n "$refs" ]; then
          while IFS= read -r ref; do runtime_refs="${runtime_refs}- $name -> $ref"$'\n'; done <<< "$refs"
        fi
        ;;
    esac
  done < <(grep '/src/' "$tmp_dir/projects.txt")
  if [ -z "$runtime_refs" ]; then
    echo 'No direct runtime-path project reference to an `Elsa.*Design*` project was found by the Maps v1 heuristic.'
  else
    printf '%s' "$runtime_refs" | sort
  fi
  echo
  echo "## Next Map Work"
  echo
  echo "- Add feature dependency/activation IDs from CShells configuration."
  echo "- Add constitution-specific verification reports that consume these maps."
  echo "- Add richer test maturity classification beyond direct project references."
} > "$docs_reports/maps-v1-findings.md"

{
  find "$repo_root/src" -type f \( -name '*.csproj' -o -name '*.cs' \) 2>/dev/null
  find "$repo_root/tests" -type f -name '*.csproj' 2>/dev/null
  find "$repo_root/specs" -type f -name '*.md' 2>/dev/null
  printf '%s\n' "$repo_root/tools/maps/generate-maps.ps1"
  printf '%s\n' "$repo_root/tools/maps/generate-maps.sh"
  printf '%s\n' "$repo_root/tools/maps/generate-domain-map.ps1"
  printf '%s\n' "$repo_root/tools/maps/generate-domain-map.sh"
  printf '%s\n' "$repo_root/tools/maps/generate-extension-point-map.ps1"
  printf '%s\n' "$repo_root/tools/maps/generate-extension-point-map.sh"
  printf '%s\n' "$repo_root/tools/maps/generate-architecture-reference-map.ps1"
  printf '%s\n' "$repo_root/tools/maps/generate-architecture-reference-map.sh"
} | sort -u > "$tmp_dir/input-files.txt"

: > "$tmp_dir/input-hashes.txt"
while IFS= read -r input_file; do
  [ -f "$input_file" ] || continue
  printf '%s=%s\n' "$(repo_path "$input_file")" "$(sha256_file "$input_file")" >> "$tmp_dir/input-hashes.txt"
done < "$tmp_dir/input-files.txt"

input_fingerprint="$(sha256_text < "$tmp_dir/input-hashes.txt")"
input_file_count="$(grep -c . "$tmp_dir/input-hashes.txt" || true)"
git_head="null"
if git_head_raw="$(git_head_value)"; then
  git_head="$(json_string_or_null "$git_head_raw")"
fi
dirty="null"
if git_status_raw="$(run_git -C "$repo_root" status --porcelain -- src tests specs tools/maps 2>/dev/null)"; then
  if [ -n "$git_status_raw" ]; then dirty="true"; else dirty="false"; fi
elif [ "$git_head" != "null" ]; then
  dirty="true"
fi

direct_project_references=0
while IFS= read -r project_file; do
  count="$(project_refs "$project_file" | grep -c . || true)"
  direct_project_references=$((direct_project_references + count))
done < "$tmp_dir/projects.txt"
direct_package_references="$(grep -c . "$tmp_dir/packages.tsv" || true)"

cat > "$docs_maps/manifest.json" <<EOF
{
  "schema_version": "1.0",
  "generator": "tools/maps/generate-maps",
  "freshness_rule": "Maps are fresh when input_fingerprint matches the current inputs. git_head is advisory because generated maps may be committed with their inputs.",
  "git_head": $git_head,
  "relevant_inputs_dirty": $(json_bool_or_null "$dirty"),
  "input_fingerprint": "$input_fingerprint",
  "input_file_count": $input_file_count,
  "counts": {
    "source_projects": $source_count,
    "test_projects": $test_count,
    "direct_project_references": $direct_project_references,
    "direct_package_references": $direct_package_references,
    "feature_classes": $feature_count,
    "specs": $spec_count
  },
  "generated_files": [
    "docs/maps/project-reference-map.md",
    "docs/maps/package-map.md",
    "docs/maps/feature-map.md",
    "docs/maps/test-map.md",
    "docs/maps/spec-status-map.md",
    "docs/maps/domain-map.md",
    "docs/maps/extension-point-map.md",
    "docs/maps/architecture-reference-map.md",
    "docs/reports/maps-v2-findings.md",
    "docs/reports/maps-v1-findings.md"
  ]
}
EOF

echo "Generated maps:"
echo " - docs/maps/project-reference-map.md"
echo " - docs/maps/package-map.md"
echo " - docs/maps/feature-map.md"
echo " - docs/maps/test-map.md"
echo " - docs/maps/spec-status-map.md"
echo " - docs/reports/maps-v1-findings.md"
echo " - docs/maps/manifest.json"
