#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/../.." && pwd)"
docs_maps="$repo_root/docs/maps"
tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT
mkdir -p "$docs_maps"

repo_path() {
  local path="$1"
  path="$(cd "$(dirname "$path")" && pwd)/$(basename "$path")"
  printf '%s\n' "${path#$repo_root/}" | sed 's#\\#/#g'
}

escape_cell() {
  local value="${1:-}"
  if [ -z "${value// }" ]; then printf '%s' "-"; else printf '%s' "$value" | sed 's/|/\\|/g'; fi
}

domain_group() {
  local project="$1"
  case "$project" in
    Elsa3.*) printf '%s\n' "Elsa3" ;;
    Elsa.*) printf '%s\n' "$project" | awk -F. '{print $1 "." $2}' ;;
    *) printf '%s\n' "Other" ;;
  esac
}

owner_project() {
  local file="$1" dir match
  dir="$(dirname "$file")"
  while [ "$dir" != "/" ]; do
    match="$(find "$dir" -maxdepth 1 -name '*.csproj' -type f | sort | head -n 1)"
    if [ -n "$match" ]; then basename "$match" .csproj; return 0; fi
    dir="$(dirname "$dir")"
  done
  printf '%s\n' "-"
}

join_br() {
  awk 'BEGIN{first=1}{if(!first)printf "<br>"; printf "%s",$0; first=0}'
}

root_index="$repo_root/EXTENSION_POINTS.md"
: > "$tmp_dir/catalogs.txt"
[ -f "$root_index" ] && printf '%s\n' "$root_index" >> "$tmp_dir/catalogs.txt"
find "$repo_root/src" -name 'EXTENSION_POINTS.md' -type f 2>/dev/null | sort >> "$tmp_dir/catalogs.txt"
sort -u "$tmp_dir/catalogs.txt" -o "$tmp_dir/catalogs.txt"

: > "$tmp_dir/indexed.txt"
if [ -f "$root_index" ]; then
  grep -oE '\]\(src/[^)]+/EXTENSION_POINTS\.md\)' "$root_index" | sed -E 's/.*\((src\/.*)\)/\1/' | sort -u > "$tmp_dir/indexed.txt" || true
fi

: > "$tmp_dir/catalogs.tsv"
while IFS= read -r file; do
  rel="$(repo_path "$file")"
  project="$(owner_project "$file")"
  domain="repo root"
  [ "$project" != "-" ] && domain="$(domain_group "$project")"
  sections="$({ grep -E '^## ' "$file" 2>/dev/null || true; } | sed 's/^## //' | { grep -Ev '^(Cross-references|Constitutional basis)$' || true; } | join_br)"
  points="$({ grep -E '^### ' "$file" 2>/dev/null || true; } | sed 's/^### //' | join_br)"
  kinds="$({ grep -E '^- \*\*Kind:\*\*' "$file" 2>/dev/null || true; } | sed 's/^- \*\*Kind:\*\* //' | join_br)"
  known="$(grep -cE '^\*\*Known implementations' "$file" 2>/dev/null || true)"
  root_indexed="no"
  [ "$rel" = "EXTENSION_POINTS.md" ] && root_indexed="root"
  grep -Fxq "$rel" "$tmp_dir/indexed.txt" 2>/dev/null && root_indexed="yes"
  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$rel" "$project" "$domain" "$sections" "$points" "$kinds" "$known" "$root_indexed" >> "$tmp_dir/catalogs.tsv"
done < "$tmp_dir/catalogs.txt"

awk -F'\t' '$1 ~ /^src\// {print $1}' "$tmp_dir/catalogs.tsv" | sort -u > "$tmp_dir/discovered-src.txt"
comm -23 "$tmp_dir/discovered-src.txt" "$tmp_dir/indexed.txt" > "$tmp_dir/not-indexed.txt" || true
comm -13 "$tmp_dir/discovered-src.txt" "$tmp_dir/indexed.txt" > "$tmp_dir/missing.txt" || true

{
  echo "# Extension-Point Map"
  echo
  echo 'Generated by `tools/maps/generate-extension-point-map`.'
  echo
  echo 'Records Markdown catalog facts from `EXTENSION_POINTS.md` files. It does not validate catalog completeness.'
  echo
  echo "## Summary"
  echo
  echo "- Catalog files discovered: $(grep -c . "$tmp_dir/catalogs.tsv" || true)"
  echo "- Source catalogs discovered: $(grep -c . "$tmp_dir/discovered-src.txt" || true)"
  echo "- Source catalogs indexed from root: $(grep -c . "$tmp_dir/indexed.txt" || true)"
  echo "- Discovered source catalogs not linked from root index: $(grep -c . "$tmp_dir/not-indexed.txt" || true)"
  echo "- Root-indexed catalogs missing on disk: $(grep -c . "$tmp_dir/missing.txt" || true)"
  echo
  echo "## Catalogs"
  echo
  echo "| Catalog | Owner project | Domain | Sections | Extension-point headings | Kind lines | Known implementation blocks | Root indexed |"
  echo "|---|---|---|---|---|---|---:|---|"
  while IFS=$'\t' read -r rel project domain sections points kinds known root_indexed; do
    echo "| [$rel](../../$rel) | $project | $domain | $(escape_cell "$sections") | $(escape_cell "$points") | $(escape_cell "$kinds") | $known | $root_indexed |"
  done < "$tmp_dir/catalogs.tsv"
  echo
  echo "## Root Index Coverage"
  echo
  echo "| Status | Catalog |"
  echo "|---|---|"
  if [ ! -s "$tmp_dir/not-indexed.txt" ] && [ ! -s "$tmp_dir/missing.txt" ]; then
    echo "| ok | Root index and discovered source catalogs match. |"
  else
    while IFS= read -r rel; do echo "| discovered but not root-indexed | [$rel](../../$rel) |"; done < "$tmp_dir/not-indexed.txt"
    while IFS= read -r rel; do echo "| root-indexed but missing on disk | $rel |"; done < "$tmp_dir/missing.txt"
  fi
} > "$docs_maps/extension-point-map.md"

echo "Generated maps:"
echo " - docs/maps/extension-point-map.md"
