#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/../.." && pwd)"
docs_maps="$repo_root/docs/maps"
tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT
mkdir -p "$docs_maps"

repo_path() {
  local path="$1"
  path="$(cd "$(dirname "$path")" && pwd)/$(basename "$path")"
  printf '%s\n' "${path#$repo_root/}" | sed 's#\\#/#g'
}

escape_cell() {
  local value="${1:-}"
  if [ -z "${value// }" ]; then printf '%s' "-"; else printf '%s' "$value" | sed 's/|/\\|/g'; fi
}

run_git() {
  if command -v git >/dev/null 2>&1; then
    git "$@"
  elif command -v git.exe >/dev/null 2>&1; then
    git.exe "$@"
  else
    return 127
  fi
}

# Enumerate repo files via git so .gitignore is respected and paths use the
# git-tracked casing; a raw filesystem walk picks up machine-local scratch
# files and on-disk casing, which churns the committed maps.
list_repo_files() {
  local listing
  if ! listing="$(run_git -C "$repo_root" ls-files --cached --others --exclude-standard -- "$@")"; then
    echo "git ls-files failed; map generation requires a git checkout" >&2
    return 1
  fi
  while IFS= read -r rel_file; do
    [ -n "$rel_file" ] || continue
    [ -f "$repo_root/$rel_file" ] || continue
    printf '%s/%s\n' "$repo_root" "$rel_file"
  done <<< "$listing"
}

project_name_from_include() {
  local include="$1"
  include="${include##*\\}"
  include="${include##*/}"
  printf '%s\n' "${include%.csproj}"
}

project_refs() {
  local file="$1"
  { grep -oE '<ProjectReference[^>]+Include="[^"]+"' "$file" 2>/dev/null || true; } \
    | sed -E 's/.*Include="([^"]+)".*/\1/' \
    | while IFS= read -r include; do project_name_from_include "$include"; done \
    | sort -u
}

domain_group() {
  local project="$1"
  case "$project" in
    Elsa.Server) printf '%s\n' "Elsa.Server" ;;
    Server) printf '%s\n' "Elsa.Server" ;;
    Test.*) printf '%s\n' "Test" ;;
    Elsa3.*) printf '%s\n' "Elsa3" ;;
    Elsa.*) printf '%s\n' "$project" | awk -F. '{print $1 "." $2}' ;;
    *) printf '%s\n' "Other" ;;
  esac
}

sub_domain() {
  local project="$1" domain="$2" tail
  case "$domain" in Elsa.Server|Test|Elsa3|Other) printf '%s\n' "-" ; return ;; esac
  tail="${project#$domain}"
  tail="${tail#.}"
  [ -n "$tail" ] && printf '%s\n' "$tail" || printf '%s\n' "(root)"
}

project_role() {
  local project="$1" kind="$2"
  if [ "$kind" = "test" ]; then printf '%s\n' "test"; return; fi
  if [ "$project" = "Elsa.Server" ] || [ "$project" = "Server" ]; then printf '%s\n' "host"; return; fi
  case "$project" in
    *.Core) printf '%s\n' "contract" ;;
    *.Strategies|*.Schedules|*.Libraries) printf '%s\n' "helper" ;;
    *.Sqlite|*.EFCore|*.FileSystem|*.Jint|*.Liquid) printf '%s\n' "provider/implementation" ;;
    *) printf '%s\n' "feature/implementation" ;;
  esac
}

list_repo_files 'src/*.csproj' 'tests/*.csproj' | sort > "$tmp_dir/projects.txt"
: > "$tmp_dir/projects.tsv"
: > "$tmp_dir/refs.tsv"

while IFS= read -r project_file; do
  name="$(basename "$project_file" .csproj)"
  rel="$(repo_path "$project_file")"
  kind="source"; case "$rel" in tests/*) kind="test" ;; esac
  domain="$(domain_group "$name")"
  sub="$(sub_domain "$name" "$domain")"
  role="$(project_role "$name" "$kind")"
  printf '%s\t%s\t%s\t%s\t%s\t%s\n' "$name" "$rel" "$kind" "$domain" "$sub" "$role" >> "$tmp_dir/projects.tsv"
  project_refs "$project_file" | while IFS= read -r ref; do printf '%s\t%s\n' "$name" "$ref" >> "$tmp_dir/refs.tsv"; done
done < "$tmp_dir/projects.txt"

cross_count="$(awk -F'\t' 'NR==FNR {d[$1]=$4; next} ($2 in d) && d[$1] != d[$2] {c++} END{print c+0}' "$tmp_dir/projects.tsv" "$tmp_dir/refs.tsv")"

{
  echo "# Domain Map"
  echo
  echo 'Generated by `tools/maps/generate-domain-map`.'
  echo
  echo "Records project grouping and direct reference facts only. Roles are heuristic navigation labels, not constitution verdicts."
  echo
  echo "## Summary"
  echo
  echo "- Source projects: $(awk -F'\t' '$3=="source"{c++} END{print c+0}' "$tmp_dir/projects.tsv")"
  echo "- Test projects: $(awk -F'\t' '$3=="test"{c++} END{print c+0}' "$tmp_dir/projects.tsv")"
  echo "- Domains: $(cut -f4 "$tmp_dir/projects.tsv" | sort -u | grep -c . || true)"
  echo "- Direct cross-domain references: $cross_count"
  echo
  echo "## Domains"
  echo
  echo "| Domain | Source projects | Test projects | Roles |"
  echo "|---|---:|---:|---|"
  cut -f4 "$tmp_dir/projects.tsv" | sort -u | while IFS= read -r domain; do
    source_count="$(awk -F'\t' -v d="$domain" '$4==d && $3=="source"{c++} END{print c+0}' "$tmp_dir/projects.tsv")"
    test_count="$(awk -F'\t' -v d="$domain" '$4==d && $3=="test"{c++} END{print c+0}' "$tmp_dir/projects.tsv")"
    roles="$(awk -F'\t' -v d="$domain" '$4==d{print $6}' "$tmp_dir/projects.tsv" | sort -u | awk 'BEGIN{first=1}{if(!first)printf "<br>"; printf "%s",$0; first=0}')"
    echo "| $domain | $source_count | $test_count | $(escape_cell "$roles") |"
  done
  echo
  echo "## Projects"
  echo
  echo "| Project | Kind | Domain | Sub-domain | Role | Direct references |"
  echo "|---|---|---|---|---|---|"
  while IFS=$'\t' read -r name rel kind domain sub role; do
    refs="$(awk -F'\t' -v n="$name" '$1==n{print $2}' "$tmp_dir/refs.tsv" | sort -u | awk 'BEGIN{first=1}{if(!first)printf "<br>"; printf "%s",$0; first=0}')"
    [ -z "$refs" ] && refs="-"
    echo "| [$name](../../$rel) | $kind | $domain | $(escape_cell "$sub") | $role | $(escape_cell "$refs") |"
  done < "$tmp_dir/projects.tsv"
  echo
  echo "## Direct Cross-Domain References"
  echo
  echo "| From | From domain | To | To domain |"
  echo "|---|---|---|---|"
  awk -F'\t' 'NR==FNR {rel[$1]=$2; dom[$1]=$4; next} ($2 in dom) && dom[$1] != dom[$2] {print $1 "\t" rel[$1] "\t" dom[$1] "\t" $2 "\t" rel[$2] "\t" dom[$2]}' "$tmp_dir/projects.tsv" "$tmp_dir/refs.tsv" \
    | sort | while IFS=$'\t' read -r from from_rel from_domain to to_rel to_domain; do
      echo "| [$from](../../$from_rel) | $from_domain | [$to](../../$to_rel) | $to_domain |"
    done
} > "$docs_maps/domain-map.md"

echo "Generated maps:"
echo " - docs/maps/domain-map.md"
