#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/../.." && pwd)"
docs_maps="$repo_root/docs/maps"
docs_reports="$repo_root/docs/reports"
tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT
mkdir -p "$docs_maps" "$docs_reports"

repo_path() {
  local path="$1"
  path="$(cd "$(dirname "$path")" && pwd)/$(basename "$path")"
  printf '%s\n' "${path#$repo_root/}" | sed 's#\\#/#g'
}

escape_cell() {
  local value="${1:-}"
  if [ -z "${value// }" ]; then printf '%s' "-"; else printf '%s' "$value" | sed 's/|/\\|/g'; fi
}

project_name_from_include() {
  local include="$1"
  include="${include##*\\}"
  include="${include##*/}"
  printf '%s\n' "${include%.csproj}"
}

project_refs() {
  local file="$1"
  { grep -oE '<ProjectReference[^>]+Include="[^"]+"' "$file" 2>/dev/null || true; } \
    | sed -E 's/.*Include="([^"]+)".*/\1/' \
    | while IFS= read -r include; do project_name_from_include "$include"; done \
    | sort -u
}

phase() {
  local project="$1"
  case "$project" in
    *.Design|*.Design.*) printf '%s\n' "design" ;;
    *.Runtime|*.Runtime.*) printf '%s\n' "runtime" ;;
    *.Publishing|*.Publishing.*) printf '%s\n' "bridge-like" ;;
    *) printf '%s\n' "neutral" ;;
  esac
}

find "$repo_root/src" "$repo_root/tests" -name '*.csproj' -type f 2>/dev/null | sort > "$tmp_dir/projects.txt"
: > "$tmp_dir/projects.tsv"
: > "$tmp_dir/refs.tsv"
while IFS= read -r project_file; do
  name="$(basename "$project_file" .csproj)"
  rel="$(repo_path "$project_file")"
  kind="source"; case "$rel" in tests/*) kind="test" ;; esac
  ph="$(phase "$name")"
  printf '%s\t%s\t%s\t%s\n' "$name" "$rel" "$kind" "$ph" >> "$tmp_dir/projects.tsv"
  project_refs "$project_file" | while IFS= read -r ref; do printf '%s\t%s\n' "$name" "$ref" >> "$tmp_dir/refs.tsv"; done
done < "$tmp_dir/projects.txt"

awk -F'\t' 'NR==FNR {rel[$1]=$2; kind[$1]=$3; ph[$1]=$4; next} ($1 in ph) && ($2 in ph) && kind[$1]=="source" {
  if (ph[$1]=="runtime" && ph[$2]=="design") print "runtime-to-design\t" $1 "\t" rel[$1] "\t" $2 "\t" rel[$2] "\treview signal";
  else if (ph[$1]=="design" && ph[$2]=="runtime") print "design-to-runtime\t" $1 "\t" rel[$1] "\t" $2 "\t" rel[$2] "\texpected in some design/read/publish paths; review context";
}' "$tmp_dir/projects.tsv" "$tmp_dir/refs.tsv" | sort > "$tmp_dir/signals.tsv"

awk -F'\t' 'NR==FNR {rel[$1]=$2; kind[$1]=$3; ph[$1]=$4; next} ($1 in ph) && ($2 in ph) && kind[$1]=="source" {
  if (ph[$2]=="design") design[$1]=design[$1] ? design[$1] "<br>" $2 : $2;
  if (ph[$2]=="runtime") runtime[$1]=runtime[$1] ? runtime[$1] "<br>" $2 : $2;
  paths[$1]=rel[$1];
} END { for (p in paths) if (design[p] && runtime[p]) print p "\t" paths[p] "\t" design[p] "\t" runtime[p]; }' "$tmp_dir/projects.tsv" "$tmp_dir/refs.tsv" | sort > "$tmp_dir/bridges.tsv"

{
  echo "# Architecture Reference Map"
  echo
  echo 'Generated by `tools/maps/generate-architecture-reference-map`.'
  echo
  echo "Records direct project-reference signals only. A signal is a review prompt, not an automatic constitution violation."
  echo
  echo "## Summary"
  echo
  echo "- Runtime-to-design direct reference signals: $(awk -F'\t' '$1=="runtime-to-design"{c++} END{print c+0}' "$tmp_dir/signals.tsv")"
  echo "- Design-to-runtime direct reference signals: $(awk -F'\t' '$1=="design-to-runtime"{c++} END{print c+0}' "$tmp_dir/signals.tsv")"
  echo "- Projects directly referencing both design and runtime projects: $(grep -c . "$tmp_dir/bridges.tsv" || true)"
  echo
  echo "## Direct Design/Runtime Signals"
  echo
  echo "| Signal | From | To | Review note |"
  echo "|---|---|---|---|"
  if [ -s "$tmp_dir/signals.tsv" ]; then
    while IFS=$'\t' read -r signal from from_rel to to_rel note; do
      echo "| $signal | [$from](../../$from_rel) | [$to](../../$to_rel) | $note |"
    done < "$tmp_dir/signals.tsv"
  else
    echo "| ok | - | - | No direct design/runtime reference signals found. |"
  fi
  echo
  echo "## Bridge-Like Direct Reference Shape"
  echo
  echo "| Project | Design references | Runtime references |"
  echo "|---|---|---|"
  if [ -s "$tmp_dir/bridges.tsv" ]; then
    while IFS=$'\t' read -r project rel design runtime; do
      echo "| [$project](../../$rel) | $(escape_cell "$design") | $(escape_cell "$runtime") |"
    done < "$tmp_dir/bridges.tsv"
  else
    echo "| - | - | - |"
  fi
} > "$docs_maps/architecture-reference-map.md"

domain_summary="not generated"
if [ -f "$docs_maps/domain-map.md" ]; then
  domain_summary="$(grep -m1 '^- Domains:' "$docs_maps/domain-map.md" | sed 's/^- Domains: //' || true)"
  [ -z "$domain_summary" ] && domain_summary="unknown"
fi
extension_summary="not generated"
extension_indexed_summary="not generated"
extension_not_indexed_summary="not generated"
extension_missing_summary="not generated"
if [ -f "$docs_maps/extension-point-map.md" ]; then
  extension_summary="$(grep -m1 '^- Source catalogs discovered:' "$docs_maps/extension-point-map.md" | sed 's/^- Source catalogs discovered: //' || true)"
  [ -z "$extension_summary" ] && extension_summary="unknown"
  extension_indexed_summary="$(grep -m1 '^- Source catalogs indexed from root:' "$docs_maps/extension-point-map.md" | sed 's/^- Source catalogs indexed from root: //' || true)"
  [ -z "$extension_indexed_summary" ] && extension_indexed_summary="unknown"
  extension_not_indexed_summary="$(grep -m1 '^- Discovered source catalogs not linked from root index:' "$docs_maps/extension-point-map.md" | sed 's/^- Discovered source catalogs not linked from root index: //' || true)"
  [ -z "$extension_not_indexed_summary" ] && extension_not_indexed_summary="unknown"
  extension_missing_summary="$(grep -m1 '^- Root-indexed catalogs missing on disk:' "$docs_maps/extension-point-map.md" | sed 's/^- Root-indexed catalogs missing on disk: //' || true)"
  [ -z "$extension_missing_summary" ] && extension_missing_summary="unknown"
fi

{
  echo "# Maps v2 Findings"
  echo
  echo 'Generated by `tools/maps/generate-architecture-reference-map`.'
  echo
  echo "This is a point-in-time report from generated map facts. It is not a constitution compliance verdict."
  echo
  echo "## Summary"
  echo
  echo "- Domains in domain map: $domain_summary"
  echo "- Source extension catalogs discovered: $extension_summary"
  echo "- Source extension catalogs indexed from root: $extension_indexed_summary"
  echo "- Discovered source catalogs not linked from root index: $extension_not_indexed_summary"
  echo "- Root-indexed catalogs missing on disk: $extension_missing_summary"
  echo "- Runtime-to-design direct reference signals: $(awk -F'\t' '$1=="runtime-to-design"{c++} END{print c+0}' "$tmp_dir/signals.tsv")"
  echo "- Design-to-runtime direct reference signals: $(awk -F'\t' '$1=="design-to-runtime"{c++} END{print c+0}' "$tmp_dir/signals.tsv")"
  echo "- Bridge-like direct reference shapes: $(grep -c . "$tmp_dir/bridges.tsv" || true)"
  echo
  echo "## Reference Signals"
  echo
  if [ -s "$tmp_dir/signals.tsv" ]; then
    while IFS=$'\t' read -r signal from _from_rel to _to_rel note; do
      echo "- $from -> $to ($signal): $note."
    done < "$tmp_dir/signals.tsv"
  else
    echo "No direct design/runtime reference signals were found."
  fi
  echo
  echo "## Next Map Work"
  echo
  echo "- Use these maps as inputs for constitution verification reports."
  echo "- Keep runtime/design reference signals as review prompts, not automatic violations."
  echo "- Build CShells appsettings generation as a separate work unit after feature identifiers and dependency expectations are pinned."
} > "$docs_reports/maps-v2-findings.md"

echo "Generated maps:"
echo " - docs/maps/architecture-reference-map.md"
echo " - docs/reports/maps-v2-findings.md"
