<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="CShells" />
    <PackageReference Include="Elsa.Platform.PackageManifests" />
    <PackageReference Include="Nuplane.Admin" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Elsa.Modularity.Core.csproj" />
  </ItemGroup>

</Project>
