// <auto-generated />
using Elsa.Workflows.Runtime.Distributed.Persistence.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elsa.Workflows.Runtime.Distributed.Persistence.EntityFrameworkCore.Migrations.ExecutionPlacement.SqlServer
{
    [DbContext(typeof(ExecutionPlacementSqlServerDbContext))]
    [Migration("20260915205134_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            // SqlServerModelBuilderExtensions.UseIdentityColumns omitted: the module stays provider-free.

            modelBuilder.Entity("Elsa.Workflows.Runtime.Distributed.Persistence.EntityFrameworkCore.Entities.ExecutionPlacementLeaseEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AcquiredAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpiresAtOffsetMinutes")
                        .HasColumnType("int");

                    b.Property<long>("ExpiresAtUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("bit");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("OwnerIdHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("PlacementToken")
                        .HasColumnType("bigint");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScopeKeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("WorkflowExecutionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("WorkflowExecutionIdOrderKey")
                        .IsRequired()
                        .HasMaxLength(258)
                        .HasColumnType("varbinary(258)");

                    b.HasKey("Id");

                    b.HasIndex("ScopeKeyHash", "OwnerIdHash", "IsReleased", "ExpiresAtUtcTicks", "WorkflowExecutionIdOrderKey");

                    b.ToTable("elsa_distributed_execution_placement", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
