<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Elsa.Versioning.Publisher</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Elsa.Versioning.Calculator\Elsa.Versioning.Calculator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Elsa.Versioning.Publisher.Tests" />
  </ItemGroup>

</Project>
