// <auto-generated />
using System;
using Elsa.Workflows.Design.Persistence.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elsa.Workflows.Design.Persistence.EntityFrameworkCore.Migrations.WorkflowsDesign.PostgreSql
{
    [DbContext(typeof(WorkflowsDesignPostgreSqlDbContext))]
    partial class WorkflowsDesignPostgreSqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            // NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns omitted: the module stays provider-free.

            modelBuilder.Entity("Elsa.Workflows.Design.Persistence.Core.Entities.WorkflowDefinition", b =>
                {
                    b.Property<string>("ScopeKey")
                        .HasMaxLength(65)
                        .HasColumnType("character varying(65)")
                        .UseCollation("C");

                    b.Property<string>("IdLookupHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .UseCollation("C");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedReason")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .UseCollation("C");

                    b.Property<string>("DescriptionSearchKey")
                        .HasMaxLength(1792)
                        .HasColumnType("character varying(1792)")
                        .UseCollation("C");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .UseCollation("C");

                    b.Property<string>("IdSearchKey")
                        .IsRequired()
                        .HasMaxLength(896)
                        .HasColumnType("character varying(896)")
                        .UseCollation("C");

                    b.Property<bool>("IsSourceOwned")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .UseCollation("C");

                    b.Property<string>("NameSearchKey")
                        .HasMaxLength(1792)
                        .HasColumnType("character varying(1792)")
                        .UseCollation("C");

                    b.Property<string>("TenantId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .UseCollation("C");

                    b.HasKey("ScopeKey", "IdLookupHash");

                    b.HasIndex("ScopeKey", "Id");

                    b.HasIndex("ScopeKey", "Name", "Id");

                    b.ToTable("elsa_workflow_definitions_v2", (string)null);
                });

            modelBuilder.Entity("Elsa.Workflows.Design.Persistence.Core.Entities.WorkflowDefinitionDraft", b =>
                {
                    b.Property<string>("ScopeKey")
                        .HasMaxLength(65)
                        .HasColumnType("character varying(65)")
                        .UseCollation("C");

                    b.Property<string>("IdLookupHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .UseCollation("C");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .UseCollation("C");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceVersionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .UseCollation("C");

                    b.Property<string>("StateSource")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .UseCollation("C");

                    b.Property<string>("WorkflowDefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .UseCollation("C");

                    b.Property<string>("WorkflowDefinitionIdLookupHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .UseCollation("C");

                    b.HasKey("ScopeKey", "IdLookupHash");

                    b.HasIndex("ScopeKey", "WorkflowDefinitionIdLookupHash", "LastModifiedAt", "IdLookupHash");

                    b.ToTable("elsa_workflow_definition_drafts", (string)null);
                });

            modelBuilder.Entity("Elsa.Workflows.Design.Persistence.Core.Entities.WorkflowDefinitionDraftLayout", b =>
                {
                    b.Property<string>("ScopeKey")
                        .HasMaxLength(65)
                        .HasColumnType("character varying(65)")
                        .UseCollation("C");

                    b.Property<string>("IdLookupHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .UseCollation("C");

                    b.Property<string>("ActivityPresentationJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .UseCollation("C");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecordsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .UseCollation("C");

                    b.Property<string>("WorkflowDefinitionDraftId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .UseCollation("C");

                    b.Property<string>("WorkflowDefinitionDraftIdLookupHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .UseCollation("C");

                    b.HasKey("ScopeKey", "IdLookupHash");

                    b.HasIndex("ScopeKey", "WorkflowDefinitionDraftIdLookupHash")
                        .IsUnique();

                    b.ToTable("elsa_workflow_definition_draft_layouts", (string)null);
                });

            modelBuilder.Entity("Elsa.Workflows.Design.Persistence.Core.Entities.WorkflowDefinitionVersion", b =>
                {
                    b.Property<string>("ScopeKey")
                        .HasMaxLength(65)
                        .HasColumnType("character varying(65)")
                        .UseCollation("C");

                    b.Property<string>("IdLookupHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .UseCollation("C");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .UseCollation("C");

                    b.Property<string>("DefinitionIdLookupHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .UseCollation("C");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .UseCollation("C");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SemVerSortKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .UseCollation("C");

                    b.Property<DateTimeOffset?>("SourceCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceDraftId")
                        .HasColumnType("text");

                    b.Property<string>("StateSource")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .UseCollation("C");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .UseCollation("C");

                    b.HasKey("ScopeKey", "IdLookupHash");

                    b.HasIndex("ScopeKey", "DefinitionIdLookupHash", "SemVerSortKey")
                        .IsUnique()
                        .HasDatabaseName("UX_elsa_workflow_definition_versions_semver_identity");

                    b.ToTable("elsa_workflow_definition_versions", (string)null);
                });

            modelBuilder.Entity("Elsa.Workflows.Design.Persistence.Core.Entities.WorkflowDefinitionVersionLayout", b =>
                {
                    b.Property<string>("ScopeKey")
                        .HasMaxLength(65)
                        .HasColumnType("character varying(65)")
                        .UseCollation("C");

                    b.Property<string>("IdLookupHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .UseCollation("C");

                    b.Property<string>("ActivityPresentationJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .UseCollation("C");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecordsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .UseCollation("C");

                    b.Property<string>("WorkflowDefinitionVersionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .UseCollation("C");

                    b.Property<string>("WorkflowDefinitionVersionIdLookupHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .UseCollation("C");

                    b.HasKey("ScopeKey", "IdLookupHash");

                    b.HasIndex("ScopeKey", "WorkflowDefinitionVersionIdLookupHash")
                        .IsUnique();

                    b.ToTable("elsa_workflow_definition_version_layouts", (string)null);
                });

            modelBuilder.Entity("Elsa.Workflows.Design.Persistence.EntityFrameworkCore.Entities.DesignOperationEntity", b =>
                {
                    b.Property<string>("ScopeKey")
                        .HasMaxLength(65)
                        .HasColumnType("character varying(65)")
                        .UseCollation("C");

                    b.Property<string>("OperationKindLookupHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .UseCollation("C");

                    b.Property<string>("OperationKeyLookupHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .UseCollation("C");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .UseCollation("C");

                    b.Property<string>("OperationKind")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .UseCollation("C");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .UseCollation("C");

                    b.Property<string>("ResultFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .UseCollation("C");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .UseCollation("C");

                    b.HasKey("ScopeKey", "OperationKindLookupHash", "OperationKeyLookupHash");

                    b.ToTable("elsa_design_operations", (string)null);
                });

            modelBuilder.Entity("Elsa.Workflows.Design.Persistence.Core.Entities.WorkflowDefinitionDraft", b =>
                {
                    b.HasOne("Elsa.Workflows.Design.Persistence.Core.Entities.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany()
                        .HasForeignKey("ScopeKey", "WorkflowDefinitionIdLookupHash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("Elsa.Workflows.Design.Persistence.Core.Entities.WorkflowDefinitionDraftLayout", b =>
                {
                    b.HasOne("Elsa.Workflows.Design.Persistence.Core.Entities.WorkflowDefinitionDraft", "WorkflowDefinitionDraft")
                        .WithOne()
                        .HasForeignKey("Elsa.Workflows.Design.Persistence.Core.Entities.WorkflowDefinitionDraftLayout", "ScopeKey", "WorkflowDefinitionDraftIdLookupHash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowDefinitionDraft");
                });

            modelBuilder.Entity("Elsa.Workflows.Design.Persistence.Core.Entities.WorkflowDefinitionVersion", b =>
                {
                    b.HasOne("Elsa.Workflows.Design.Persistence.Core.Entities.WorkflowDefinition", "Definition")
                        .WithMany()
                        .HasForeignKey("ScopeKey", "DefinitionIdLookupHash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Definition");
                });

            modelBuilder.Entity("Elsa.Workflows.Design.Persistence.Core.Entities.WorkflowDefinitionVersionLayout", b =>
                {
                    b.HasOne("Elsa.Workflows.Design.Persistence.Core.Entities.WorkflowDefinitionVersion", "WorkflowDefinitionVersion")
                        .WithOne()
                        .HasForeignKey("Elsa.Workflows.Design.Persistence.Core.Entities.WorkflowDefinitionVersionLayout", "ScopeKey", "WorkflowDefinitionVersionIdLookupHash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowDefinitionVersion");
                });
#pragma warning restore 612, 618
        }
    }
}
