<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Elsa.Platform.PackageManifest.Generator" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Core/Elsa.Workflows.ExecutionEvidence.Core.csproj" />
    <ProjectReference Include="../Elsa.Workflows.ExecutionEvidence.csproj" />
    <ProjectReference Include="../../../Api/FastEndpoints/Elsa.Api.FastEndpoints.csproj" />
    <ProjectReference Include="../../../Api/Capabilities/Elsa.Api.Capabilities.csproj" />
  </ItemGroup>

</Project>
