<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\src\essentials\Diagnostics\Persistence\Elsa.Diagnostics.Persistence.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\essentials\Diagnostics\OpenTelemetry\Elsa.Diagnostics.OpenTelemetry.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\essentials\Diagnostics\OpenTelemetry\Core\Elsa.Diagnostics.OpenTelemetry.Core.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\essentials\Diagnostics\StructuredLogs\Elsa.Diagnostics.StructuredLogs.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\essentials\Diagnostics\StructuredLogs\Core\Elsa.Diagnostics.StructuredLogs.Core.csproj" />
  </ItemGroup>

</Project>
