<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Elsa.Platform.PackageManifest.Generator" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Core\**\*.cs" />
    <Compile Remove="Models\**\*.cs" />
    <Compile Remove="Requests\**\*.cs" />
    <Compile Remove="Commands\**\*.cs" />
    <Compile Include="Models\ActivityExecutionProblemDetails.cs" />
    <Compile Include="Requests\GetActivityExecutionValuePayload.cs" />
    <Compile Include="Requests\ListWorkflowInstances.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="Core\Elsa.Workflows.Runtime.Api.Core.csproj" />
    <ProjectReference Include="..\Core\Elsa.Workflows.Runtime.Core.csproj" />
    <ProjectReference Include="..\Elsa.Workflows.Runtime.csproj" />
    <ProjectReference Include="..\..\..\Foundation\Identity\Abstractions\Elsa.Foundation.Identity.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\Api\Capabilities\Elsa.Api.Capabilities.csproj" />
    <ProjectReference Include="..\..\..\Mediator\Core\Elsa.Mediator.Core.csproj" />
  </ItemGroup>

</Project>
