<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Elsa.Platform.PackageManifest.Generator" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Elsa.Workflows.Runtime.Core.csproj" />
    <ProjectReference Include="..\Elsa.Workflows.Runtime.csproj" />
    <ProjectReference Include="..\..\..\Foundation\Identity\Abstractions\Elsa.Foundation.Identity.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\Api\Capabilities\Elsa.Api.Capabilities.csproj" />
    <ProjectReference Include="..\..\..\Mediator\Core\Elsa.Mediator.Core.csproj" />
  </ItemGroup>

</Project>
