<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="CShells.Abstractions" />
    <PackageReference Include="Elsa.Platform.PackageManifest.Generator" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Runtime\Core\Elsa.Activities.Runtime.Core.csproj" />
    <ProjectReference Include="..\Runtime\Elsa.Activities.Runtime.csproj" />
    <ProjectReference Include="..\..\Primitives\Primitives\Elsa.Primitives.csproj" />
    <ProjectReference Include="..\..\Serialization\Core\Elsa.Serialization.Core.csproj" />
    <ProjectReference Include="..\..\Workflows\Runtime\Core\Elsa.Workflows.Runtime.Core.csproj" />
  </ItemGroup>

</Project>
