<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <PackageReference Include="Groundwork.Sqlite" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="CShells" />
    <PackageReference Include="CShells.AspNetCore" />
    <PackageReference Include="CShells.AspNetCore.Abstractions" />
    <PackageReference Include="CShells.FastEndpoints" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Elsa\Secrets\Core\Elsa.Secrets.Core.csproj" />
    <ProjectReference Include="..\..\..\..\src\Elsa\Secrets\Elsa.Secrets.csproj" />
    <ProjectReference Include="..\..\..\..\src\Elsa\Secrets\Api\Elsa.Secrets.Api.csproj" />
    <ProjectReference Include="..\..\..\..\src\Elsa\Api\AspNetCore\Elsa.Api.AspNetCore.csproj" />
    <ProjectReference Include="..\..\..\..\src\Elsa\Foundation\Identity\Abstractions\Elsa.Foundation.Identity.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\..\src\Elsa\Secrets\Persistence\Groundwork\Elsa.Secrets.Persistence.Groundwork.csproj" />
    <ProjectReference Include="..\..\..\..\src\Elsa\Expressions\Elsa.Expressions.csproj" />
    <ProjectReference Include="..\..\..\..\src\Elsa\Workflows\Runtime\Elsa.Workflows.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Persistence\Groundwork\Testing\Elsa.Persistence.Groundwork.Testing.csproj" />
    <ProjectReference Include="../../Api/Compatibility/Testing/Elsa.Api.Compatibility.Testing.csproj" />
    <Using Include="Elsa.Persistence.Groundwork.Testing" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Baselines/*.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Never" />
  </ItemGroup>

</Project>
