<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <PackageReference Include="Groundwork.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Elsa\Secrets\Core\Elsa.Secrets.Core.csproj" />
    <ProjectReference Include="..\..\..\..\src\Elsa\Secrets\Elsa.Secrets.csproj" />
    <ProjectReference Include="..\..\..\..\src\Elsa\Secrets\Api\Elsa.Secrets.Api.csproj" />
    <ProjectReference Include="..\..\..\..\src\Elsa\Secrets\Persistence\Groundwork\Elsa.Secrets.Persistence.Groundwork.csproj" />
    <ProjectReference Include="..\..\..\..\src\Elsa\Expressions\Elsa.Expressions.csproj" />
    <ProjectReference Include="..\..\..\..\src\Elsa\Workflows\Runtime\Elsa.Workflows.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Persistence\Groundwork\Testing\Elsa.Persistence.Groundwork.Testing.csproj" />
    <Using Include="Elsa.Persistence.Groundwork.Testing" />
  </ItemGroup>

</Project>
