<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Persistence/**/*" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CShells.Abstractions" />
    <PackageReference Include="CShells.AspNetCore.Abstractions" />
    <PackageReference Include="Elsa.Specifications.PackageManifest.Generator" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\..\essentials\Activities\Design\Persistence\Core\Elsa.Activities.Design.Persistence.Core.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\essentials\Api\AspNetCore\Elsa.Api.AspNetCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\essentials\Foundation\Identity\Core\Elsa.Foundation.Identity.Core.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\essentials\Foundation\Identity\Elsa.Foundation.Identity.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\essentials\Activities\Design\Core\Elsa.Activities.Design.Core.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\essentials\Events\Core\Elsa.Events.Core.csproj" />
    <ProjectReference Include="..\..\..\Models\Elsa3.Models.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\essentials\Serialization\Core\Elsa.Serialization.Core.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\essentials\Workflows\Design\Persistence\Core\Elsa.Workflows.Design.Persistence.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NativeEndpoints" />
  </ItemGroup>

</Project>
