<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Elsa.Platform.PackageManifest.Generator" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Elsa.Secrets.csproj" />
    <ProjectReference Include="..\Core\Elsa.Secrets.Core.csproj" />
    <ProjectReference Include="..\..\Api\FastEndpoints\Elsa.Api.FastEndpoints.csproj" />
    <ProjectReference Include="..\..\Mediator\Core\Elsa.Mediator.Core.csproj" />
    <ProjectReference Include="..\..\Foundation\Identity\Abstractions\Elsa.Foundation.Identity.Abstractions.csproj" />
  </ItemGroup>

</Project>
