<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="CShells.Abstractions" />
    <PackageReference Include="CShells.AspNetCore.Abstractions" />
    <PackageReference Include="Elsa.Platform.PackageManifest.Generator" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Elsa.Secrets.csproj" />
    <ProjectReference Include="..\Core\Elsa.Secrets.Core.csproj" />
    <ProjectReference Include="..\..\Api\AspNetCore\Elsa.Api.AspNetCore.csproj" />
    <ProjectReference Include="..\..\Foundation\Identity\Abstractions\Elsa.Foundation.Identity.Abstractions.csproj" />
  </ItemGroup>

</Project>
