// <auto-generated />
using Elsa.Workflows.Runtime.Distributed.Persistence.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elsa.Workflows.Runtime.Distributed.Persistence.EntityFrameworkCore.Migrations.ExecutionPlacement.Sqlite
{
    [DbContext(typeof(ExecutionPlacementSqliteDbContext))]
    [Migration("20260928035702_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Elsa.Persistence.EntityFramework.SchemaFinalization.EfDatabaseIdentityRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DatabaseIdentity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SchemaVersion");

                    b.ToTable("__ElsaDatabaseIdentity_ElsaDistributedExecutionPlacement", (string)null);
                });

            modelBuilder.Entity("Elsa.Persistence.EntityFramework.SchemaFinalization.EfSchemaFinalizationRecordRow", b =>
                {
                    b.Property<string>("Family")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabaseIdentity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalizedVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("FinishHistoryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FinishJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("HistoryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HoldsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IntentJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Family");

                    b.HasIndex("SchemaVersion");

                    b.ToTable("__ElsaSchemaFinalization_ElsaDistributedExecutionPlacement", (string)null);
                });

            modelBuilder.Entity("Elsa.Workflows.Runtime.Distributed.Persistence.EntityFrameworkCore.Entities.ExecutionPlacementLeaseEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AcquiredAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpiresAtOffsetMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerIdHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("PlacementToken")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeKeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowExecutionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("WorkflowExecutionIdOrderKey")
                        .IsRequired()
                        .HasMaxLength(258)
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("SchemaVersion");

                    b.HasIndex("ScopeKeyHash", "OwnerIdHash", "IsReleased", "ExpiresAtUtcTicks", "WorkflowExecutionIdOrderKey");

                    b.ToTable("elsa_distributed_execution_placement", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
