// <auto-generated />
using Elsa.Persistence.EntityFrameworkCore.MySql.FeasibilityTests;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elsa.Persistence.EntityFrameworkCore.MySql.FeasibilityTests.Migrations
{
    [DbContext(typeof(SecretsMySqlDbContext))]
    [Migration("20260912081709_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_bin")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            global::MySql.EntityFrameworkCore.Extensions.MySQLModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("Elsa.Secrets.Persistence.EntityFrameworkCore.Entities.SecretRecord", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_bin");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_bin");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("DisplayNameSearchKey")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_bin");

                    b.Property<bool>("HasNonExpiringActiveVersion")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("MaxActiveVersionExpiresAt")
                        .HasColumnType("bigint");

                    b.Property<string>("NameSearchKey")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_bin");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("ScopeLookupKey")
                        .HasColumnType("longtext")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_bin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("StoreNameLookupKey")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_bin");

                    b.Property<string>("TypeNameLookupKey")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_bin");

                    b.HasKey("TenantId", "NormalizedName");

                    b.HasIndex("TenantId", "Status", "NormalizedName")
                        .HasDatabaseName("IX_elsa_secrets_tenantId_status_normalizedName");

                    b.ToTable("elsa_secrets", (string)null);

                    b.HasAnnotation("MySQL:Collation", "utf8mb4_bin");
                });
#pragma warning restore 612, 618
        }
    }
}
