// <auto-generated />
using Elsa.Secrets.Persistence.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Elsa.Secrets.Persistence.EntityFrameworkCore.Migrations.PostgreSql;

[DbContext(typeof(SecretsPostgreSqlDbContext))]
[Migration("20260910210216_Initial")]
partial class Initial
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        // NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns omitted: the module stays provider-free.
        modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

        modelBuilder.Entity("Elsa.Secrets.Persistence.EntityFrameworkCore.Entities.SecretRecord", b =>
            {
                b.Property<string>("TenantId")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<string>("NormalizedName")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<byte[]>("ConcurrencyToken")
                    .IsConcurrencyToken()
                    .IsRequired()
                    .HasColumnType("bytea");

                b.Property<string>("DisplayNameSearchKey")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<bool>("HasNonExpiringActiveVersion")
                    .HasColumnType("boolean");

                b.Property<DateTimeOffset?>("MaxActiveVersionExpiresAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("NameSearchKey")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Payload")
                    .IsRequired()
                    .HasColumnType("jsonb");

                b.Property<string>("ScopeLookupKey")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.Property<string>("StoreNameLookupKey")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<string>("TypeNameLookupKey")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.HasKey("TenantId", "NormalizedName");

                b.HasIndex("TenantId", "Status", "NormalizedName")
                    .HasDatabaseName("IX_elsa_secrets_tenantId_status_normalizedName");

                b.ToTable("elsa_secrets", (string)null);
            });
#pragma warning restore 612, 618
    }
}
